const {chromium}=require('../qa-browser.cjs'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:950}}),errors=[],rows=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Movement QA');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);
for(const cast of ['nova','eli','sam']){await p.evaluate(c=>{profile.appearance.character=c;profile.equippedWear={};applyHumanAppearance();},cast);await p.waitForFunction(c=>humanLoaded===c,cast);
const preview=await p.evaluate(()=>{const before=JSON.stringify(profile.equippedWear);previewClothingItem('clothing-pants-tech');const visible=FittedWardrobe.state.extension?.visible;clothingPreview=null;applyHumanAppearance();return{before,after:JSON.stringify(profile.equippedWear),visible,removed:FittedWardrobe.state.extension?.visible||false};});assert.equal(preview.before,preview.after);assert.equal(preview.removed,false);if(cast==='nova')assert(preview.visible);
await p.evaluate(()=>{profile.equippedWear={top:'clothing-vest-led',pants:'clothing-pants-tech',shoes:'clothing-shoes-cyan',hands:'clothing-gloves-stage',badge:'clothing-pin-vj'};clothingPreview=null;applyHumanAppearance();});
for(const phase of [0,1.5,3,4.5]){const result=await p.evaluate(phase=>{
 const original={parent:player.parent,pos:player.position.clone(),q:player.quaternion.clone(),classes:document.body.className,walking:player.userData.walking,visible:player.visible};document.body.classList.remove('shop-closet');document.body.classList.add('studio-world-view');player.userData.walking=true;humanStride=phase;updateHumanCharacter(.01);
 const s=new THREE.Scene();s.background=new THREE.Color(0x253340);s.add(new THREE.HemisphereLight(0xe9f3ff,0x454348,1));const key=new THREE.DirectionalLight(0xffffff,1.8);key.position.set(2,4,3);s.add(key);s.add(player);player.visible=true;player.position.set(0,0,0);player.rotation.set(0,0,0);player.updateMatrixWorld(true);
 const r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setSize(640,900);r.outputEncoding=THREE.sRGBEncoding;r.toneMapping=THREE.ACESFilmicToneMapping;const c=new THREE.PerspectiveCamera(33,640/900,.01,20);c.position.set(2.7,1.10,1.6);c.lookAt(0,.92,0);r.render(s,c);
 const extension=FittedWardrobe.state.extension;let bounds=null;if(extension){extension.skeleton.update();const box=new THREE.Box3(),v=new THREE.Vector3();for(let i=0;i<extension.geometry.attributes.position.count;i++){v.fromBufferAttribute(extension.geometry.attributes.position,i);extension.boneTransform(i,v);box.expandByPoint(v);}bounds={min:box.min.toArray(),max:box.max.toArray(),size:box.getSize(new THREE.Vector3()).toArray()};}
 const check=document.createElement('canvas');check.width=64;check.height=90;const cx=check.getContext('2d');cx.drawImage(r.domElement,0,0,64,90);const pixels=cx.getImageData(0,0,64,90).data;let occupied=0;for(let i=0;i<pixels.length;i+=4)if(Math.abs(pixels[i]-pixels[0])+Math.abs(pixels[i+1]-pixels[1])+Math.abs(pixels[i+2]-pixels[2])>25)occupied++;const coverage=occupied/(64*90);const image=r.domElement.toDataURL();r.dispose();r.forceContextLoss();original.parent.add(player);player.visible=original.visible;player.position.copy(original.pos);player.quaternion.copy(original.q);player.userData.walking=false;updateHumanCharacter(0);player.userData.walking=original.walking;document.body.className=original.classes;player.updateMatrixWorld(true);return{image,bounds,coverage};},phase);
 assert(result.coverage>.075,`Visible moving character: ${cast}, ${phase}`);if(result.bounds){assert(result.bounds.size[1]>.72&&result.bounds.size[1]<1.3);assert(result.bounds.size.every(Number.isFinite));}fs.writeFileSync(`documentation/natural-wardrobe-20260915/${cast}-walk-${phase}.png`,Buffer.from(result.image.split(',')[1],'base64'));rows.push({cast,phase,bounds:result.bounds});}
}
await p.evaluate(()=>{saveSlots();});const saved=await p.evaluate(()=>JSON.stringify(profile.equippedWear));await p.reload();await p.locator('#studio-entry-button').click();await p.waitForFunction(()=>player.userData.loaded);assert.equal(await p.evaluate(()=>JSON.stringify(profile.equippedWear)),saved);assert.equal(await p.evaluate(()=>FittedWardrobe.state.uniforms.wardrobePants.value),2);
await p.evaluate(()=>{profile.settings.thirdPerson=true;profile.studioWorld.x=0;profile.studioWorld.z=10;profile.studioWorld.yaw=0;StudioWorld.enter();});const from=await p.evaluate(()=>({x:profile.studioWorld.x,z:profile.studioWorld.z}));await p.keyboard.down('w');await p.waitForTimeout(500);await p.screenshot({path:'documentation/natural-wardrobe-20260915/actual-walking.png'});await p.keyboard.up('w');const to=await p.evaluate(()=>({x:profile.studioWorld.x,z:profile.studioWorld.z}));assert(Math.hypot(to.x-from.x,to.z-from.z)>.1);
assert.deepEqual(errors,[]);fs.writeFileSync('documentation/natural-wardrobe-20260915/motion.json',JSON.stringify({rows,from,to,errors},null,2));console.log('PASS: preview is reversible, twelve walking poses, real keyboard movement, garment bounds, saved outfit restored');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
