const {chromium}=require('../qa-browser.cjs'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Fitted QA');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);await p.evaluate(()=>{StudioWorld.showComputer();openApp('shop');shopView='clothing';renderShop();});
const rows=[];for(const cast of ['nova','eli','sam']){await p.evaluate(c=>{profile.appearance.character=c;profile.equippedWear={top:'clothing-jacket-reflective',pants:'clothing-pants-tech',shoes:'clothing-shoes-cyan',headphones:'clothing-headphones-basic'};applyHumanAppearance();},cast);await p.waitForFunction(c=>humanLoaded===c,cast);await p.waitForTimeout(250);await p.screenshot({path:`documentation/natural-wardrobe-20260915/${cast}-shop.png`});
for(const top of ['jacket-reflective','vest-led','hoodie-vj']){await p.evaluate(top=>{profile.equippedWear.top='clothing-'+top;applyHumanAppearance()},top);const data=await p.evaluate(()=>{const meshes=[],props=[];player.traverse(o=>{if(o.isSkinnedMesh)meshes.push({name:o.name,uniforms:!!o.material.userData?.surfaceWardrobe,attributes:!!o.geometry.attributes.wardrobePosition});if(o.userData.wearAttachment)props.push(o.userData.itemId)});return{cast:humanLoaded,meshes,props,extension:FittedWardrobe.state.extension?.visible||false};});assert(data.props.every(id=>/head|cap|beanie|mask/.test(id)));assert(data.meshes.every(m=>m.attributes));if(cast==='nova')assert(data.extension);rows.push(data);
for(const angle of [0,.75,1.55]){const png=await p.evaluate(angle=>{const prior={parent:player.parent,pos:player.position.clone(),q:player.quaternion.clone()};const s=new THREE.Scene();s.background=new THREE.Color(0x253340);s.add(new THREE.HemisphereLight(0xe9f3ff,0x47434b,1.2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(2,4,3);s.add(key);const rim=new THREE.DirectionalLight(0x9fcbd5,1);rim.position.set(-2,2,-1);s.add(rim);s.add(player);player.position.set(0,0,0);player.rotation.set(0,0,0);player.updateWorldMatrix(true,true);const r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setSize(640,900);r.outputEncoding=THREE.sRGBEncoding;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1;const c=new THREE.PerspectiveCamera(32,640/900,.01,20);c.position.set(Math.sin(angle)*3.25,1.12,Math.cos(angle)*3.25);c.lookAt(0,.93,0);r.render(s,c);const out=r.domElement.toDataURL();r.dispose();r.forceContextLoss();prior.parent.add(player);player.position.copy(prior.pos);player.quaternion.copy(prior.q);player.updateWorldMatrix(true,true);return out;},angle);fs.writeFileSync(`documentation/natural-wardrobe-20260915/${cast}-${top}-${angle}.png`,Buffer.from(png.split(',')[1],'base64'));}
}
await p.evaluate(()=>{profile.equippedWear={};profile.appearance.headphones=false;applyHumanAppearance();});assert.equal(await p.evaluate(()=>FittedWardrobe.state.extension?.visible||false),false);
}
assert.deepEqual(errors,[]);fs.writeFileSync('documentation/natural-wardrobe-20260915/tests.json',JSON.stringify({rows,errors},null,2));console.log('PASS: 3 bodies, 3 garment styles, front/quarter/side renders, no rigid cloth props, full trousers and removal');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
