const {chromium}=require('../qa-browser.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1280,height:900}}),errors=[],dir='documentation/quality-pass-20260915';p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Cindy · DMTeam');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);await p.evaluate(()=>{StudioWorld.showComputer();profile.settings.reducedMotion=true;});await p.waitForTimeout(500);
 for(const size of [{width:1280,height:900},{width:1116,height:717},{width:390,height:844}]){await p.setViewportSize(size);await p.waitForTimeout(100);await p.screenshot({path:`${dir}/desktop-${size.width}.png`});
  const result=await p.locator('.desktop-icons .desktop-icon').evaluateAll(es=>es.map(e=>{e.scrollIntoView({block:'center',inline:'nearest'});const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{text:e.textContent,hit:hit===e||e.contains(hit),right:r.right,left:r.left,icon:getComputedStyle(e).getPropertyValue('--app-symbol')};}));assert(result.every(r=>r.hit&&r.right<=size.width&&r.left>=0&&r.icon),JSON.stringify(result));}
 await p.setViewportSize({width:1280,height:900});await p.locator('[data-rehearsal-launch]').click();const original=await p.evaluate(()=>({money:profile.money,xp:profile.stats.xp,day:profile.day,gigs:profile.gigs.map(g=>g.status)}));
 await p.locator('[data-rehearsal-passage="2"]').click();assert.equal(await p.evaluate(()=>StudioRehearsal.show.elapsed),30);assert.equal(await p.evaluate(()=>StudioRehearsal.show.paused),true);
 await p.locator('[data-rehearsal-go]').click();await p.locator('[data-live-intensity]').fill('85');await p.locator('[data-live-intensity]').dispatchEvent('input');await p.locator('[data-live-suggest]').click();assert.equal(await p.locator('#studio-rehearsal [data-clip-energy]').inputValue(),'peak');
 const current=await p.evaluate(()=>StudioRehearsal.show.currentIndex);const card=p.locator(`#studio-rehearsal [data-resolute-clip]:not([data-resolute-clip="${current}"])`).first();await card.click();await p.waitForFunction(()=>StudioRehearsal.show.preview.readyState>=2);await p.locator('[data-live-sync]').click();await p.waitForFunction(()=>StudioRehearsal.show.stageTasks[2],null,{timeout:10000});await p.screenshot({path:`${dir}/live-peak.png`});
 await p.locator('[data-rehearsal-result]').waitFor({state:'visible',timeout:18000});assert.equal(await p.evaluate(()=>StudioRehearsal.show.elapsed),45);assert(await p.locator('[data-rehearsal-result]').textContent().then(x=>x.includes('1/1')));assert.equal(await p.locator('[data-rehearsal-desk]').isVisible(),false);await p.screenshot({path:`${dir}/passage-result.png`});
 const best=await p.evaluate(()=>profile.settings.rehearsalBests);assert(Object.values(best).some(v=>v.gesture&&v.percent>80));const after=await p.evaluate(()=>({money:profile.money,xp:profile.stats.xp,day:profile.day,gigs:profile.gigs.map(g=>g.status)}));assert.deepEqual(after,original);
 await p.locator('[data-rehearsal-close]').click();await p.reload();await p.locator('#studio-entry-button').click();await p.evaluate(()=>StudioWorld.showComputer());await p.locator('[data-rehearsal-launch]').click();await p.locator('[data-rehearsal-result]').waitFor();assert.deepEqual(await p.evaluate(()=>profile.settings.rehearsalBests),best);
 await p.locator('[data-rehearsal-retry="2"]').click();assert.equal(await p.evaluate(()=>StudioRehearsal.show.elapsed),30);assert(await p.locator('[data-rehearsal-desk]').isVisible());await p.locator('[data-rehearsal-whole]').click();assert.equal(await p.evaluate(()=>StudioRehearsal.show.elapsed),0);await p.locator('[data-rehearsal-close]').click();
 await p.locator('.relax-game-icon').click();await p.locator('.relax-game-window').waitFor({state:'visible'});await p.locator('[data-relax-close]').click();
 assert.deepEqual(errors,[]);fs.writeFileSync(`${dir}/tests.json`,JSON.stringify({original,after,best,errors},null,2));console.log('PASS: all desktop launchers reachable at three sizes, real 15s peak drill and synchronized fade, suggested clips, result and record reload, replay, return to full set, no career rewards, Pause app');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
