const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Test contrat');await p.locator('#create-vj-button').click();await p.locator('[data-world-computer]').click();await p.locator('.app-button[data-app="social"]').click();const apply=p.locator('[data-simple-apply]').first(),id=await apply.getAttribute('data-simple-apply');await apply.click();const pending=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(pending.status,'pending');for(let i=0;i<7;i++){if(await p.evaluate(id=>profile.gigs.find(g=>g.id===id).status!=='pending',id))break;await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-hours]').fill('12');await p.locator('[data-sleep-hours]').dispatchEvent('input');await p.locator('[data-sleep-confirm]').click();}const offer=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(offer.status,'offered');await p.locator('#app-window').getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(250);await p.locator('.app-button[data-app="social"]').click();
await p.locator('[data-simple-email]').first().click();
const emailId=await p.evaluate(id=>profile.emails.find(e=>e.gigId===id&&e.type==='gig-offer').id,id);await p.locator(`[data-email="${emailId}"]`).click();await p.locator('[data-email-action="accept-gig"]').click();assert(await p.locator('#app-window .traffic.red').isVisible());
let accepted=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(accepted.status,'accepted');
while(await p.evaluate(id=>profile.day<getGigAbsoluteDay(profile.gigs.find(g=>g.id===id)),id)){await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-hours]').fill('12');await p.locator('[data-sleep-hours]').dispatchEvent('input');await p.locator('[data-sleep-confirm]').click();}
await p.locator('#app-window').getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(250);await p.locator('.app-button[data-app="social"]').click();await p.locator(`[data-simple-id="${id}"]`).click();
await p.locator('#gig-setup-start-button').click();
await p.waitForTimeout(400);assert(await p.evaluate(()=>document.body.classList.contains('screen-gig')));assert.equal(await p.evaluate(()=>profile.money),await p.evaluate(id=>75-calculateTransportCost(profile.gigs.find(g=>g.id===id)).cost,id));await p.locator('#first-show-coach').waitFor({state:'visible'});await p.screenshot({path:'documentation/seven-steps-20260915/first-show-guide.png'});await p.locator('#connect-projector-button').click();await p.locator('#start-live-button').click();await p.waitForFunction(()=>liveShow?.started);await p.locator('[data-live-view]').click();await p.locator('[data-live-intensity]').fill('35');await p.locator('[data-live-intensity]').dispatchEvent('input');await p.locator('[data-live-sync]').click();
await p.screenshot({path:'documentation/seven-steps-20260915/first-show-live-guide.png'});let lastPhase=-1;for(let n=0;n<180;n++){if(await p.locator('#result-modal').isVisible())break;const t=await p.evaluate(()=>liveShow?.elapsed||0),phase=Math.min(3,Math.floor(t/15));if(phase!==lastPhase){lastPhase=phase;const value=['35','60','85','25'][phase];await p.locator('[data-live-intensity]').fill(value);await p.locator('[data-live-intensity]').dispatchEvent('input');console.log('Live phase',phase,'temps',t);}await p.waitForTimeout(1000);}
assert(await p.locator('#result-modal').isVisible(),'Le bilan doit s’ouvrir automatiquement');await p.locator('[data-payment-receipt]').click();assert((await p.locator('#bank-receipt').innerText()).includes('Garage de quartier'));await p.getByRole('button',{name:'Fermer le reçu',exact:true}).click();const bilan=await p.locator('#result-modal').innerText();assert(bilan.includes('sur le temps 1'),'Synchronized fade should appear in the result');await p.screenshot({path:'documentation/audit-official-20260914/contract-bilan.png'});const paid=await p.evaluate(()=>({money:profile.money,bank:profile.bank.transactions,gig:profile.gigs.find(g=>g.status==='done')}));assert(paid.bank.some(r=>r.label.startsWith('Cachet')&&r.amount>0));const bankSum=paid.bank.reduce((sum,r)=>sum+r.amount,0);assert.equal(paid.money,75+bankSum);await p.locator('#result-close-button').click();await p.reload();await p.locator('#studio-entry-button').click();assert.equal(await p.evaluate(()=>profile.money),paid.money);assert.equal(await p.evaluate(()=>profile.bank.transactions.length),paid.bank.length);
fs.writeFileSync('documentation/seven-steps-20260915/after-first-save.json',await p.evaluate(()=>localStorage.getItem(SAVE_KEY)));await p.evaluate(()=>{StudioWorld.showComputer();openApp('shop');shopView='gear';shopGearFilter='projector';renderShop();});
const balanceBefore=await p.evaluate(()=>profile.money);await p.locator('[data-buy="projector-standard"]').click();const purchased=await p.evaluate(()=>({balance:profile.money,owned:profile.ownedItems.includes('projector-standard'),gear:profile.gear.projector,level:profile.stats.level}));console.log('UPGRADE',purchased);assert(purchased.owned);assert(purchased.balance<balanceBefore);
const nextId=await p.evaluate(()=>profile.gigs.find(g=>g.referredBy&&g.status==='offered')?.id);assert(nextId,'A referral should offer a reachable next contract');
await p.evaluate(()=>openApp('email'));const nextEmail=await p.evaluate(id=>profile.emails.find(e=>e.gigId===id&&e.type==='gig-offer').id,nextId);await p.locator(`[data-email="${nextEmail}"]`).click();await p.locator('[data-email-action="accept-gig"]').click();
while(await p.evaluate(id=>profile.day<getGigAbsoluteDay(profile.gigs.find(g=>g.id===id)),nextId)){await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-hours]').fill('12');await p.locator('[data-sleep-hours]').dispatchEvent('input');await p.locator('[data-sleep-confirm]').click();}
await p.evaluate(()=>openApp('social'));await p.locator(`[data-simple-id="${nextId}"]`).click();console.log('NEXT STATE',await p.evaluate(id=>{const g=profile.gigs.find(g=>g.id===id);return{g,missing:getMissingSkills(g),world:getGigWorldRequirements(g),can:canPlayGig(g),day:profile.day,money:profile.money,notes:profile.notifications.slice(-4)}},nextId));console.log('NEXT COST',await p.locator('#gig-setup-summary').innerText());assert(await p.locator('#gig-setup-start-button').isVisible(),'Next contract setup should open');assert(await p.locator('#gig-setup-start-button').isEnabled(),'First upgrade must leave enough for the next trip');await p.locator('#gig-setup-start-button').click();await p.waitForFunction(()=>document.body.classList.contains('screen-gig'));
await p.locator('#connect-projector-button').click();await p.locator('#start-live-button').click();await p.locator('[data-live-view]').click();await p.waitForFunction(()=>liveShow?.preview?.readyState>=2);await p.locator('[data-live-take]').click();let paused=false;
for(let n=0;n<85;n++){if(await p.locator('#result-modal').isVisible())break;const state=await p.evaluate(()=>({elapsed:liveShow.elapsed,paused:liveShow.paused,hidden:document.hidden,completed:liveShow.completed}));if(n%10===0)console.log('SECOND LIVE',state);if(state.completed){await p.waitForTimeout(300);continue;}const cue=await p.evaluate(()=>liveShow.cues[liveShow.cueIndex||0]);await p.locator('[data-live-intensity]').fill(String(Math.round((cue.low+cue.high)/2)));await p.locator('[data-live-intensity]').dispatchEvent('input');if(!paused&&await p.evaluate(()=>liveShow.elapsed>20)){await p.locator('[data-live-pause]').click();const frozen=await p.evaluate(()=>liveShow.elapsed);await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>liveShow.elapsed),frozen);await p.locator('[data-live-pause]').click();assert.equal(await p.evaluate(()=>liveShow.paused),false);console.log('PAUSE RESUMED');paused=true;}await p.waitForTimeout(1000);}
assert(await p.locator('#result-modal').isVisible());const final=await p.evaluate(()=>({money:profile.money,day:profile.day,sessions:profile.showSessions,level:profile.stats.level,gear:profile.gear.projector,relations:profile.clientRelations,bank:profile.bank.transactions}));assert.equal(final.sessions,2);assert(final.money>=0);await p.screenshot({path:'documentation/seven-steps-20260915/second-show-result.png'});await p.locator('#result-close-button').click();await p.reload();await p.waitForFunction(()=>profile?.created);assert.equal(await p.evaluate(()=>profile.money),final.money);assert.equal(await p.evaluate(()=>profile.gear.projector),'standard');fs.writeFileSync('documentation/live-upgrade-20260915/career-loop.json',JSON.stringify({balanceBefore,purchased,final,paused,errors},null,2));console.log('CAREER LOOP',JSON.stringify(final));
assert.deepEqual(errors,[]);fs.writeFileSync('documentation/seven-steps-20260915/first-contract.json',JSON.stringify({accepted,bilan,paid,errors,checks:['Candidature UI','Offre reçue après sommeil','Acceptation UI','Jour du contrat','Débit transport','Connexion UI','Fondu UI','Intensité quatre phases','60 secondes non accélérées','Bilan automatique','Virement client','Rechargement sans double paiement']},null,2));console.log('BILAN',bilan);console.log('BANQUE',paid.bank);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
