const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1116,height:717}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Live interface QA');await p.locator('#create-vj-button').click();await p.evaluate(()=>{StudioWorld.showComputer();openApp('skills')});const skills=[];
for(const [width,height] of [[1116,717],[1280,720],[390,844]]){await p.setViewportSize({width,height});await p.evaluate(()=>openApp('skills'));for(const level of [0,5]){await p.evaluate(level=>{for(const s of skillCatalog){profile.skills[s.id]=level;profile.settings.progression.skillXp[s.id]=level===5?1200:0;}renderSkills();addWindowControls();},level);const visible=await p.locator('.skill-career-card').evaluateAll(cards=>cards.every(card=>{const r=card.getBoundingClientRect();return [...card.querySelectorAll('button')].every(button=>{const b=button.getBoundingClientRect();return b.top>=r.top&&b.bottom<=r.bottom&&b.left>=r.left&&b.right<=r.right})}));assert(visible,'Skill buttons must fit cards');await p.locator('[data-course]').last().scrollIntoViewIfNeeded();const hit=await p.locator('[data-course]').last().evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el});assert(hit,'Last course button must be reachable without clipping/overlap');skills.push({width,height,level,buttonsFit:true});await p.locator('#app-window').evaluate(el=>el.scrollTop=0);await p.screenshot({path:`documentation/live-upgrade-20260915/skills-${width}-${level}.png`});}}
await p.setViewportSize({width:1280,height:720});await p.evaluate(()=>{document.querySelector('#app-window').hidden=true;profile.showSessions=1;document.body.className='screen-gig';currentGig=profile.gigs[0];const root=document.createElement('section');root.id='qa-mixer';root.className='live-show-desk';document.body.append(root);window.qaShow=new VJLiveShow(root,videoClips);qaShow.start(0);});await p.waitForFunction(()=>qaShow.program.readyState>=2&&qaShow.preview.readyState>=2);
const mechanics=await p.evaluate(()=>{qaShow.elapsed=.4;qaShow.queueTake();const at=qaShow.queuedAt;if(at!==2)throw Error('Wrong next measure');qaShow.setPaused(true);qaShow.tick(1);if(qaShow.elapsed!==.4)throw Error('Paused timer moved');const saved=qaShow.snapshot();qaShow.setPaused(false);qaShow.queueTake();if(qaShow.queuedAt!==null)throw Error('Cancel failed');qaShow.queueTake();qaShow.tick(1.5);if(qaShow.transition)throw Error('Transition too early');qaShow.tick(.11);if(!qaShow.transition?.synced)throw Error('No synced transition');qaShow.tick(2.1);if(qaShow.syncedTransitions!==1||qaShow.transitions!==1)throw Error('Count failed');qaShow.elapsed=14;qaShow.updateCue();return{at,saved,next:qaShow.root.querySelector('[data-live-next]').textContent,synced:qaShow.syncedTransitions};});assert(mechanics.next.includes('Dans 1 s'));
await p.locator('[data-live-view]').click();await p.locator('#qa-mixer').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'documentation/live-upgrade-20260915/live-desktop.png'});
await p.evaluate(saved=>{qaShow.dispose();const root=document.querySelector('#qa-mixer');window.qaShow=new VJLiveShow(root,videoClips);qaShow.start(0);qaShow.restore(saved);},mechanics.saved);await p.waitForFunction(()=>qaShow.program.readyState>=2&&qaShow.preview.readyState>=2);assert.equal(await p.evaluate(()=>qaShow.queuedAt),2);assert.equal(await p.evaluate(()=>qaShow.paused),true);await p.evaluate(()=>{qaShow.setPaused(false);qaShow.tick(1.7);qaShow.tick(2.1)});assert.equal(await p.evaluate(()=>qaShow.syncedTransitions),1);
await p.setViewportSize({width:390,height:844});await p.locator('#qa-mixer').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'documentation/live-upgrade-20260915/live-mobile.png'});for(const selector of ['[data-live-sync]','[data-live-intensity]','[data-live-pause]']){await p.locator(selector).scrollIntoViewIfNeeded();assert(await p.locator(selector).evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el}),selector+' should be reachable');}
assert.deepEqual(errors,[]);fs.writeFileSync('documentation/live-upgrade-20260915/tests.json',JSON.stringify({skills,mechanics,errors},null,2));console.log('Skills fit/reachable at 3 screen sizes, synchronized transition/cancel/pause/restore, mobile controls passed');await p.evaluate(()=>qaShow.dispose());}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
