const {chromium}=require(process.env.VJ_PLAYWRIGHT),fs=require('node:fs');const folder='documentation/audit-2026-09-14';
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173/?audit=20260914');await p.screenshot({path:folder+'/01-home.png'});await p.locator('#studio-entry-button').click();await p.waitForFunction(()=>humanLoaded==='nova');await p.screenshot({path:folder+'/02-creator.png'});await p.locator('#vj-name').fill('Audit isolé');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>document.body.classList.contains('studio-world-view'));await p.screenshot({path:folder+'/03-studio.png'});
const data=await p.evaluate(()=>({catalog:shopItems,skills:skillCatalog,gigs:profile.gigs,cast:HUMAN_CAST,settings:profile.settings,stats:profile.stats,apps:[...new Set([...document.querySelectorAll('.desktop-icon[data-app]')].map(e=>e.dataset.app))],clips:videoClips,gearProgressions:GEAR_PROGRESSIONS,clients:CLIENT_TYPES,events:GIG_EVENTS,saveBytes:localStorage.getItem(SAVE_KEY).length}));fs.writeFileSync(folder+'/runtime-catalog.json',JSON.stringify(data,null,2));
const perf=await p.evaluate(()=>new Promise(resolve=>{const frames=[];let last=performance.now(),start=last;function frame(t){frames.push(t-last);last=t;if(t-start<10000)requestAnimationFrame(frame);else{frames.sort((a,b)=>a-b);resolve({seconds:(t-start)/1000,frames:frames.length,averageFps:frames.length*1000/(t-start),p95ms:frames[Math.floor(frames.length*.95)],over50ms:frames.filter(x=>x>50).length,renderer:renderer.info.render,memory:renderer.info.memory,pixelRatio:renderer.getPixelRatio(),hardware:navigator.hardwareConcurrency});}}requestAnimationFrame(frame);}));
await p.keyboard.down('w');await p.waitForTimeout(650);await p.keyboard.up('w');await p.keyboard.press('e');await p.screenshot({path:folder+'/04-desktop.png'});
const screens=[];for(const app of data.apps){await p.evaluate(app=>{closeAppWindow(false);clearInactiveWindows();openApp(app);},app);await p.waitForTimeout(130);screens.push(await p.evaluate(app=>({app,title:appWindow.querySelector('h1,h2')?.innerText,text:appWindow.innerText.slice(0,18000),buttons:[...appWindow.querySelectorAll('button')].map(e=>({text:e.innerText,disabled:e.disabled})),scrollHeight:appWindow.scrollHeight,clientHeight:appWindow.clientHeight}),app));await p.screenshot({path:folder+'/app-'+app+'.png'});}
await p.evaluate(()=>{closeAppWindow(false);clearInactiveWindows();openApp('social');});await p.locator('[data-simple-id]').first().click();await p.screenshot({path:folder+'/05-setup.png'});
const setup=await p.evaluate(()=>({text:gigSetupModal.innerText,loadout:readGigLoadoutFromSetup()}));
// Isolate whether statistical packs affect score while all measured performance stays fixed.
const scoreProbe=await p.evaluate(()=>{const gig=pendingGigSetup,loadout=readGigLoadoutFromSetup();const run={mappingScore:90,connectedRatio:1,live:{score:90,completion:1,transitions:2,seconds:60},elapsed:90000};profile.styleXp[gig.style]=0;profile.ownedItems=profile.ownedItems.filter(id=>!shopItems.some(i=>i.id===id&&i.category==='vjloop'));const a=calculateCareerScore(90,gig,loadout,run);const pack=shopItems.find(i=>i.category==='vjloop'&&i.styleTarget===gig.style);if(pack)profile.ownedItems.push(pack.id);const b=calculateCareerScore(90,gig,loadout,run);return {pack:pack?.id,before:{score:a.score,artistic:a.artistic},after:{score:b.score,artistic:b.artistic},liveSources:videoClips.length};});
fs.writeFileSync(folder+'/runtime-audit.json',JSON.stringify({performance:perf,screens,setup,scoreProbe,errors},null,2));console.log(JSON.stringify({catalog:data.catalog.length,gigs:data.gigs.length,skills:data.skills.length,apps:data.apps,performance:perf,scoreProbe,errors}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
