const { chromium } = require(process.env.VJ_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173');await page.waitForTimeout(1500);
 await page.screenshot({path:require('node:path').join(__dirname,'qa-home.png')});
 await page.locator('[data-slot="0"]').click(); await page.locator('#slot-confirm-yes').click();
 await page.locator('#vj-name').fill('QA Production');await page.locator('#create-vj-button').click();
 // Fixture in an isolated browser profile; never reads or changes the user's save.
 await page.evaluate(()=>{const gig=profile.gigs[0];gig.status='accepted';gig.eventDay=profile.day;profile.money=5000;startGig(gig.id);});
 await page.locator('[data-loadout-type="prep"]').selectOption('choice:gear');
 assert.match(await page.locator('#production-prep-effect').innerText(),/Fatigue/);
 await page.screenshot({path:require('node:path').join(__dirname,'qa-brief.png')});
 const before=await page.evaluate(()=>({money:profile.money,fatigue:profile.stats.fatigue,cost:readGigLoadoutFromSetup().totalCost}));
 await page.locator('#gig-setup-start-button').click();
 const after=await page.evaluate(()=>({money:profile.money,fatigue:profile.stats.fatigue,prep:activeGigLoadout.selected.prep.slug}));
 assert.equal(after.money,before.money-before.cost);assert.equal(after.fatigue,Math.min(100,before.fatigue+3));assert.equal(after.prep,'gear');
 const caps=await page.evaluate(()=>[0,.5,1].map(connectedRatio=>calculateCareerScore(100,currentGig,activeGigLoadout,{connectedRatio}).score));
 assert.equal(caps[0],0);assert.ok(caps[1]<=50);assert.ok(caps[2]>caps[1]);
 await page.screenshot({path:require('node:path').join(__dirname,'qa-stage.png')});
 await page.locator('#finish-gig-button').click();
 assert.match(await page.locator('#result-content').innerText(),/Résultat net/);
 const result=await page.evaluate(()=>({score:currentGig.lastScore,payout:currentGig.lastPayout}));
 assert.equal(result.score,0);assert.equal(result.payout,0);
 await page.locator('#result-close-button').click();
 await page.reload();await page.waitForTimeout(500);
 assert.equal(await page.evaluate(()=>slots[0].name),'VJ QA Production');
 await page.evaluate(()=>{const gig=profile.gigs[0];gig.status='accepted';gig.eventDay=profile.day;startGig(gig.id);});
 await page.locator('#gig-setup-start-button').click();
 await page.locator('#connect-projector-button').click();
 assert.equal(await page.locator('#connected-count').innerText(),'1 / 1');
 await page.locator('#finish-gig-button').click();
 assert.equal(await page.evaluate(()=>currentGig.lastPayout),0);
 await page.locator('#result-close-button').click();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>showScreen('slots'));await page.screenshot({path:require('node:path').join(__dirname,'qa-mobile.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,caps,before,after,result,pageErrors:errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
