const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('QA sept étapes');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);
const initialClients=await p.evaluate(()=>{saveSlots();return profile.gigs.map(g=>({id:g.id,type:g.clientType,budget:g.budget,clothes:getGigClothingRequirement(g).count}));});assert(initialClients.every(g=>g.type));assert(initialClients.slice(0,5).every(g=>g.clothes===0));await p.reload();await p.locator('#studio-entry-button').click();assert.deepEqual(await p.evaluate(()=>profile.gigs.map(g=>({id:g.id,type:g.clientType,budget:g.budget,clothes:getGigClothingRequirement(g).count}))),initialClients);await p.waitForFunction(()=>player.userData.loaded);
const cast=[];for(const id of ['nova','eli','sam']){await p.evaluate(id=>{profile.appearance.character=id;applyHumanAppearance();profile.studioWorld.x=0;profile.studioWorld.z=10;profile.studioWorld.yaw=0;profile.settings.thirdPerson=true;},id);await p.waitForFunction(id=>humanLoaded===id,id);await p.keyboard.down('w');await p.waitForTimeout(350);await p.screenshot({path:`documentation/seven-steps-20260915/character-${id}-walk.png`});await p.keyboard.up('w');const result=await p.evaluate(()=>{player.updateWorldMatrix(true,true);const ys=[];player.traverse(o=>{if(o.isBone&&/Head|Foot/.test(o.name))ys.push(o.getWorldPosition(new THREE.Vector3()).y)});return {height:Math.max(...ys)-Math.min(...ys),visible:player.visible,finite:player.children.every(o=>Number.isFinite(o.position.y))}});console.log(id,result);assert(result.visible);assert(result.height>1.2&&result.height<2.1);assert(result.finite);cast.push({id,...result});}
const features=await p.evaluate(()=>({profiles:['learning','bar','club','festival','corporate'].map(id=>{const gigs={learning:{number:1},bar:{number:2,style:'chill'},club:{number:8,style:'techno'},festival:{number:20,clientType:'festival'},corporate:{number:15,clientType:'corpo'}};return ShowProfiles.get(gigs[id]);}),resolutions:GEAR_PROGRESSIONS.computer.map(GearCapabilities.resolution),brightness:GEAR_PROGRESSIONS.projector.map(GearCapabilities.brightness)}));assert.equal(new Set(features.profiles.map(p=>JSON.stringify(p.ranges))).size,5);assert.deepEqual(features.resolutions,[640,960,1280,1600,1920]);
// Client memory and bonus are idempotent and survive save normalization.
const relation=await p.evaluate(()=>{const gig=profile.gigs[0];gig.status='done';gig.timesCompleted=1;const money=profile.money;const live={completion:1};const result={score:100,penalties:[]};ClientRelations.complete(gig,result,live);const emails=profile.emails.length;ClientRelations.complete(gig,result,live);const first=ClientRelations.offerBonus(gig),budget=gig.budget;ClientRelations.offerBonus(gig);saveSlots();return{emailsStable:emails===profile.emails.length,budgetStable:budget===gig.budget,first,budget,moneyStable:profile.money===money,state:ClientRelations.get(gig),id:gig.id};});assert(relation.emailsStable&&relation.budgetStable&&relation.moneyStable);assert(relation.first>0);await p.reload();await p.waitForFunction(()=>profile?.created);assert.equal(await p.evaluate(id=>profile.gigs.find(g=>g.id===id).budget,relation.id),relation.budget);assert.equal(await p.evaluate(id=>ClientRelations.get(profile.gigs.find(g=>g.id===id)).shows,relation.id),1);
const failed=await p.evaluate(id=>{const g=profile.gigs.find(g=>g.id===id);g.timesCompleted=2;ClientRelations.complete(g,{score:10,penalties:['Signal absent']},{completion:0});ClientRelations.offerBonus(g);return {bonus:g.loyaltyBonus,trust:ClientRelations.get(g).trust}},relation.id);assert.equal(failed.bonus,0);assert.equal(failed.trust,1);
// Render the synth and audience response to an actual audio buffer.
const pcm=await p.evaluate(async()=>{const ctx=new OfflineAudioContext(1,44100,44100),sound=new LiveSoundtrack(ctx);sound.master.gain.value=.7;sound.tone(135,.2,.09,'sine',true);sound.tone(196,.25,.035,'triangle');sound.crowd();const rendered=await ctx.startRendering();return Array.from(rendered.getChannelData(0));});assert(pcm.some(v=>Math.abs(v)>.005));assert(Math.max(...pcm.map(Math.abs))<1);const wav=Buffer.alloc(44+pcm.length*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(pcm.length*2,40);pcm.forEach((v,i)=>wav.writeInt16LE(Math.round(v*32767),44+i*2));fs.writeFileSync('documentation/seven-steps-20260915/live-sound-preview.wav',wav);
assert.deepEqual(errors,[]);fs.writeFileSync('documentation/seven-steps-20260915/features.json',JSON.stringify({clientInitializationStable:true,cast,features,relation,failed,audioSamples:pcm.length,errors},null,2));console.log('3 animated characters, 5 show directions, 5 render resolutions, 6 projection levels, persistent/idempotent client memory, audio buffer passed');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
