const {chromium}=require('../qa-browser.cjs'),a=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:5187/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Physical cable pointer QA');await p.locator('#create-vj-button').click();await p.waitForTimeout(300);
const ids=await p.evaluate(()=>{const s=PhysicalV4.state,C=PhysicalCore,find=id=>s.objects.find(o=>o.modelId===id),pc=find('computer-starter-laptop'),pj=find('projector-cheap'),wire=find('cable-vga-3'),bag=find('bag-messenger-basic');C.move(s,pc.uid,{x:-.6,y:.98,z:7.2},'desk');pj.rotation=Math.PI;C.move(s,pj.uid,{x:.65,y:.98,z:7.2},'desk');C.move(s,wire.uid,{x:0,y:.98,z:7.8},'desk');C.move(s,bag.uid,{x:1.5,y:.18,z:8.4},'desk');Object.assign(profile.studioWorld,{x:0,z:10,yaw:0,pitch:-.14});return{pc:pc.uid,pj:pj.uid,wire:wire.uid,bag:bag.uid};});await p.waitForTimeout(100);
async function point(id,port){return await p.evaluate(({id,port})=>{const root=PhysicalCables.wires.get(id)||PhysicalV4.models.get(id),v=port?root.getObjectByName('socket-'+port).getWorldPosition(new THREE.Vector3()):new THREE.Box3().setFromObject(root.children[0]).getCenter(new THREE.Vector3());v.project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},{id,port});}
async function aimPort(id,port){await p.evaluate(({id,port})=>{const socket=PhysicalV4.models.get(id).getObjectByName('socket-'+port),v=socket.getWorldPosition(new THREE.Vector3()),normal=new THREE.Vector3(0,0,1).applyQuaternion(socket.getWorldQuaternion(new THREE.Quaternion()));normal.y=0;if(normal.lengthSq()<.1)normal.set(0,0,1);normal.normalize();const x=v.x+normal.x*3,z=v.z+normal.z*3;Object.assign(profile.studioWorld,{x,z,yaw:Math.atan2(x-v.x,z-v.z),pitch:Math.atan2(v.y-1.65,3)});},{id,port});await p.waitForTimeout(140);const q=await p.evaluate(({id,port})=>{const v=PhysicalV4.models.get(id).getObjectByName('socket-'+port).getWorldPosition(new THREE.Vector3()).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},{id,port});a(q.x>0&&q.x<1050&&q.y>120&&q.y<800,JSON.stringify({id,port,q}));await p.mouse.click(q.x,q.y);await p.waitForTimeout(90);}

async function click(id,port){if(port)return aimPort(id,port);let q=await point(id,port);if(!port)q=await p.evaluate(({id,q})=>{const ray=new THREE.Raycaster();for(let radius=0;radius<90;radius+=4)for(let angle=0;angle<7;angle+=.4){const x=q.x+Math.cos(angle)*radius,y=q.y+Math.sin(angle)*radius;ray.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,1-y/innerHeight*2),camera);const h=ray.intersectObject(PhysicalV4.group,true).find(h=>{let n=h.object;while(n){if(!n.visible||n.userData.uid===PhysicalV4.held)return false;n=n.parent;}return true;});let n=h?.object;while(n){if(n.userData.uid){if(n.userData.uid===id)return{x,y};break;}n=n.parent;}}return q;},{id,q});a(q.x>0&&q.x<1440&&q.y>50&&q.y<890,JSON.stringify(q));await p.mouse.click(q.x,q.y);await p.waitForTimeout(90);}
await click(ids.wire);a.equal(await p.evaluate(()=>PhysicalV4.selected),ids.wire);await p.keyboard.press('e');await p.waitForTimeout(100);a.equal(await p.evaluate(()=>PhysicalV4.held),ids.wire);
await click(ids.pc,'hdmi');a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).looseEnd||null,ids.wire),null,'VGA plug must reject HDMI at first endpoint');
await click(ids.pc,'vga');a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).looseEnd?.port,ids.wire),'vga');
a.equal(await p.evaluate(id=>PhysicalCables.wires.get(id)?.userData.loose,ids.wire),true);
await p.screenshot({path:'documentation/physical-v4/cable-first-end.png'});
await click(ids.pj,'vga');a.equal(await p.evaluate(()=>PhysicalV4.held),null);a.equal(await p.evaluate(()=>PhysicalV4.state.links.length),1);
const geometry=await p.evaluate(id=>{const g=PhysicalCables.wires.get(id);return{tube:g.getObjectByName('cable-jacket').geometry.type,plugs:g.children.filter(n=>n.name.startsWith('plug-')).length,loose:g.userData.loose};},ids.wire);a.deepEqual(geometry,{tube:'TubeGeometry',plugs:2,loose:false});
await p.screenshot({path:'documentation/physical-v4/cable-connected.png'});
await p.evaluate(()=>saveSlots());await p.reload();await p.waitForTimeout(500);await p.evaluate(()=>{showScreen('desktop');StudioWorld.enter();});await p.waitForTimeout(400);console.log('Reload',await p.evaluate(()=>({body:document.body.className,created:profile.created,models:PhysicalV4.models.size,wires:PhysicalCables.wires.size})),errors);a.equal(await p.evaluate(()=>PhysicalV4.state.links.length),1);a.equal(await p.evaluate(id=>PhysicalCables.wires.get(id)?.userData.loose,ids.wire),false);
await p.evaluate(()=>Object.assign(profile.studioWorld,{x:0,z:10,yaw:0,pitch:-.14}));await p.waitForTimeout(80);
await click(ids.pj);await p.keyboard.press('p');a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).powerOn,ids.pj),true);
const tape=await p.evaluate(()=>{const o=PhysicalCore.add(PhysicalV4.state,'accessory-gaff-pocket','desk',{x:-.1,y:.98,z:7.9});o.owner='rental';return o.uid;});await p.waitForTimeout(120);await click(tape);await p.keyboard.press('e');a.equal(await p.evaluate(()=>PhysicalV4.held),tape);const tapePoint=await p.evaluate(id=>{const v=PhysicalCables.wires.get(id).getObjectByName('cable-jacket').geometry.parameters.path.getPoint(.5).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},ids.wire);await p.mouse.click(tapePoint.x,tapePoint.y);await p.waitForTimeout(120);a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).secured,ids.wire),true);a(await p.evaluate(id=>PhysicalCables.wires.get(id).children.some(n=>n.name==='gaffer-band'),ids.wire));await p.screenshot({path:'documentation/physical-v4/cable-gaffer.png'});await p.keyboard.press('Escape');
await click(ids.wire);await p.waitForTimeout(100);a.equal(await p.evaluate(()=>PhysicalV4.selected),ids.wire);await p.keyboard.press('e');a.equal(await p.evaluate(()=>PhysicalV4.state.links.length),0);await p.keyboard.press('Escape');await p.waitForTimeout(100);
await p.evaluate(()=>Object.assign(profile.studioWorld,{x:0,z:11,yaw:0,pitch:-.5}));await p.waitForTimeout(120);await click(ids.wire);await p.keyboard.press('e');await p.waitForTimeout(80);await click(ids.bag);a.equal(await p.evaluate(()=>PhysicalV4.held),ids.wire,'Opening bag keeps held item');a(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).open,ids.bag));await click(ids.bag);a.equal(await p.evaluate(()=>PhysicalV4.held),null);a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).location,ids.wire),'bag');
await click(ids.bag);await p.locator('[data-unpack="'+ids.wire+'"]').click();a.equal(await p.evaluate(()=>PhysicalV4.held),ids.wire);
await p.keyboard.press('Escape');a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).container,ids.wire),ids.bag);a.deepEqual(errors,[]);fs.writeFileSync('documentation/physical-v4/cable-pointer-results.json',JSON.stringify({passed:true,geometry,errors,checks:['VGA rejects HDMI','two real socket clicks','loose end visible','two solid plugs and tube','reload restores wire','power key','disconnect','closed bag opens before packing','open bag packs','unpack']},null,2));console.log('PASS physical wire and bag through real pointer/keyboard actions');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
