const {chromium}=require('../qa-browser.cjs'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:5187/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Campaign regression');await p.locator('#create-vj-button').click();await p.waitForTimeout(200);
for(let n=1;n<=24;n++){
 const fixture=await p.evaluate(require('./fixture.cjs'),n);
 await p.waitForTimeout(180);
 if(n===1){const before=await p.evaluate(()=>({links:structuredClone(PhysicalV4.state.links),ids:PhysicalV4.state.active.ids,money:profile.money,elapsed:PhysicalV4.state.active.elapsed}));before.elapsed=await p.evaluate(()=>{returnToDesktopFromGig();return PhysicalV4.state.active.elapsed;});await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>PhysicalV4.group.visible),false);assert.equal(await p.evaluate(()=>PhysicalV4.state.active.elapsed),before.elapsed);await p.reload();await p.waitForTimeout(550);await p.evaluate(()=>{showScreen('desktop');resumeActiveRun();});await p.waitForTimeout(180);assert.deepEqual(await p.evaluate(()=>PhysicalV4.state.links),before.links);assert.deepEqual(await p.evaluate(()=>PhysicalV4.state.active.ids),before.ids);assert.equal(await p.evaluate(()=>profile.money),before.money);assert(await p.evaluate(()=>PhysicalV4.state.active.elapsed)<before.elapsed+2);console.log('PASS pause, reload, resume: unchanged instances, wiring, cash; paused clock');}
 if([5,10,22].includes(n)){await p.waitForFunction(()=>[...PhysicalOutputs.media.values()].length>0&&[...PhysicalOutputs.media.values()].every(m=>m.video.readyState>=2),{},{timeout:15000});const media=await p.evaluate(()=>({textures:rigs.map(r=>r.screenProjection.material.map.uuid),sources:[...PhysicalOutputs.media.values()].map(m=>m.src)}));assert.equal(new Set(media.textures).size,n===5?1:n===10?2:3);assert.equal(new Set(media.sources).size,n===5?1:n===10?2:3);console.log('PASS decoded video outputs',n,media.sources.length);}
 const negatives=await p.evaluate(n=>{const s=PhysicalV4.state,checks=[],pj=PhysicalCore.get(s,rigs[0].physicalId),verify=(label,change,restore)=>{change();const result=PhysicalV4.finish({preview:true});restore();if(result.passed)throw Error('Incorrect success: '+label);checks.push({label,...result});};if(n===1){const input=pj.input;verify('Wrong input',()=>pj.input='AUX',()=>pj.input=input);verify('No projector power',()=>pj.powerOn=false,()=>pj.powerOn=true);const screen=s.objects.find(o=>o.placed);verify('Screen not installed',()=>screen.placed=false,()=>screen.placed=true);}if(n===7){const audio=s.objects.find(o=>o.modelId==='audio-console'),old=audio.audioTestChannel;verify('Micro not tested',()=>audio.audioTestChannel=null,()=>audio.audioTestChannel=old);}if(n===17){const q=rigs[0].maskQuality;verify('Empty manual mapping',()=>rigs[0].maskQuality=0,()=>rigs[0].maskQuality=q);}if(n===22){const wire=s.links.find(l=>l.a.port==='usb2'),old=[...s.links];verify('Mouse missing',()=>PhysicalCore.disconnect(s,wire.cable),()=>s.links=old);const wear=profile.equippedWear;verify('Corporate dress code',()=>profile.equippedWear={},()=>profile.equippedWear=wear);}if(n===24){const clips=s.selectedClips;verify('No clips selected',()=>s.selectedClips=[],()=>s.selectedClips=clips);}return checks;},n);
 if([1,7,13,17,22,24].includes(n))await p.screenshot({path:`documentation/physical-v4/gig-${n}.png`});const scores=await p.evaluate(()=>({score:aggregateScore,signals:rigs.map(r=>({id:r.physicalId,on:r.cable.connected,mask:r.maskQuality})),money:profile.money}));await p.locator('#finish-gig-button').click();const result=await p.evaluate(()=>PhysicalV4.state.results.at(-1));console.log(n,JSON.stringify(result),JSON.stringify(scores.score));assert.equal(result.passed,true,'gig '+n+' '+JSON.stringify(result));results.push({...result,...fixture,negatives});await p.locator('#result-close-button').click();if(n===1){await p.evaluate(()=>reapplyToGig('physical-gig-01'));assert.equal(await p.evaluate(()=>profile.gigs[0].status),'accepted');}}
 assert.deepEqual(errors,[]);fs.writeFileSync('documentation/physical-v4/campaign-results.json',JSON.stringify({results,errors},null,2));console.log('PASS 24 cumulative fixtures through departure, power/ports, actual scene projection, scoring and payment');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
