from pathlib import Path
def edit(file,a,b):
 p=Path(file);s=p.read_text(encoding='utf-8-sig');assert a in s,(file,a[:90]);p.write_text(s.replace(a,b,1),encoding='utf-8')
edit('src/physical-v4.js',"<h3>Contenu avant gig · ${g.clipMinimum}","${g.number===23?'<label>Lieu du contrat <select data-venue-choice><option value=\"festival\">Festival secondaire</option><option value=\"street\">Extérieur / scène temporaire</option></select></label>':''}<h3>Contenu avant gig · ${g.clipMinimum}")
edit('src/physical-v4.js',"state.selectedClips=[...gigSetupContent", "if(g.number===23){g.venueFamily=gigSetupContent.querySelector('[data-venue-choice]').value;g.venue=g.venueFamily==='street'?'Extérieur / scène temporaire':'Festival secondaire';}state.selectedClips=[...gigSetupContent")
edit('src/physical-v4.js',"d.kind==='surface'?1.8:d.kind==='projector'", "d.kind==='surface'?1.8:d.kind==='stand'?1.5:d.kind==='projector'")
edit('src/physical-v4.js',"if(target&&C.spec(target.modelId).kind==='tower'", "if(target&&C.spec(target.modelId).kind==='stand'&&d.kind==='projector'){const support=target.uid;put({...target.position,y:target.position.y+1.42},state.active?'venue':'desk');o.mountedTo=support;persist();return;}\n   if(target&&C.spec(target.modelId).kind==='tower'")
edit('src/physical-v4.js',"if(k==='r'){o.rotation+=Math.PI/12;persist();}","if(k==='r'){o.rotation+=Math.PI/12;const r=rigs.find(r=>r.physicalId===o.uid);if(r)r.calibration.yaw+=Math.PI/12;persist();}")
edit('src/physical-v4.js',"r.cable.connected=C.signal(state,o.uid).valid;", "o.rotation=Math.PI+r.calibration.yaw;r.cable.connected=C.signal(state,o.uid).valid;")
edit('src/physical-v4.js',"height=!g.height||all.some(o=>C.spec(o.modelId).kind==='stand')", "height=!g.height||projs.length===g.projectorCount&&projs.every(o=>all.some(s=>C.spec(s.modelId).kind==='stand'&&Math.hypot(s.position.x-o.position.x,s.position.z-o.position.z)<.6&&o.position.y-s.position.y>1.2))")
edit('src/physical-v4.js',"function togglePower(){", "function testMicrophone(){const o=selectedObject(),sig=o&&C.signal(state,o.uid);if(!sig?.valid){notify('Test micro impossible : '+(sig?.reason||'sélectionne la console'));return;}o.audioTestChannel=sig.channel;o.testUntil=performance.now()+2000;notify('Test micro reçu : le vumètre répond.');persist();}\n function togglePower(){")
edit('src/physical-v4.js',"<button data-disconnect>Débrancher</button>","${d.kind==='audio-console'?'<button data-mic-test>Tester le micro</button><meter data-mic-meter min=\"0\" max=\"100\" value=\"0\" aria-label=\"Niveau du micro\"></meter>':''}<button data-disconnect>Débrancher</button>")
edit('src/physical-v4.js',"panel.querySelector('[data-take]').onclick", "panel.querySelector('[data-mic-test]')?.addEventListener('click',testMicrophone);panel.querySelector('[data-take]').onclick")
edit('src/physical-v4.js',"cableGeometry();objectPanel();saveAt+=dt;", "cableGeometry();objectPanel();const meter=panel.querySelector('[data-mic-meter]'),audio=selectedObject();if(meter)meter.value=audio?.testUntil>performance.now()&&C.signal(state,audio.uid).valid?60+Math.sin(performance.now()/70)*25:0;saveAt+=dt;")
edit('src/physical-v4.js',"C.spec(o.modelId).kind==='audio-console'&&C.signal(state,o.uid).valid),surface=", "C.spec(o.modelId).kind==='audio-console'&&C.signal(state,o.uid).valid&&o.audioTestChannel===C.signal(state,o.uid).channel),surface=")
edit('src/gig-difficulty.js',"const base=currentGig.zoneShape||'rectangle'", "const base=currentGig.physical&&currentGig.number===21&&rig.index===1?'rectangle':currentGig.zoneShape||'rectangle'")
# Compact, honest PDF reference in the long-term project directions.
p=Path('documentation/DIRECTION-JEU.md');s=p.read_text(encoding='utf-8');s='## Mise à jour prioritaire — 16 septembre 2026\n\nCindy a choisi la copie vjSIMUFINALE 2 et demandé d’appliquer le [Game Design Master v4](references/VJ_Simulator_Game_Design_Master_Refonte_Physique_v4.pdf). Cette nouvelle instruction suspend la refonte esthétique globale et le gameplay Resolute décrits ci-dessous. Conserver le décor et la navigation pendant la refonte physique. Suivi : [physical-v4](physical-v4/IMPLEMENTATION.md).\n\n'+s;p.write_text(s,encoding='utf-8')
