from pathlib import Path
p=Path('src/physical-v4.js')
s=p.read_text(encoding='utf-8')
start=s.index("const ports=new THREE.Group();ports.name='physical-ports';",s.index('function rebuild'))
end=s.index("group.add(root);models.set",start)
s=s[:start]+"PhysicalCables.ports(root,o,new THREE.Box3().setFromObject(m));"+s[end:]
start=s.index(' function cableGeometry(){')
end=s.index('\n function objectives()',start)
s=s[:start]+" function cableGeometry(){PhysicalCables.sync(group,models,state,held,firstPort,camera);}"+s[end:]
start=s.index("const ports=m.getObjectByName('physical-ports');const cable=held")
end=s.index('\n  if(state.prepared',start)
s=s[:start]+"PhysicalCables.updatePorts(m,o,held&&C.spec(C.get(state,held)?.modelId),firstPort&&C.endpoint(state,firstPort),selected,state);}\n"+s[end:]
s=s.replace("selected=firstPort=null;held=state.objects.find(o=>o.location==='hand')?.uid||null;","selected=null;held=state.objects.find(o=>o.location==='hand')?.uid||null;firstPort=C.get(state,held)?.looseEnd||null;")
s=s.replace("held=state.objects.find(o=>o.location==='hand')?.uid||null;}","held=state.objects.find(o=>o.location==='hand')?.uid||null;firstPort=C.get(state,held)?.looseEnd||null;}")
s=s.replace("firstPort=endpoint;notify(", "const end=C.endpoint(state,endpoint);if(['shelf','bag','vehicle'].includes(end.object.location)){notify('Pose cet appareil sur une surface avant de le brancher.');return;}if(!d.ends.includes(end.port.standard)){notify('Cette fiche ne correspond pas à cette prise.');return;}if(state.links.some(l=>[l.a,l.b].some(e=>e.device===endpoint.device&&e.port===endpoint.port))){notify('Cette prise est déjà occupée.');return;}firstPort=endpoint;o.looseEnd={...endpoint};saveSlots();notify(")
s=s.replace("if(C.spec(o.modelId).kind==='cable')C.disconnect(state,id);","if(C.spec(o.modelId).kind==='cable'){C.disconnect(state,id);delete o.looseEnd;}")
s=s.replace("o.position=o.homePosition||o.position;held=null;", "o.position=o.homePosition||o.position;delete o.looseEnd;held=null;")
s=s.replace("const from=aa", "const from=aa")
# Selected cable is rendered separately from its hidden stored coil.
s=s.replace("if(!o||o.modelId==='venue-outlet')return;", "if(!o||o.modelId==='venue-outlet')return;")
s=s.replace("const passed=score>=70,paid=ratio===0?0:Math.round(", "const passed=score>=70,paid=ratio===0?0:Math.floor(")
s=s.replace("Micro sans signal", "Micro non testé ou sans signal")
s=s.replace("Math.floor(index/16)%4", "Math.floor(index/16)%4")
p.write_text(s,encoding='utf-8')
p=Path('src/physical-core.js');s=p.read_text(encoding='utf-8')
s=s.replace("['bag','vehicle','installed'].includes(aa.object.location)||['bag','vehicle','installed'].includes(bb.object.location)","['shelf','bag','vehicle','installed'].includes(aa.object.location)||['shelf','bag','vehicle','installed'].includes(bb.object.location)")
s=s.replace("Sors les appareils de leur contenant.","Pose les appareils sur une surface avant de les brancher.")
s=s.replace("delete c.container;return{ok:true};","delete c.container;delete c.looseEnd;return{ok:true};")
s=s.replace("function disconnect(s,cableId){s.links=", "function disconnect(s,cableId){const c=get(s,cableId);if(c)delete c.looseEnd;s.links=")
p.write_text(s,encoding='utf-8')
p=Path('src/main.js');s=p.read_text(encoding='utf-8')
s=s.replace("function reapplyToGig(gigId) {","function reapplyToGig(gigId) {\n  if(window.PhysicalV4?.handles(gigId))return PhysicalV4.book(gigId);")
s=s.replace("const lockedByLevel = !profile.godMode && !owned && (profile.stats.level || 1) < unlockLevel;", "const physicalLock = window.PhysicalV4?.enabled ? PhysicalCareer.unlockItem(item) : '';\n  const lockedByLevel = Boolean(physicalLock) || (!profile.godMode && !owned && (profile.stats.level || 1) < unlockLevel);")
s=s.replace("const lockedByLevel = !owned && (profile.stats.level || 1) < unlockLevel;", "const physicalLock = window.PhysicalV4?.enabled ? PhysicalCareer.unlockItem(item) : '';\n  const lockedByLevel = Boolean(physicalLock) || (!profile.godMode && !owned && (profile.stats.level || 1) < unlockLevel);")
s=s.replace("lockedByLevel ? `Niveau ${unlockLevel} requis`","lockedByLevel ? (physicalLock || `Niveau ${unlockLevel} requis`)")
s=s.replace("lockedByLevel ? `Niveau ${unlockLevel}`","lockedByLevel ? (physicalLock || `Niveau ${unlockLevel}`)")
s=s.replace("const ownedLabel = lockedByLevel\n    ? `Niveau ${unlockLevel} requis`","const ownedLabel = lockedByLevel\n    ? (physicalLock || `Niveau ${unlockLevel} requis`)")
s=s.replace("GearCapabilities.brightness(GearCapabilities.selected('projector'))", "(currentGig?.physical && rig.physicalId ? Math.min(1, PhysicalCore.spec(PhysicalCore.get(PhysicalV4.state, rig.physicalId)?.modelId).lumens / 5000) : GearCapabilities.brightness(GearCapabilities.selected('projector')))")
p.write_text(s,encoding='utf-8')
