from pathlib import Path
def edit(file,a,b):
 p=Path(file);s=p.read_text(encoding='utf-8-sig');assert a in s,(file,a[:90]);p.write_text(s.replace(a,b,1),encoding='utf-8')
edit('src/physical-v4.js',"document.body.classList.contains('studio-world-view')&&!StudioWorld.visitingHome", "document.body.classList.contains('studio-world-view')&&!StudioWorld.visitingHome&&!state?.active")
edit('src/physical-v4.js',"selected=held=firstPort=null;signature='';syncOwned();", "selected=firstPort=null;held=state.objects.find(o=>o.location==='hand')?.uid||null;signature='';syncOwned();")
edit('src/physical-v4.js',"dirty=true;selected=held=null;}\n function resume", "dirty=true;selected=null;held=state.objects.find(o=>o.location==='hand')?.uid||null;}\n function resume")
edit('src/physical-v4.js',"function finish(){if(!state.active", "function finish({preview=false}={}){if(!state.active")
edit('src/physical-v4.js',"const passed=score>=70,paid=", "if(g.dress==='safety'&&!wear.safety)score=Math.min(score,59);if(preview)return{score,passed:score>=70,reasons};const passed=score>=70,paid=")
edit('src/physical-v4.js',"o.rotation=Math.PI+r.calibration.yaw;", "o.rotation=Math.PI+r.calibration.yaw;o.pitch=-r.calibration.pitch;")
edit('src/physical-v4.js',"m.rotation.y=o.rotation||0;m.visible", "m.rotation.y=o.rotation||0;m.rotation.x=o.pitch||0;m.visible")
edit('src/physical-v4.js',"r.screenPlane.visible=Boolean(surfaces[i]);", "r.screenPlane.visible=Boolean(surfaces[i]);r.screenPlane.material.color.setHex(r.cable.connected?0xf4f0df:0x090b10);")
edit('src/physical-v4.js',"if(state.active){if(!document.hidden)", "if(state.prepared&&profile.preparedDeparture){const g=profile.gigs.find(g=>g.id===state.prepared);profile.preparedDeparture.packed=!preparation(g).missing.length;}\n  if(state.active){if(!document.hidden)")
# Colour each actual port by compatibility with the cable being carried.
edit('src/physical-v4.js',"m.getObjectByName('physical-ports').visible=Boolean", "const ports=m.getObjectByName('physical-ports');const cable=held&&C.spec(C.get(state,held)?.modelId);for(const p of ports.children.filter(p=>p.geometry?.type==='SphereGeometry')){const end=p.userData.endpoint,port=o.ports.find(q=>q.id===end.port),first=firstPort&&C.endpoint(state,firstPort);let color=0x78d9d1;if(cable?.kind==='cable'){const compatible=cable.ends.includes(port.standard)&&(!first||first.port.direction!==port.direction);color=compatible?0x54ed9d:['VGA','HDMI','SDI','DP'].includes(port.standard)&&!first?0xe6b755:0xef6464;}p.material.color.setHex(color);}ports.visible=Boolean")
edit('src/physical-v4.js',"profile.stats.xp+=passed?40:5;", "profile.stats.xp+=passed?40:5;profile.stats.level=Math.max(profile.stats.level,1+Math.floor(state.completed.length/3));state.scores={TEC:Math.round((aggregateScore.coverage+aggregateScore.trapeze)/2),SIG:Math.round(ratio*100),MAP:g.maskRequired?map:state.scores?.MAP||0,AUD:g.micro?(audio?50:0):state.scores?.AUD||0,PRO:Math.round((Number(dress)+Number(height)+Number(!late))/3*100),STYLE:Math.min(100,wear.style*5+clips.score*2),NET:Math.min(100,state.completed.length*4+wear.network)};")
edit('src/main.js','function getGigTimerText() {','function getGigTimerText() {\n  if(currentGig?.physical&&profile.physical?.active){const s=profile.physical.active.elapsed;return formatGigTime((currentGig.timeLimitSeconds?Math.max(0,currentGig.timeLimitSeconds-s):s)*1000);}')
