from pathlib import Path
def edit(file,a,b):
 p=Path(file);s=p.read_text(encoding='utf-8-sig');assert a in s,(file,a[:80]);p.write_text(s.replace(a,b,1),encoding='utf-8')
edit('src/main.js','  merged.gigs = mergeStarterGigData(merged.gigs);','  if(!merged.physical)merged.gigs = mergeStarterGigData(merged.gigs);')
edit('src/main.js','  return 120 + Math.floor(days / 20) * 10;','  return 40 + Math.min(20, Math.floor(days / 10) * 5);')
edit('src/main.js','(Number(item?.cost) || 0) * 0.7','(Number(item?.cost) || 0) * 0.5')
edit('src/main.js','function getGearSellCheck(item) {','function getGearSellCheck(item) {\n  if(window.PhysicalV4?.enabled&&item?.category===\'gear\'&&!PhysicalV4.canSell(item.id))return {canSell:false,reason:\'Range et débranche un exemplaire avant la vente.\'};')
edit('src/main.js','  recordFinance(value, `Revente ${item.label}`);','  window.PhysicalV4?.syncOwned();\n  recordFinance(value, `Revente ${item.label}`);')
edit('src/physical-v4.js',"function syncOwned(){if(!state)return;let count=", "function canSell(id){return state?.objects.some(o=>o.modelId===id&&o.owner==='player'&&['shelf','desk'].includes(o.location)&&!state.links.some(l=>l.cable===o.uid||l.a.device===o.uid||l.b.device===o.uid));}\n function syncOwned(){if(!state)return;for(const modelId of new Set(state.objects.filter(o=>o.owner==='player').map(o=>o.modelId))){const wanted=profile.ownedItems.includes(modelId)?Math.max(1,Number(profile.inventory[modelId])||0):0;let excess=state.objects.filter(o=>o.modelId===modelId&&o.owner==='player').length-wanted;while(excess-->0){const o=state.objects.find(o=>o.modelId===modelId&&o.owner==='player'&&['shelf','desk'].includes(o.location)&&!state.links.some(l=>l.cable===o.uid||l.a.device===o.uid||l.b.device===o.uid));if(o)state.objects=state.objects.filter(x=>x!==o);else break;}}let count=")
edit('src/physical-v4.js','ensure,syncOwned,handles,buyGuard','ensure,syncOwned,canSell,handles,buyGuard')
edit('src/physical-v4.js',"state.active.calibrations=rigs.map(r=>({...r.calibration}));objectives();", "state.active.calibrations=rigs.map(r=>({...r.calibration}));state.active.mappings=rigs.map(r=>({zones:structuredClone(r.maskZones||[r.maskPoints]),zone:r.mappingZone||0}));objectives();")
edit('src/physical-v4.js',"const outlet=state.objects.find(o=>o.modelId==='venue-outlet');outlet.position", "if(state.active.mappings)rigs.forEach((r,i)=>{const m=state.active.mappings[i];if(m&&getGigMaskRequirement(g)){PolygonMapping.init(r);r.maskZones=m.zones;r.mappingZone=m.zone;r.maskPoints=r.maskZones[m.zone]||[];r.mappingSignature=null;updateMaskContour(r);}});const outlet=state.objects.find(o=>o.modelId==='venue-outlet');outlet.position")
edit('src/physical-v4.js',"state.objects=state.objects.filter(o=>o.owner!=='rental');state.active=null;", "state.objects=state.objects.filter(o=>o.owner!=='rental');state.links=state.links.filter(l=>C.get(state,l.cable)&&C.get(state,l.a.device)&&C.get(state,l.b.device));state.active=null;")
edit('src/physical-core.js',"return{valid:true,channel:id+':'+portId,standard:p.standard};", "return{valid:true,channel:id+':'+portId,standard:p.standard,standards:[p.standard]};")
edit('src/physical-core.js',"return{...r,standard:p.standard};", "return{...r,standard:p.standard,standards:[...new Set([...(r.standards||[]),p.standard])]};")
edit('src/physical-v4.js',"if(!surface)reasons.push('Écran(s) non installé(s)');if(!audio)reasons.push('Micro sans signal');", "if(!surface){score=Math.min(score,69);reasons.push('Écran(s) non installé(s)');}if(!audio){score=Math.min(score,69);reasons.push('Micro sans signal');}if(g.maskRequired&&map<70){score=Math.min(score,69);reasons.push('Mapping sous 70 %');}if(g.standard==='SDI'&&signals.some(s=>!s.standards?.includes('SDI'))){score=Math.min(score,69);reasons.push('La chaîne demandée doit utiliser SDI');}if(g.number>=22&&!all.some(o=>C.spec(o.modelId).kind==='tower'&&C.workstation(state,o.uid).ok)){score=Math.min(score,69);reasons.push('Une tour complète est requise');}")
edit('src/physical-v4.js',"new Set(signals.map(s=>s.channel)).size<g.projectorCount", "new Set(signals.map(s=>s.channel)).size<g.projectorCount")
# Diagnostics replace software playback only on the small screen texture of new equipment.
edit('src/gear-models.js',"d.fillStyle='#475767';d.fillRect(18,404,732,8);const t=", "if(window.PhysicalV4?.enabled){d.fillStyle='#18212b';d.fillRect(0,0,768,432);d.fillStyle='#dabc80';d.font='bold 26px Arial';d.fillText('POSTE VIDEO / DIAGNOSTIC',32,52);d.fillStyle='#b7d3d7';d.font='21px Arial';['1. Alimenter les appareils','2. Relier les ports OUT → IN','3. Choisir le bon input','4. Tester et cadrer'].forEach((s,i)=>d.fillText(s,32,120+i*64));}d.fillStyle='#475767';d.fillRect(18,404,732,8);const t=")
