module.exports=n=>{const C=PhysicalCore,s=PhysicalV4.state,g=profile.gigs.find(g=>g.number===n);if(PhysicalCareer.blocked(g))throw Error(PhysicalCareer.blocked(g));resultModal.hidden=true;showScreen('desktop');StudioWorld.enter();s.objects=s.objects.filter(o=>o.modelId==='venue-outlet');s.links=[];s.selectedClips=shopItems.filter(i=>i.category==='vjloop'&&i.styleTarget===g.style).slice(0,6).map(i=>i.id);profile.ownedItems.push(...s.selectedClips.filter(id=>!profile.ownedItems.includes(id)));profile.equippedWear={top:n>=23?'clothing-jacket-reflective':'clothing-coat-tour'};PhysicalV4.prepare(g.id);gigSetupContent.querySelectorAll('[data-physical-clip]').forEach(e=>e.checked=s.selectedClips.includes(e.dataset.physicalClip));PhysicalV4.queue();
 const wires=[],nodes=[];const add=(id,pos={x:0,y:.9,z:6.5})=>{const o=C.add(s,id,'desk',pos);o.owner='rental';o.rentalFee=0;nodes.push({id:o.uid,pos});return o;};const wire=(a,ap,b,bp,id)=>{const c=add(id);wires.push([c.uid,{device:a.uid,port:ap},{device:b.uid,port:bp}]);};const wall=s.objects[0];wall.position={x:0,y:.2,z:6.3};let powerIndex=0;
 const power=o=>{if(powerIndex>=12){const bar=add('power-bar',{x:0,y:.25,z:6.1});wire(wall,'out12',bar,'power','cable-extension');powerIndex=0;wall.extra=bar.uid;}const src=wall.extra?C.get(s,wall.extra):wall;wire(src,'out'+(++powerIndex),o,'power','cable-extension');};
 const pc=add(n===24?'computer-desktop-rtx4080':n>=22?'computer-desktop-rtx4060':n>=10?'computer-creator-laptop-rtx':n>=4?'computer-vj-laptop-gtx':'computer-starter-laptop');power(pc);let gpu,card;if(n===24)card=add('gpu-sdi-pcie');
 if(n>=22){gpu=add('gpu-gpu-desktop-pro');const mon=add('screen-monitor-24',{x:.7,y:.9,z:6.6});power(mon);wire(pc,'gpu-hdmi',mon,'hdmi','cable-hdmi-5');const k=add('keyboard-basic'),m=add('mouse-basic');wire(pc,'usb1',k,'usb','cable-usb');wire(pc,'usb2',m,'usb','cable-usb');}
 const mirror=[5,6,9,23].includes(n);let splitter;if(mirror){splitter=add(n===23?'router-sdi-distribution':'router-splitter-duo');power(splitter);if(n===23){const bridge=add('converter-hdmi-sdi');power(bridge);const dp=add('adapter-dp-hdmi-basic');wire(pc,'gpu-dp1',dp,'in','cable-dp');wire(dp,'out',bridge,'in','cable-hdmi-5');wire(bridge,'out',splitter,'in','cable-sdi-10');}else wire(pc,'hdmi',splitter,'in','cable-hdmi-5');}
 const projectors=[];
 for(let i=0;i<g.projectorCount;i++){const x=(i-(g.projectorCount-1)/2)*5.4;const pos={x,y:g.height?1.62:.9,z:TARGET_Z};const pj=add(n>=22?'projector-pro-6500':n>=4?'projector-standard':'projector-cheap',pos);pj.input=n<=3?'VGA':n>=22?'SDI':'HDMI';power(pj);projectors.push(pj.uid);const screen=add('surface-square',{x,y:0,z:-7});screen.placed=true;if(g.height)add('support-stand',{x,y:.2,z:TARGET_Z});let source=splitter||pc,out=splitter?'out'+(i+1):n===24?'sdi'+(i+1):n>=22?'gpu-dp'+(i+1):n<=3?'vga':i===0?'hdmi':'usbc-video';
 if(n===24){wire(pc,out,pj,'sdi','cable-sdi-30');continue;}if(!splitter&&(i>0||n>=22)){const adapter=add(n>=22?'adapter-dp-hdmi-basic':'adapter-usb-c-hdmi',{x:.3+i*.3,y:.9,z:6.5});wire(pc,out,adapter,'in',n>=22?'cable-dp':'cable-usbc-video');source=adapter;out='out';}
 if(n>=13&&n!==23){const to=add('converter-hdmi-sdi',{x:source.position.x+.25,y:.7,z:source.position.z});power(to);wire(source,out,to,'in','cable-75ft-active');if(n>=22)wire(to,'out',pj,'sdi','cable-sdi-30');else{const from=add('converter-sdi-hdmi',{x:x+.5,y:.7,z:TARGET_Z});power(from);wire(to,'out',from,'in','cable-sdi-30');wire(from,'out',pj,'hdmi','cable-hdmi-5');}}
 else wire(source,out,pj,n<=3?'vga':n===23?'sdi':'hdmi',n<=3?'cable-vga-3':n===23?'cable-sdi-30':'cable-75ft-active');}
 let audio;if(g.micro){const mic=add('audio-mic'),console=add('audio-console');audio=console.uid;console.input='XLR';power(console);wire(mic,'xlr',console,'mic','cable-xlr-10');}
 const original=[...nodes];let bag;for(const {id}of original){const o=C.get(s,id),d=C.spec(o.modelId);if(['projector','tower','surface','stand','monitor'].includes(d.kind)){o.location='vehicle';continue;}if(!bag||!C.pack(s,id,bag.uid).ok){bag=add('accessory-roadcase-pro',{x:4,y:.2,z:11.8});bag.open=true;bag.location='vehicle';const packed=C.pack(s,id,bag.uid);if(!packed.ok)throw Error(packed.reason);}}
 PhysicalV4.depart();if(!s.active)throw Error('No active run '+n);for(const {id,pos}of nodes){const o=C.get(s,id);if(C.spec(o.modelId).kind==='container')continue;C.move(s,id,pos,'venue');o.powerOn=true;if(C.spec(o.modelId).kind==='projector')o.input=n<=3?'VGA':n>=22?'SDI':'HDMI';if(C.spec(o.modelId).kind==='audio-console')o.input='XLR';}if(card){pc.powerOn=false;const r=C.install(s,card.uid,pc.uid);if(!r.ok)throw Error(r.reason);pc.powerOn=true;}if(gpu){pc.powerOn=false;const r=C.install(s,gpu.uid,pc.uid);if(!r.ok)throw Error(r.reason);pc.powerOn=true;}for(const [id,a,b]of wires){const r=C.connect(s,id,a,b);if(!r.ok)throw Error(n+' '+C.get(s,id).modelId+' '+JSON.stringify([a,b])+' '+r.reason);}if(audio){const o=C.get(s,audio);o.audioTestChannel=C.signal(s,audio).channel;}
 rigs.forEach(r=>{r.calibration.yaw=r.calibration.pitch=0;r.calibration.projectorX=r.screen.x;r.calibration.projectorZ=TARGET_Z;if(g.maskRequired){PolygonMapping.init(r);r.maskZones=r.mappingTargets.map(points=>points.map(p=>({...p})));r.maskPoints=r.maskZones[0];r.mappingSignature=null;}});return{projectors,wires:wires.length,objects:s.active.ids.length};};
