from pathlib import Path
p=Path('.')
def edit(file,a,b):
 s=(p/file).read_text(encoding='utf-8-sig'); assert a in s,(file,a[:90]); (p/file).write_text(s.replace(a,b,1),encoding='utf-8')
edit('src/item-models.js',"window.ItemModels={create(item){","window.ItemModels={create(item){\n const physical=window.PhysicalModels?.create(item);if(physical)return physical;")
edit('index.html','</body>','<script defer src="./src/physical-core.js?v=4"></script>\n<script defer src="./src/physical-career.js?v=4"></script>\n<script defer src="./src/physical-models.js?v=4"></script>\n<script defer src="./src/physical-v4.js?v=4"></script>\n</body>')
edit('src/file-explorer.js',"if(folder==='documents')return profile.emails", "if(folder==='documents')return [{id:'physical-guide',label:'Game Design Master — Refonte physique v4.pdf',type:'PDF · 17 pages · guide officiel',kind:'guide'},...profile.emails")
edit('src/file-explorer.js',"kind:'email'}));", "kind:'email'}))];")
edit('src/file-explorer.js',"if(entry.kind==='folder')", "if(entry.kind==='guide'){openApp('physical-guide');return;}if(entry.kind==='folder')")
edit('src/main.js','function renderDesktop() {','function renderDesktop() {\n  window.PhysicalV4?.ensure();')
edit('src/main.js',"if (currentApp === 'guide') renderGuide();","if (currentApp === 'guide') window.PhysicalCareer ? PhysicalCareer.guide() : renderGuide();\n  if (currentApp === 'physical-guide') window.PhysicalCareer?.guide();")
edit('src/main.js','function startGig(gigId) {','function startGig(gigId) {\n  if(window.PhysicalV4?.handles(gigId))return PhysicalV4.prepare(gigId);')
edit('src/main.js','function beginGigFromSetup() {','function beginGigFromSetup() {\n  if(pendingGigSetup?.physical)return window.PhysicalV4?.queue();')
edit('src/main.js','function startLivePerformance({restoring=false}={}) {','function startLivePerformance({restoring=false}={}) {\n  if(currentGig?.physical)return window.PhysicalV4?.finish();')
edit('src/main.js','function finishGig() {','function finishGig() {\n  if(currentGig?.physical)return window.PhysicalV4?.finish();')
edit('src/main.js','function updateCable(rig) {','function updateCable(rig) {\n  if(currentGig?.physical){rig.cable.mesh.visible=false;return;}')
edit('src/main.js','  renderer.render(scene, camera);','  window.PhysicalV4?.tick(liveDelta);\n  renderer.render(scene, camera);')
edit('src/main.js','function getMissingSkills(gig) {','function getMissingSkills(gig) {\n  if(gig?.physical)return [];')
edit('src/main.js','function getGigWorldRequirements(gig) {','function getGigWorldRequirements(gig) {\n  if(gig?.physical)return PhysicalCareer.blocked(gig)?[PhysicalCareer.blocked(gig)]:[];')
edit('src/main.js','function getItemUnlockLevel(item) {','function getItemUnlockLevel(item) {\n  if(window.PhysicalCareer && (item.physical || item.category===\'vjloop\' || item.category===\'clothing\'))return 1;')
edit('src/main.js','function getGigMinimumScore(gig) {','function getGigMinimumScore(gig) {\n  if(gig?.physical)return 70;')
edit('src/main.js','function buyItem(itemId) {','function buyItem(itemId) {\n  if(window.PhysicalV4?.buyGuard(itemId))return;')
edit('src/main.js','  item.apply(profile);','  item.apply(profile);\n  window.PhysicalV4?.syncOwned();')
edit('src/main.js','function unlockGigs() {','function unlockGigs() {\n  if(window.PhysicalV4?.enabled){PhysicalCareer.migrate();return;}')
edit('src/main.js','function renderGigQuickRequirements(gig) {','function renderGigQuickRequirements(gig) {\n  if(gig?.physical)return `<p>${escapeHtml(gig.requirement)} · ${gig.clipMinimum} clip(s) · ${gig.micro?\'micro XLR · \':\'\'}${gig.dress===\'safety\'?\'gilet sécurité\':gig.dress===\'pro\'?\'tenue Pro ≥ 3\':\'tenue libre\'}</p>`;')
edit('src/main.js','function applyToGig(gigId) {','function applyToGig(gigId) {\n  if(window.PhysicalV4?.handles(gigId))return PhysicalV4.book(gigId);')
edit('src/simple-booking.js','function getSimpleGigBlockers(gig) {','function getSimpleGigBlockers(gig) {\n  if(gig?.physical)return PhysicalCareer.blocked(gig)?[PhysicalCareer.blocked(gig)]:[];')
edit('src/simple-booking.js',"const goal = g => getGigMaskRequirement(g) > 0", "const goal = g => g.physical ? g.requirement : getGigMaskRequirement(g) > 0")
edit('src/simple-booking.js',"appWindow.querySelector('[data-simple-practice]').onclick = () => {", "appWindow.querySelector('[data-simple-practice]').onclick = () => {\n    if(window.PhysicalV4?.enabled){StudioWorld.enter();notify('Pratique libre : manipule les objets et leurs ports sur le bureau.');return;}")
edit('src/catalog-browser.js',"return items.filter(i=>(!q", "return items.filter(i=>!i.physicalDisabled&&(!q")
edit('src/studio-storage.js','   const model=ItemModels.create(item)', '   if(window.PhysicalV4?.enabled)return;\n   const model=ItemModels.create(item)')
edit('src/studio-journey.js','rebuildEquippedGear();}}',"if(window.PhysicalV4?.enabled)equipment.visible=false;else rebuildEquippedGear();}}")
edit('src/studio-journey.js',"if(z==='mixer'){\n   const launch", "if(z==='mixer'){\n   if(window.PhysicalV4?.enabled){StudioWorld.showComputer();openApp('files');return;}\n   const launch")
edit('src/studio-journey.js',"if(z==='projector'){\n   const launch", "if(z==='projector'){\n   if(window.PhysicalV4?.enabled){notify('Clique sur un objet, E pour le prendre. Branche ses ports avec un câble.');return;}\n   const launch")
edit('src/studio-journey.js','function hint(s){const zone=nearby(s),p=profile.preparedDeparture;', 'function hint(s){if(window.PhysicalV4?.enabled&&profile.physical?.prepared)return PhysicalV4.departureHint(s);const zone=nearby(s),p=profile.preparedDeparture;')
edit('src/studio-journey.js','  const zone=nearby(s),p=profile.preparedDeparture;', '  if(window.PhysicalV4?.enabled&&profile.physical?.prepared){PhysicalV4.depart();return;}\n  const zone=nearby(s),p=profile.preparedDeparture;')
edit('src/venue-design.js',"const family=families[num-1]||'hall';", "const family=gig.venueFamily||families[num-1]||'hall';")
edit('src/gig-difficulty.js','function tier(g){return', 'function tier(g){if(g?.physical)return Math.min(7,Math.floor((g.number-1)/3));return')
edit('src/gig-difficulty.js','function spec(g){const t=tier(g);','function spec(g){if(g?.physical)return{index:tier(g),name:g.type,score:70,mask:70};const t=tier(g);')
edit('src/gig-difficulty.js','function label(g){const s=spec(g);','function label(g){if(g?.physical)return `Palier ${tier(g)+1}/8 · ${g.type} · objectif 70 %`;const s=spec(g);')
edit('src/gig-difficulty.js','function configure(g){','function configure(g){if(g?.physical)return g;')
edit('src/gig-difficulty.js',"function roadmap(){return", "function roadmap(){if(window.PhysicalV4?.enabled)return '<details class=\"simple-other\"><summary>Parcours physique · 8 paliers / 24 gigs</summary><p>VGA → HDMI → micro XLR → sorties indépendantes → SDI → mapping → multi-mapping → régie complète. Chaque contrat reprend la chaîne déjà apprise. Réussite à 70/100.</p></details>';return")
edit('src/gig-difficulty.js',"n=/rond/.test(shape)?20:/hexa/.test(shape)?6:4;", "n=/rond/.test(shape)?20:/hexa/.test(shape)?6:/triangle/.test(shape)?3:/etoile/.test(shape)?10:4;")
edit('src/gig-difficulty.js','Math.cos(i/n*Math.PI*2)*Math.min(w,h)/2','Math.cos(i/n*Math.PI*2)*Math.min(w,h)/2*(shape===\'etoile\'&&i%2?.45:1)')
edit('src/gig-difficulty.js','Math.sin(i/n*Math.PI*2)*Math.min(w,h)/2','Math.sin(i/n*Math.PI*2)*Math.min(w,h)/2*(shape===\'etoile\'&&i%2?.45:1)')
edit('src/gig-difficulty.js','function required(){return currentGig&&','function required(){if(currentGig?.physical)return currentGig.height;return currentGig&&')
