const {chromium}=require('../qa-browser.cjs'),a=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.stack));try{await p.goto('http://127.0.0.1:5187/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Branchement débutant');await p.locator('#create-vj-button').click();await p.waitForTimeout(450);
const kit=await p.evaluate(()=>{const by=id=>PhysicalV4.state.objects.filter(o=>o.modelId===id).map(o=>o.uid);return{pc:by('computer-starter-laptop')[0],pj:by('projector-cheap')[0],wall:by('venue-outlet')[0],bars:by('power-bar'),ext:by('cable-extension'),iec:by('cable-iec'),vga:by('cable-vga-3')[0],audio:by('cable-audio-3')[0],speakers:by('audio-speakers-basic')[0]};});
a(await p.evaluate(()=>!PhysicalV4.state.objects.some(o=>o.location==='desk'&&Math.abs(o.position.x)<2.225&&o.position.z>6.625&&o.position.z<8.275)));
await p.screenshot({path:'documentation/physical-v4/empty-workshop.png'});
await p.evaluate(kit=>{const C=PhysicalCore,s=PhysicalV4.state,put=(id,x,y,z,r=0)=>{C.move(s,id,{x,y,z},'desk');C.get(s,id).rotation=r;};put(kit.pc,-.65,.928,7.25);put(kit.pj,.65,.928,7.3,Math.PI);put(kit.speakers,-1.7,.928,7.85);put(kit.bars[0],-1.1,.928,8);put(kit.bars[1],1.1,.928,8);const screen=s.objects.find(o=>o.modelId==='surface-square');put(screen.uid,.65,.168,5.4);},kit);await p.waitForTimeout(180);
async function port(id,port){await p.evaluate(({id,port})=>{const socket=PhysicalV4.models.get(id).getObjectByName('socket-'+port),v=socket.getWorldPosition(new THREE.Vector3()),normal=new THREE.Vector3(0,0,1).applyQuaternion(socket.getWorldQuaternion(new THREE.Quaternion()));normal.y=0;if(normal.lengthSq()<.1)normal.set(0,0,1);normal.normalize();const x=v.x+normal.x*3,z=v.z+normal.z*3;Object.assign(profile.studioWorld,{x,z,yaw:Math.atan2(x-v.x,z-v.z),pitch:Math.atan2(v.y-1.65,3)});},{id,port});await p.waitForTimeout(140);const q=await p.evaluate(({id,port})=>{const v=PhysicalV4.models.get(id).getObjectByName('socket-'+port).getWorldPosition(new THREE.Vector3()).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},{id,port});a(q.x>0&&q.x<1050&&q.y>120&&q.y<800,JSON.stringify({id,port,q}));await p.mouse.click(q.x,q.y);await p.waitForTimeout(90);}
async function wire(id,aa,ap,bb,bp){await p.evaluate(id=>PhysicalV4.take(id),id);await p.waitForTimeout(80);await port(aa,ap);a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).looseEnd?.device,id),aa,ap+' first end');await port(bb,bp);a.equal(await p.evaluate(()=>PhysicalV4.held),null,bp+' second end');checks.push(ap+' → '+bp);}
await wire(kit.ext[0],kit.wall,'out1',kit.bars[0],'power');await wire(kit.ext[1],kit.wall,'out2',kit.bars[1],'power');await wire(kit.iec[0],kit.bars[0],'out1',kit.pc,'power');await wire(kit.iec[1],kit.bars[1],'out1',kit.pj,'power');await wire(kit.vga,kit.pc,'vga',kit.pj,'vga');await wire(kit.audio,kit.pc,'audio',kit.speakers,'audio');
for(const id of [kit.pc,kit.pj]){await p.evaluate(id=>{const o=PhysicalCore.get(PhysicalV4.state,id);Object.assign(profile.studioWorld,{x:o.position.x,z:10,yaw:0,pitch:-.17});},id);await p.waitForTimeout(120);const q=await p.evaluate(id=>{const v=new THREE.Box3().setFromObject(PhysicalV4.models.get(id).children[0]).getCenter(new THREE.Vector3()).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},id);await p.mouse.click(q.x,q.y);await p.waitForTimeout(80);a.equal(await p.evaluate(()=>PhysicalV4.selected),id);await p.locator('[data-power]').click();a(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).powerOn,id));}
await p.evaluate(id=>{const o=PhysicalCore.get(PhysicalV4.state,id);Object.assign(profile.studioWorld,{x:o.position.x,z:9.5,yaw:0,pitch:-.25});},kit.pc);await p.waitForTimeout(150);const pcPoint=await p.evaluate(id=>{const v=new THREE.Box3().setFromObject(PhysicalV4.models.get(id).children[0]).getCenter(new THREE.Vector3()).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},kit.pc);await p.mouse.click(pcPoint.x,pcPoint.y);await p.waitForTimeout(80);a(await p.locator('[data-use-computer]').isEnabled());await p.locator('[data-use-computer]').click();await p.waitForTimeout(100);a(!await p.evaluate(()=>document.body.classList.contains('studio-world-view')));await p.locator('#leave-studio-computer').click();await p.waitForTimeout(150);await p.keyboard.press('e');await p.waitForTimeout(100);a(!await p.evaluate(()=>document.body.classList.contains('studio-world-view')));await p.locator('#leave-studio-computer').click();await p.waitForTimeout(150);checks.push('powered laptop opens computer desktop through button and E');
a(await p.evaluate(id=>PhysicalCore.signal(PhysicalV4.state,id).valid,kit.pj));a(await p.evaluate(id=>PhysicalCore.signal(PhysicalV4.state,id).valid,kit.speakers));a.equal(await p.evaluate(()=>PhysicalV4.state.links.length),6);await p.evaluate(()=>Object.assign(profile.studioWorld,{x:2.4,z:10.2,yaw:.58,pitch:-.2}));await p.waitForTimeout(180);await p.screenshot({path:'documentation/physical-v4/starter-pointer-connected.png'});a.deepEqual(errors,[]);fs.writeFileSync('documentation/physical-v4/starter-pointer-results.json',JSON.stringify({checks,powerButtons:true,signal:true,errors},null,2));console.log('PASS six real cable connections, power buttons and VGA/audio signal');
}catch(e){await p.screenshot({path:'documentation/physical-v4/starter-pointer-failure.png'});console.log('BROWSER ERRORS',errors);throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
