const {chromium}=require('../qa-browser.cjs'),a=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:5187/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Window audit');await p.locator('#create-vj-button').click();await p.waitForTimeout(500);
const models=await p.evaluate(()=>shopItems.filter(i=>i.category==='gear'&&!i.physicalDisabled).map(i=>{const model=ItemModels.create(i),box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());return{id:i.id,finite:[...box.min.toArray(),...box.max.toArray()].every(Number.isFinite),size:size.toArray()};}));a(models.every(m=>m.finite&&Math.max(...m.size)>0),JSON.stringify(models.filter(m=>!m.finite)));
const apps=['calendar','guide','phone','email','social','transport','music','settings','stats','job','rest','inventory','finance','housing','skills','shop','files'];
for(const viewport of [{width:1440,height:900},{width:1116,height:717},{width:960,height:600}]){await p.setViewportSize(viewport);for(const app of apps){await p.evaluate(app=>{closeAppWindow(false);clearInactiveWindows();profile.settings.windowLayouts={};profile.settings.windowBounds={width:innerWidth-70,height:innerHeight-155};profile.settings.windowPosition={left:35,top:75};openApp(app);},app);await p.waitForTimeout(70);const check=await p.evaluate(()=>{const r=appWindow.getBoundingClientRect();return{width:appWindow.clientWidth,scrollWidth:appWindow.scrollWidth,inViewport:r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,title:appWindow.querySelector('h1,h2')?.textContent,clipped:[...appWindow.querySelectorAll('article,.skill-card,.app-heading')].filter(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return r.width>0&&r.height>0&&s.overflowY==='hidden'&&e.scrollHeight>e.clientHeight+3}).map(e=>({text:e.textContent.trim().slice(0,100),height:e.clientHeight,content:e.scrollHeight}))};});checks.push({app,viewport,...check});if(viewport.width===1116&&['skills','shop','guide','files'].includes(app))await p.screenshot({path:'documentation/physical-v4/window-'+app+'.png'});}}
await p.evaluate(()=>openApp('guide'));for(let page=1;page<=17;page++){await p.locator('[data-guide-page]').selectOption(String(page));await p.locator('#app-window img').evaluate(img=>img.decode());a.equal(await p.locator('#app-window img').evaluate(img=>img.naturalWidth>0),true);}
const clips=await p.evaluate(()=>shopItems.filter(i=>i.category==='vjloop').map(i=>({id:i.id,cost:i.cost})));a(clips.every(i=>i.cost>=20&&i.cost<=35));
fs.writeFileSync('documentation/physical-v4/ui-audit-results.json',JSON.stringify({checks,models,clips:clips.length,guidePages:17,errors},null,2));console.log('UI',checks.filter(c=>!c.inViewport||c.scrollWidth>c.width+2||c.clipped.length));a.deepEqual(errors,[]);a(checks.every(c=>c.inViewport&&c.scrollWidth<=c.width+2&&!c.clipped.length),'Window clipping found');console.log('PASS',checks.length,'windows,',models.length,'models, 17 guide pages,',clips.length,'clip prices');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
