const {chromium}=require('../qa-browser.cjs'),a=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:5187/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Atelier physique');await p.locator('#create-vj-button').click();await p.waitForTimeout(550);
const ids=await p.evaluate(()=>{const s=PhysicalV4.state,C=PhysicalCore,of=id=>s.objects.filter(o=>o.modelId===id);return{pc:of('computer-starter-laptop')[0].uid,pj:of('projector-cheap')[0].uid,wire:of('cable-vga-3')[0].uid,bag:of('bag-messenger-basic')[0].uid,speakers:of('audio-speakers-basic')[0].uid,audio:of('cable-audio-3')[0].uid,screen:of('surface-square')[0].uid,bars:of('power-bar').map(o=>o.uid),iec:of('cable-iec').map(o=>o.uid),extensions:of('cable-extension').map(o=>o.uid),wall:of('venue-outlet')[0].uid,videoPorts:of('computer-starter-laptop')[0].ports.filter(p=>['VGA','HDMI','DP','SDI','USB-C'].includes(p.standard)).map(p=>p.standard),projectorPorts:of('projector-cheap')[0].ports.map(p=>p.standard)};});a.deepEqual(ids.videoPorts,['VGA','HDMI']);a(!ids.projectorPorts.includes('HDMI'));a.equal(ids.bars.length,2);a.equal(ids.iec.length,2);a.equal(ids.extensions.length,2);checks.push('starter laptop VGA + HDMI; VGA projector; stereo pair; two complete power bundles');
async function view(x,z,yaw=0,pitch=-.15){await p.evaluate(v=>Object.assign(profile.studioWorld,v),{x,z,yaw,pitch});await p.waitForTimeout(100);}
async function take(id){await p.evaluate(id=>PhysicalV4.take(id),id);await p.waitForTimeout(120);a.equal(await p.evaluate(()=>PhysicalV4.held),id);}
async function clickObject(id){const q=await p.evaluate(id=>{const root=PhysicalV4.models.get(id),v=new THREE.Box3().setFromObject(root.children[0]).getCenter(new THREE.Vector3()).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},id);await p.mouse.click(q.x,q.y);await p.waitForTimeout(120);}
await view(0,11);await take(ids.pc);a(await p.locator('[data-drop]').isDisabled());await p.keyboard.press('e');a.equal(await p.evaluate(()=>PhysicalV4.held),ids.pc);checks.push('airborne placement rejected');
for(let i=0;i<4;i++){await p.mouse.move(200,450);await p.mouse.down();await p.mouse.move(760,450,{steps:10});await p.mouse.up();}a(Math.abs(await p.evaluate(()=>profile.studioWorld.yaw))>Math.PI*2);await p.mouse.move(450,500);await p.mouse.down();await p.mouse.move(450,120,{steps:10});await p.mouse.up();a(await p.evaluate(()=>profile.studioWorld.pitch)>1.3);a.equal(await p.evaluate(()=>PhysicalV4.held),ids.pc);checks.push('360-degree look and looking up while carrying');
await view(0,11);await p.locator('[data-contact]').click();await p.waitForTimeout(80);a(await p.locator('[data-drop]').isEnabled());await p.screenshot({path:'documentation/physical-v4/placement-floor.png'});await p.locator('[data-drop]').click();a.equal(await p.evaluate(()=>PhysicalV4.held),null);a(Math.abs(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).position.y,ids.pc)-.168)<.01);checks.push('button places on actual floor height');
await take(ids.pc);await view(-.75,9.2);await p.locator('[data-contact]').click();await p.waitForTimeout(100);a(await p.locator('[data-drop]').isEnabled());await p.screenshot({path:'documentation/physical-v4/placement-desk.png'});await p.keyboard.press('e');a.equal(await p.evaluate(()=>PhysicalV4.held),null);a(Math.abs(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).position.y,ids.pc)-.928)<.015);checks.push('E places on desktop rather than inside it');
await take(ids.wire);await view(4.35,6.82);await p.locator('[data-contact]').click();await p.waitForTimeout(100);a(await p.locator('[data-drop]').isEnabled());const shelfY=await p.evaluate(()=>PhysicalPlacement.last.point.y);a(shelfY>.98&&shelfY<1.0);await p.mouse.move(400,400);await p.mouse.wheel(0,-120);await p.waitForTimeout(100);a(await p.locator('[data-drop]').isDisabled());await p.mouse.wheel(0,120);await p.waitForTimeout(100);a(await p.locator('[data-drop]').isEnabled());await p.keyboard.press('e');checks.push('shelf contact and wheel height adjustment');
await view(0,10.5,0,-.55);await p.evaluate(ids=>{const C=PhysicalCore,s=PhysicalV4.state;C.move(s,ids.bag,{x:.7,y:.168,z:9.1},'desk');},ids);await take(ids.wire);await clickObject(ids.bag);a(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).open,ids.bag));await clickObject(ids.bag);a.equal(await p.evaluate(()=>PhysicalV4.held),null);a.equal(await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).container,ids.wire),ids.bag);await p.screenshot({path:'documentation/physical-v4/bag-open.png'});await p.locator('[data-unpack="'+ids.wire+'"]').click();a.equal(await p.evaluate(()=>PhysicalV4.held),ids.wire);await p.keyboard.press('Escape');checks.push('click closed bag to open, click to pack, unpack same instance');
await p.evaluate(ids=>{const C=PhysicalCore,s=PhysicalV4.state;for(const o of s.objects)if(![ids.pc,ids.pj,ids.screen,ids.wall,...ids.bars].includes(o.uid)&&o.location!=='shelf'){o.location='shelf';o.position={x:4.35,y:1.06,z:5.42};}const put=(id,x,y,z,r=0)=>{C.move(s,id,{x,y,z},'desk');C.get(s,id).rotation=r;};put(ids.pc,-1.1,.928,7.5);put(ids.pj,.35,.928,7.8,Math.PI);put(ids.screen,.35,.168,5.5);put(ids.speakers,-1.25,.928,6.95,Math.PI);put(ids.bars[0],-1.3,.928,7.95);put(ids.bars[1],1.2,.928,7.95);},ids);await view(1.8,10.3,.5,-.2);await p.waitForTimeout(150);
await p.evaluate(ids=>{const C=PhysicalCore,s=PhysicalV4.state,wire=(c,aa,ap,bb,bp)=>{const r=C.connect(s,c,{device:aa,port:ap},{device:bb,port:bp});if(!r.ok)throw Error(r.reason);};ids.bars.forEach((bar,i)=>{wire(ids.extensions[i],ids.wall,'out'+(i+1),bar,'power');wire(ids.iec[i],bar,'out1',[ids.pc,ids.pj][i],'power');C.get(s,bar).powerOn=true;});wire(ids.wire,ids.pc,'vga',ids.pj,'vga');wire(ids.audio,ids.pc,'audio',ids.speakers,'audio');C.get(s,ids.pc).powerOn=true;C.get(s,ids.pj).powerOn=true;},ids);await p.waitForTimeout(400);
a(await p.evaluate(id=>PhysicalCore.signal(PhysicalV4.state,id).valid,ids.pj));a(await p.evaluate(id=>PhysicalCore.signal(PhysicalV4.state,id).valid,ids.speakers));a.equal(await p.evaluate(id=>PhysicalV4.models.get(id).getObjectByName('workshop-projection').material.uniforms.on.value,ids.screen),1);await p.screenshot({path:'documentation/physical-v4/starter-powered.png'});checks.push('wall to two power bars to laptop/projector; laptop AUX to passive stereo pair');
await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).rotation=0,ids.pj);await p.waitForTimeout(120);a.equal(await p.evaluate(id=>PhysicalV4.models.get(id).getObjectByName('workshop-projection').material.uniforms.on.value,ids.screen),0);await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).rotation=Math.PI,ids.pj);await p.waitForTimeout(100);checks.push('projection follows lens direction, screen behind projector stays blank');
await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).powerOn=false,ids.bars[1]);await p.waitForTimeout(100);a(!await p.evaluate(id=>PhysicalCore.signal(PhysicalV4.state,id).valid,ids.pj));a(!await p.evaluate(id=>WorkshopProjection.beams.get(id).visible,ids.pj));await p.evaluate(id=>PhysicalCore.get(PhysicalV4.state,id).powerOn=true,ids.bars[1]);await p.waitForTimeout(100);checks.push('power bar switch interrupts projector and beam');
const before=await p.evaluate(()=>{saveSlots();return{count:PhysicalV4.state.objects.length,links:PhysicalV4.state.links.length};});await p.reload();await p.waitForTimeout(450);await p.evaluate(()=>{showScreen('desktop');StudioWorld.enter();});await p.waitForTimeout(200);a.equal(await p.evaluate(()=>PhysicalV4.state.objects.length),before.count);a.equal(await p.evaluate(()=>PhysicalV4.state.links.length),before.links);checks.push('reload preserves placement and wires without duplicating bundles');a.deepEqual(errors,[]);fs.writeFileSync('documentation/physical-v4/workshop-results.json',JSON.stringify({checks,errors},null,2));console.log('PASS',checks);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});

