const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const errors=[],checks=[];try{const p=await b.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Cindy Signal');await p.locator('#create-vj-button').click();await p.locator('[data-world-computer]').click();await p.locator('.app-button[data-app="finance"]').click();assert.equal(await p.evaluate(()=>profile.money),75);await p.locator('[data-bank-account]').click();assert((await p.locator('[data-bank-panel="account"]').innerText()).includes('Cindy Signal'));const account=await p.evaluate(()=>profile.bank.accountId);checks.push('Compte nominatif visible dans Banque');
await p.locator('[data-bank-tab="management"]').click();await p.locator('[data-loan]').first().click();assert.equal(await p.evaluate(()=>profile.money),375);assert.equal(await p.evaluate(()=>profile.bank.transactions.length),1);checks.push('Prêt versé : +300 $, solde 375 $');
await p.locator('[data-bank-receipt]').first().click();assert(await p.locator('#bank-receipt').isVisible());await p.screenshot({path:'documentation/audit-official-20260914/bank-receipt.png'});await p.getByRole('button',{name:'Fermer le reçu',exact:true}).click();
await p.locator('#app-window').getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(250);await p.locator('.desktop-icon[data-app="skills"]').click();await p.locator('[data-course]').first().click();assert.equal(await p.evaluate(()=>profile.money),195);checks.push('Formation : virement sortant 180 $, solde 195 $');
await p.locator('.app-button[data-app="finance"]').click();await p.locator('[data-bank-tab="management"]').click();await p.locator('[data-pay-loan]').first().click();assert.equal(await p.evaluate(()=>profile.money),160);let rows=await p.evaluate(()=>profile.bank.transactions);assert.deepEqual(rows.map(r=>r.balanceAfter),[375,195,160]);assert.deepEqual(rows.map(r=>r.amount),[300,-180,-35]);assert.equal(new Set(rows.map(r=>r.reference)).size,3);checks.push('Remboursement : 35 $, références uniques, soldes exacts');
await p.locator('[data-bank-tab="transfers"]').click();await p.locator('[data-bank-filter]').selectOption('out');assert.equal(await p.locator('[data-bank-history] [data-bank-receipt]').count(),2);await p.locator('[data-bank-filter]').selectOption('in');assert.equal(await p.locator('[data-bank-history] [data-bank-receipt]').count(),1);checks.push('Filtres entrées / sorties');await p.locator('[data-bank-tab="overview"]').click();await p.waitForTimeout(6000);await p.screenshot({path:'documentation/audit-official-20260914/bank-overview.png'});
await p.reload();await p.locator('#studio-entry-button').click();await p.locator('[data-world-computer]').click();await p.locator('.app-button[data-app="finance"]').click();assert.equal(await p.evaluate(()=>profile.bank.accountId),account);assert.equal(await p.evaluate(()=>profile.money),160);assert.equal(await p.evaluate(()=>profile.bank.transactions.length),3);checks.push('Rechargement : compte, opérations et solde conservés sans double débit');
await p.locator('[data-bank-tab="management"]').click();await p.locator('[data-pay-loan-all]').first().click();assert.equal(await p.evaluate(()=>profile.money),160);assert.equal(await p.evaluate(()=>profile.bank.transactions.length),3);checks.push('Fonds insuffisants : aucune opération créée');
await p.locator('.app-button[data-app="shop"]').click();await p.locator('[data-shop-view="clothing"]').first().click();const ids=await p.locator('[data-buy]:enabled').evaluateAll(nodes=>nodes.map(n=>n.dataset.buy));const item=await p.evaluate(ids=>shopItems.filter(i=>ids.includes(i.id)&&i.cost<=profile.money).sort((a,b)=>a.cost-b.cost)[0],ids);assert(item,'Au moins un vêtement accessible');await p.locator(`[data-buy="${item.id}"]`).first().click();assert.equal(await p.evaluate(()=>profile.money),160-item.cost);assert(await p.evaluate(id=>profile.ownedItems.includes(id),item.id));assert.equal(await p.evaluate(()=>profile.bank.transactions.at(-1).counterparty),'Atazone');checks.push('Achat en boutique : article possédé et virement Atazone du montant exact');
// Legacy fixture: old logs migrate once without inventing historical balances.
await p.evaluate(()=>{delete profile.bank;profile.money=55;profile.financeLog=[{day:1,amount:100,label:'Jobine'},{day:1,amount:-45,label:'Uver Party Garage'}];renderFinance();});assert.equal(await p.evaluate(()=>profile.bank.transactions.length),2);assert(await p.evaluate(()=>profile.bank.transactions.every(r=>r.balanceAfter===null&&r.status==='archive')));await p.evaluate(()=>renderFinance());assert.equal(await p.evaluate(()=>profile.bank.transactions.length),2);assert.equal(await p.evaluate(()=>profile.money),55);checks.push('Ancienne sauvegarde : historique migré une fois, solde préservé');assert.deepEqual(errors,[]);fs.writeFileSync('documentation/audit-official-20260914/bank-tests.json',JSON.stringify({checks,rows,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
