const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Test contrat');await p.locator('#create-vj-button').click();await p.locator('[data-world-computer]').click();await p.locator('.app-button[data-app="social"]').click();const apply=p.locator('[data-simple-apply]').first(),id=await apply.getAttribute('data-simple-apply');await apply.click();const pending=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(pending.status,'pending');for(let i=0;i<7;i++){if(await p.evaluate(id=>profile.gigs.find(g=>g.id===id).status!=='pending',id))break;await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-hours]').fill('12');await p.locator('[data-sleep-hours]').dispatchEvent('input');await p.locator('[data-sleep-confirm]').click();}const offer=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(offer.status,'offered');await p.locator('#app-window').getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(250);await p.locator('.app-button[data-app="social"]').click();
await p.locator('[data-simple-email]').first().click();
const emailId=await p.evaluate(id=>profile.emails.find(e=>e.gigId===id&&e.type==='gig-offer').id,id);await p.locator(`[data-email="${emailId}"]`).click();await p.locator('[data-email-action="accept-gig"]').click();assert(await p.locator('#app-window .traffic.red').isVisible());
let accepted=await p.evaluate(id=>profile.gigs.find(g=>g.id===id),id);assert.equal(accepted.status,'accepted');
while(await p.evaluate(id=>profile.day<getGigAbsoluteDay(profile.gigs.find(g=>g.id===id)),id)){await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-hours]').fill('12');await p.locator('[data-sleep-hours]').dispatchEvent('input');await p.locator('[data-sleep-confirm]').click();}
await p.locator('#app-window').getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(250);await p.locator('.app-button[data-app="social"]').click();await p.locator(`[data-simple-id="${id}"]`).click();
await p.locator('#gig-setup-start-button').click();
await p.waitForTimeout(400);assert(await p.evaluate(()=>document.body.classList.contains('screen-gig')));assert.equal(await p.evaluate(()=>profile.money),30);await p.locator('#connect-projector-button').click();await p.locator('#start-live-button').click();await p.waitForFunction(()=>liveShow?.started);await p.locator('[data-live-view]').click();await p.locator('[data-live-intensity]').fill('35');await p.locator('[data-live-intensity]').dispatchEvent('input');await p.locator('[data-live-take]').click();
let lastPhase=-1;for(let n=0;n<180;n++){if(await p.locator('#result-modal').isVisible())break;const t=await p.evaluate(()=>liveShow?.elapsed||0),phase=Math.min(3,Math.floor(t/15));if(phase!==lastPhase){lastPhase=phase;const value=['35','60','85','25'][phase];await p.locator('[data-live-intensity]').fill(value);await p.locator('[data-live-intensity]').dispatchEvent('input');console.log('Live phase',phase,'temps',t);}await p.waitForTimeout(1000);}
assert(await p.locator('#result-modal').isVisible(),'Le bilan doit s’ouvrir automatiquement');await p.locator('[data-payment-receipt]').click();assert((await p.locator('#bank-receipt').innerText()).includes('Garage de quartier'));await p.getByRole('button',{name:'Fermer le reçu',exact:true}).click();const bilan=await p.locator('#result-modal').innerText();await p.screenshot({path:'documentation/audit-official-20260914/contract-bilan.png'});const paid=await p.evaluate(()=>({money:profile.money,bank:profile.bank.transactions,gig:profile.gigs.find(g=>g.status==='done')}));assert(paid.bank.some(r=>r.label.startsWith('Cachet')&&r.amount>0));const bankSum=paid.bank.reduce((sum,r)=>sum+r.amount,0);assert.equal(paid.money,75+bankSum);await p.locator('#result-close-button').click();await p.reload();await p.locator('#studio-entry-button').click();assert.equal(await p.evaluate(()=>profile.money),paid.money);assert.equal(await p.evaluate(()=>profile.bank.transactions.length),paid.bank.length);assert.deepEqual(errors,[]);fs.writeFileSync('documentation/audit-official-20260914/contract-progress.json',JSON.stringify({accepted,bilan,paid,errors,checks:['Candidature UI','Offre reçue après sommeil','Acceptation UI','Jour du contrat','Débit transport','Connexion UI','Fondu UI','Intensité quatre phases','60 secondes non accélérées','Bilan automatique','Virement client','Rechargement sans double paiement']},null,2));console.log('BILAN',bilan);console.log('BANQUE',paid.bank);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
