const {chromium}=require('C:/Users/VJs DMTeam/AppData/Local/Temp/vj-simulator-qa/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const results=[],errors=[];try{const p=await b.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('QA continuité');await p.locator('#create-vj-button').click();await p.waitForTimeout(400);
// Boundary fixtures run inside an isolated new career, never the player's profile.
let r=await p.evaluate(()=>{profile.studioWorld.seconds=86399;StudioWorld.advanceMinutes(1);return {day:profile.day,clock:StudioWorld.getClock().day}});assert.deepEqual(r,{day:2,clock:2});results.push({test:'minuit sans action préalable',...r});
await p.evaluate(()=>StudioLife.openSleepMenu());await p.locator('[data-sleep-quick="8"]').click();await p.locator('[data-sleep-confirm]').click();r=await p.evaluate(()=>({day:profile.day,hour:StudioWorld.getClock().hour}));assert.equal(r.day,2);assert.equal(r.hour,8);results.push({test:'sommeil UI sans minuit',...r});
await p.evaluate(()=>{profile.studioWorld.seconds=2*86400-3600;StudioLife.openSleepMenu()});await p.locator('[data-sleep-quick="8"]').click();await p.locator('[data-sleep-confirm]').click();r=await p.evaluate(()=>({day:profile.day,clock:StudioWorld.getClock().day,hour:StudioWorld.getClock().hour}));assert.deepEqual(r,{day:3,clock:3,hour:7});results.push({test:'sommeil UI minuit compté une fois',...r});
await p.reload();await p.locator('#studio-entry-button').click();await p.waitForTimeout(350);r=await p.evaluate(()=>({day:profile.day,clock:StudioWorld.getClock().day,hour:StudioWorld.getClock().hour}));assert.deepEqual(r,{day:3,clock:3,hour:7});results.push({test:'rechargement sauvegarde',...r});
await p.locator('[data-world-computer]').click();
for(const app of ['calendar','guide','phone','email','social','transport','music','stats','inventory','finance','settings','skills','shop']){await p.locator(`.desktop-icon[data-app="${app}"]`).click();await p.waitForTimeout(200);const win=p.locator('#app-window');assert(await win.isVisible(),app);results.push({test:'application '+app,text:(await win.innerText()).slice(0,200)});await win.getByRole('button',{name:'Fermer',exact:true}).click();await p.waitForTimeout(220);}
await p.screenshot({path:'documentation/audit-official-20260914/desktop-tested.png'});assert.deepEqual(errors,[]);fs.writeFileSync('documentation/audit-official-20260914/continuity-tests.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
