/* Beginner studio: original procedural visuals and synthesized, prepared 120 BPM beat. */
(() => {
 const key='vj-simulator-academy-v1';
 let saved={lesson:0,best:0,completed:0};try{Object.assign(saved,JSON.parse(localStorage.getItem(key)||'{}'));}catch{}
 saved.lesson=Math.max(0,Math.min(3,Number(saved.lesson)||0));
 const lessons=[
  ['Prépare sans diffuser','La prévisualisation est ton brouillon. Choisis un autre visuel : l’image en salle ne change pas.','Choisis un visuel à préparer.'],
  ['Envoie ton premier fondu','Un fondu mélange progressivement deux images. Prépare une image différente, puis envoie-la en salle.','Réalise un fondu complet.'],
  ['Accompagne l’énergie','Une image intense ne convient pas à tous les moments. Pendant un passage calme, laisse respirer la scène.','Place l’intensité entre 25 et 45 %.'],
  ['Écoute, puis joue','120 BPM signifie 120 pulsations par minute. Ici, un repère de phrase revient tous les 8 temps. Prépare ton image avant ce repère.','Défi : accompagne 4 moments et place un fondu près d’un repère de phrase.']
 ];
 let quick=false,quickStep=0,mission=null,completedFades=0;
 const missions=[
 {title:'Change l’ambiance',instruction:'Prépare un autre visuel et termine un fondu.',skill:'Preview → programme',ranges:[[25,75,'Premier mix']],tip:'Prépare une image différente avant de lancer le fondu.'},
 {title:'Le DJ demande une montée',instruction:'Suis la montée : passe de 35 à 65 %.',skill:'Énergie musicale',ranges:[[25,45,'Installe l’ambiance'],[55,75,'Fais monter l’énergie']],tip:'Quand la montée arrive, augmente vers 65 %.'},
 {title:'Un break propre',instruction:'Baisse au break et termine un fondu pendant le show.',skill:'Intensité et transition',ranges:[[65,85,'Le show bat son plein'],[15,35,'Laisse respirer'],[15,35,'Prépare la reprise'],[50,70,'Relance en douceur']],tip:'Descends vers 25 % au break et termine un fondu pendant le show.'}
 ];
 const duration=()=>mission===null?96:32;
 const phaseLength=()=>mission===null?24:32/missions[mission].ranges.length;
 const currentRanges=()=>mission===null?[[25,45,'Warm-up'],[50,70,'Montée'],[75,95,'Peak'],[15,35,'Break']]:missions[mission].ranges;
 const phaseIndex=()=>Math.min(currentRanges().length-1,Math.floor(elapsed/phaseLength()));
 
 const names=['Orbites / courbes','Échappée / perspective','Mosaïque / composition'];
 let open=false,mode='lesson',playing=false,elapsed=0,last=0,program=0,preview=1,level=.35,fade=null,learned=false,integral=0,hits=0,attempts=0,lastBeat=-1,lastSaved=-1,ac=null,master=null,origin=0,musicWasPlaying=false;
 const launch=document.createElement('button');launch.id='academy-launch';launch.textContent='▶ Mon premier mix · pratique gratuite';document.querySelector('#desktop-screen').append(launch);
 const panel=document.createElement('section');panel.id='academy';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Atelier VJ');
 panel.innerHTML=`<header><div><small>VJ SIMULATOR / ATELIER</small><h1>Le Sous-sol · ta première scène</h1><p>Apprends un geste. Vois son effet. Trouve ton style.</p></div><button data-close>Retour au jeu</button></header>
 <div class="academy-layout"><div><div class="academy-screen"><canvas width="960" height="540" data-output aria-label="Programme projeté en salle"></canvas><span>PROGRAMME / EN SALLE</span></div><div class="academy-beat"><strong data-time>120 BPM · 8 temps par repère</strong><span data-beat>● ○ ○ ○ ○ ○ ○ ○</span></div><p data-cue role="status"></p></div>
 <aside><small data-step></small><h2 data-title></h2><p data-explain></p><p class="academy-task" data-task></p><button data-demo>Voir une démonstration</button><p data-feedback role="status"></p><button data-next disabled>Étape suivante</button></aside></div>
 <div class="academy-controls"><label>PRÉVISUALISATION / HORS DIFFUSION<canvas width="320" height="180" data-preview></canvas><select data-clip aria-label="Visuel à préparer">${names.map((n,i)=>`<option value="${i}">${n}</option>`).join('')}</select></label><div><label>Durée du fondu<select data-duration><option value="1">1 seconde</option><option value="2" selected>2 secondes</option><option value="4">4 secondes</option></select></label><button data-take>Envoyer en fondu →</button><small>La prévisualisation reste invisible au public.</small></div><div><label>Intensité <output data-level>35 %</output><input data-intensity aria-label="Intensité" type="range" min="0" max="100" value="35"></label><button data-play>Jouer le défi · 96 secondes</button><button data-free>Pratique libre · sans note</button></div></div>
 <footer><label>Musique <input data-volume aria-label="Volume de la musique de l’atelier" type="range" min="0" max="100" value="35"></label><label><input data-still type="checkbox"> Mouvements réduits</label><button data-review>Revoir les explications</button><span data-save role="status"></span></footer>`;
 document.body.append(panel);const q=s=>panel.querySelector(s),out=q('[data-output]'),pre=q('[data-preview]');
 const why=document.createElement('details');why.className='quick-why';why.innerHTML='<summary>Pourquoi ?</summary><p>La preview prépare ton image sans modifier la sortie. Un fondu mélange les deux images. L’intensité accompagne le moment musical.</p>';q('aside').append(why);
 function rewardVisual(){if(names.length===3){names.push('Prisme / nouveau visuel');const option=document.createElement('option');option.value=3;option.textContent=names[3];q('[data-clip]').append(option);renderClips();}}
 const clips=document.createElement('div');clips.className='academy-clips';clips.setAttribute('role','group');clips.setAttribute('aria-label','Choisis ton prochain visuel');q('.academy-controls').before(clips);
 function renderClips(){clips.style.setProperty('--clip-count',names.length);clips.replaceChildren();names.forEach((name,id)=>{const button=document.createElement('button');button.type='button';button.dataset.visual=id;button.innerHTML='<canvas width="240" height="135" aria-hidden="true"></canvas><strong></strong><small></small>';button.querySelector('strong').textContent=name.split(' / ')[0];art(button.querySelector('canvas'),id,1);button.onclick=()=>{if(q('[data-clip]').disabled)return;q('[data-clip]').value=id;q('[data-clip]').dispatchEvent(new Event('change'));};clips.append(button);});}
 const timeline=document.createElement('div');timeline.className='academy-timeline';timeline.innerHTML=['Warm-up','Montée','Peak','Break'].map((name,i)=>`<div data-phase="${i}"><span>${name}</span><progress max="24" value="0" aria-label="${name}"></progress></div>`).join('');q('.academy-beat').before(timeline);
 const coaching=document.createElement('p');coaching.className='academy-coaching';coaching.setAttribute('role','status');q('[data-cue]').after(coaching);
 function rewardRoom(){if((saved.roomWins||[]).includes(2)&&names.length===4){names.push('Aurore / rubans lumineux');const option=document.createElement('option');option.value=4;option.textContent=names[4];q('[data-clip]').append(option);renderClips();}}
 const missionList=document.createElement('div');missionList.className='room-missions';q('aside').append(missionList);
 function renderMissions(){const wins=saved.roomWins||[];missionList.innerHTML=missions.map((m,i)=>`<button data-room-mission="${i}" ${i>0&&!wins.includes(i-1)?'disabled':''}><small>${wins.includes(i)?'✓ RÉUSSI · REJOUER':`${i+1} / 3 · 32 S`}</small><strong>${m.title}</strong></button>`).join('');missionList.querySelectorAll('button').forEach(button=>button.onclick=()=>beginMission(Number(button.dataset.roomMission)));}
 function setTimeline(){timeline.innerHTML=currentRanges().map((r,i)=>`<div data-phase="${i}"><span>${r[2]}</span><progress max="${phaseLength()}" value="0" aria-label="${r[2]}"></progress></div>`).join('');}
 function beginMission(id){checkpoint();mission=id;mode='lesson';elapsed=0;completedFades=0;quick=true;quickStep=3;panel.classList.add('quick-show');panel.dataset.quickStep='4';setTimeline();start('challenge');q('[data-feedback]').textContent=missions[id].instruction;}
 function finishMission(){const energy=Math.round(integral/duration()),passed=mission===0?completedFades>0:energy>=80&&(mission!==2||completedFades>0);stop();delete saved.run;if(passed){saved.roomWins=[...new Set([...(saved.roomWins||[]),mission])];if(mission===0)window.VJLearning?.complete('mix');if(mission===2)window.VJLearning?.complete('energy');}rewardRoom();persist();panel.dataset.quickStep='5';q('[data-title]').textContent=passed?'Bien joué !':'Un autre essai ?';q('[data-task]').textContent=passed?`${missions[mission].skill} : objectif réussi.`:'Tu as terminé le show. Un geste reste à pratiquer.';q('[data-feedback]').textContent=passed?(mission===2?'Nouveau visuel débloqué : Aurore. Essaie ses rubans lumineux en pratique libre.':'Le défi suivant est débloqué. Essaie-le quand tu veux.'):(mission!==0&&energy<80?'Ajuste l’intensité dès que le moment musical change.':missions[mission].tip);q('[data-play]').textContent='Rejouer · 32 secondes';q('[data-take]').disabled=true;renderMissions();let actions=q('.room-result-actions');if(!actions){actions=document.createElement('div');actions.className='room-result-actions';q('aside').append(actions);}actions.replaceChildren();const primary=document.createElement('button');primary.dataset.roomContinue='';primary.textContent=passed&&mission<2?'Défi suivant →':passed?'Essayer Aurore →':'Réessayer ce défi';primary.onclick=()=>passed&&mission<2?beginMission(mission+1):passed?q('[data-free]').click():beginMission(mission);actions.append(primary);if(passed){const replay=document.createElement('button');replay.dataset.roomReplay='';replay.textContent='Rejouer ce défi';replay.onclick=()=>beginMission(mission);actions.append(replay);}const choose=document.createElement('button');choose.textContent='Choisir un autre défi';choose.onclick=()=>{quickStep=3;quickPrompt();};actions.append(choose);if(!q('[data-room-free]')){const free=document.createElement('button');free.dataset.roomFree='';free.textContent='Continuer en pratique libre';free.onclick=()=>q('[data-free]').click();q('aside').append(free);}if(passed&&mission===2&&!q('[data-next-place]')){const button=document.createElement('button');button.dataset.nextPlace='';button.textContent='Découvrir le garage →';button.onclick=()=>{q('[data-close]').click();document.querySelector('#field-launch').click();document.querySelector('[data-mission="wall"]').click();};q('aside').append(button);}}
 if(saved.introComplete)rewardVisual();rewardRoom();renderClips();renderMissions();
 const consolePanel=document.createElement('section');consolePanel.className='resolute-console';consolePanel.setAttribute('aria-label','Resolute 8 — régie VJ');clips.before(consolePanel);const bar=document.createElement('div');bar.className='resolute-titlebar';bar.innerHTML='<strong>RESOLUTE <b>8</b></strong><span>COMPOSITION · LE SOUS-SOL</span><small>1 couche · mode apprentissage</small>';consolePanel.append(bar);const deck=document.createElement('div');deck.className='resolute-deck';const layer=document.createElement('div');layer.className='resolute-layer';layer.innerHTML='<small>COMPOSITION</small><strong>Couche 1</strong><span>Visuels · fondu</span>';deck.append(layer,clips);consolePanel.append(deck,q('.academy-controls'));
 const directMonitor=document.createElement('canvas');directMonitor.width=320;directMonitor.height=180;directMonitor.dataset.directProgram='';directMonitor.setAttribute('aria-label','Resolute 8 : sortie vidéo sans décor');const previewLabel=pre.parentElement;previewLabel.firstChild.textContent='PREVIEW · PRÉPARER';const monitorGroup=document.createElement('div');monitorGroup.className='resolute-monitors';previewLabel.before(monitorGroup);const programLabel=document.createElement('label');programLabel.textContent='SORTIE · EN SALLE';programLabel.append(directMonitor);monitorGroup.append(previewLabel,programLabel);
 q('[data-volume]').value=saved.preferences?.volume??35;q('[data-still]').checked=Boolean(saved.preferences?.still);
 const savePreferences=()=>{saved.preferences={volume:Number(q('[data-volume]').value),still:q('[data-still]').checked};if(master)master.gain.setValueAtTime(saved.preferences.volume/100,ac.currentTime);persist();};q('[data-volume]').addEventListener('input',savePreferences);q('[data-still]').addEventListener('change',savePreferences);

 function quickPrompt(){panel.dataset.quickStep=quickStep;const text=[['CHOISIS TON VISUEL','Choisis un visuel, puis envoie-le à l’écran.'],['CHANGE L’AMBIANCE','Prépare un autre visuel, puis fais un fondu.'],['FAIS MONTER L’ÉNERGIE','Mets l’intensité entre 50 et 70 %.'],['TON PREMIER MIX EST LANCÉ','Deux fondus et une montée réussis. Un nouveau visuel est débloqué : Prisme.']][quickStep];q('[data-title]').textContent=text[0];q('[data-task]').textContent=text[1];q('[data-feedback]').textContent=quickStep===0?'':quickStep===1?'✓ Ton image est en salle.':quickStep===2?'✓ Nouveau visuel envoyé en fondu.':'✓ Essaie Prisme, ou joue le premier défi de 32 secondes.';q('[data-play]').textContent='Jouer le premier défi · 32 secondes';}
 document.querySelector('#career-reveal-button').onclick=()=>document.body.classList.toggle('show-careers');
 window.startGuidedPractice=()=>{launch.click();quick=true;if(saved.run){panel.classList.add('quick-show');quickStep=3;panel.dataset.quickStep='4';q('[data-title]').textContent='Ton show est en pause';q('[data-cue]').textContent='Clique sur Reprendre pour continuer au même endroit.';return;}mission=null;setTimeline();quickStep=saved.introComplete?3:0;panel.classList.add('quick-show');mode='lesson';playing=true;elapsed=0;fade=null;program=0;preview=1;level=.65;q('[data-intensity]').value=65;q('[data-level]').textContent='65 %';q('[data-clip]').value=1;q('[data-take]').disabled=false;q('[data-clip]').disabled=false;audio();quickPrompt();};
 function persist(){try{localStorage.setItem(key,JSON.stringify(saved));q('[data-save]').textContent='Apprentissage sauvegardé sur cet ordinateur.';}catch{q('[data-save]').textContent='Sauvegarde indisponible : garde cette fenêtre ouverte.';}}
 function lesson(){learned=false;q('[data-step]').textContent=`ÉTAPE ${saved.lesson+1} / 4`;q('[data-title]').textContent=lessons[saved.lesson][0];q('[data-explain]').textContent=lessons[saved.lesson][1];q('[data-task]').textContent=lessons[saved.lesson][2];q('[data-next]').disabled=true;q('[data-next]').hidden=saved.lesson===3;q('[data-feedback]').textContent='À ton rythme : aucune dépense, aucune pénalité.';}
 function success(text){learned=true;q('[data-feedback]').textContent='✓ '+text;q('[data-next]').disabled=false;}
 function art(canvas,id,t,intensity=1){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;const glow=c.createRadialGradient(w*.5,h*.45,0,w*.5,h*.5,w*.65);glow.addColorStop(0,id===2?'#352044':id===1?'#132c48':'#153039');glow.addColorStop(1,'#040915');c.fillStyle=glow;c.fillRect(0,0,w,h);c.save();c.shadowBlur=w/65;c.shadowColor=id===2?'#e7a975':'#6bded7';c.translate(w/2,h/2);c.lineWidth=w/180;
 if(id===0){for(let i=0;i<9;i++){c.strokeStyle=i%2?'#f7abff':'#59e1da';c.beginPath();c.ellipse(Math.sin(t*.3+i)*w*.08,0,w*(.08+i*.025),h*(.09+i*.03),i*.24+t*.1,0,Math.PI*2);c.stroke();}}
 if(id===1){for(let i=1;i<13;i++){const z=((i+t*.65)%13)/13;c.strokeStyle=i%2?'#aab0ff':'#57ddd1';c.strokeRect(-w*z/2,-h*z/2,w*z,h*z);}}
 if(id===3){for(let i=0;i<20;i++){c.save();c.rotate(i*Math.PI/10+t*.08);c.strokeStyle=i%2?'#f6bb77':'#8bf1e3';c.beginPath();c.moveTo(w*.07,0);c.lineTo(w*.25,h*.17);c.lineTo(w*.37,0);c.stroke();c.restore();}}
 if(id===4){for(let band=0;band<7;band++){const gradient=c.createLinearGradient(-w/2,0,w/2,0);gradient.addColorStop(0,'#48cfd7');gradient.addColorStop(.5,band%2?'#b98bff':'#f0baff');gradient.addColorStop(1,'#ffba80');c.strokeStyle=gradient;c.lineWidth=w*(.004+band*.001);c.beginPath();for(let x=-w/2;x<=w/2;x+=5){const y=Math.sin(x/w*5+t*.45+band*.12)*h*.22+Math.sin(x/w*9-t*.3+band*.2)*h*.08+(band-3)*h*.025;if(x===-w/2)c.moveTo(x,y);else c.lineTo(x,y);}c.stroke();}}
 if(id===2){for(let x=-3;x<=3;x++)for(let y=-2;y<=2;y++){c.save();c.translate(x*w/8,y*h/6);c.rotate(t*.12+(x+y)*.25);c.fillStyle=(x+y)%2?'#f6b977':'#947ef5';c.fillRect(-w/35,-w/35,w/17,w/17);c.restore();}}
 c.restore();c.fillStyle=`rgba(0,0,0,${1-intensity})`;c.fillRect(0,0,w,h);}
 const buffer=document.createElement('canvas');buffer.width=960;buffer.height=540;
 function take(demo=false){if(fade||(mode==='challenge'&&!playing))return;if(preview===program){q('[data-feedback]').textContent='Ce visuel est déjà en salle. Choisis-en un autre dans la prévisualisation.';return;}fade={time:0,duration:Number(q('[data-duration]').value),demo};q('[data-take]').disabled=true;q('[data-clip]').disabled=true;if(playing&&mode==='challenge'&&!demo){attempts++;const phase=elapsed%4;if(Math.min(phase,4-phase)<=.35)hits++;}q('[data-feedback]').textContent=demo?'Démonstration : les deux images se mélangent. À toi ensuite.':'Fondu en cours…';}
 function audio(){if(!ac){ac=new AudioContext();master=ac.createGain();master.connect(ac.destination);}master.gain.value=Number(q('[data-volume]').value)/100;ac.resume();origin=ac.currentTime-elapsed;}
 function checkpoint(){if(mode==='challenge'&&elapsed>0&&elapsed<duration()){saved.run={elapsed,integral,hits,attempts,program,preview,level,fade,mission,completedFades};persist();}}
 function stop(){checkpoint();playing=false;ac?.suspend();q('[data-play]').textContent=elapsed>0&&elapsed<duration()?'Reprendre le défi':'Jouer le défi · 96 secondes';}
 function start(kind){if(playing&&mode===kind){stop();return;}if(mode!==kind||elapsed>=duration()){elapsed=0;integral=0;hits=0;attempts=0;completedFades=0;fade=null;lastBeat=-1;q('[data-clip]').disabled=false;q('[data-take]').disabled=false;}mode=kind;playing=true;audio();q('[data-feedback]').textContent=kind==='challenge'?(mission===null?'Prépare ton image, puis lance un fondu sur le temps 1.':missions[mission].instruction):'Explore à ton rythme.';q('[data-play]').textContent='Pause';q('[data-free]').textContent=kind==='free'?'Pause pratique libre':'Pratique libre · sans note';q('[data-next]').hidden=true;q('[data-demo]').disabled=true;q('[data-title]').textContent=kind==='free'?'Explore à ton rythme':'Défi : quatre moments';q('[data-explain]').textContent=kind==='free'?'Essaie chaque visuel et chaque durée. Aucun score, aucun coût.':'Critères : intensité dans la plage annoncée (70 %) ; au moins un fondu près d’un repère de phrase, ± 0,35 s (30 %). Aucun jugement de beauté.';}
 function finish(){if(mission!==null){finishMission();return;}stop();delete saved.run;const energy=Math.max(0,Math.min(100,Math.round(integral/96))),rhythm=hits?100:0,score=Math.round(energy*.7+rhythm*.3);if(energy>=80)window.VJLearning?.complete('energy');saved.best=Math.max(Number(saved.best)||0,score);saved.completed=(Number(saved.completed)||0)+1;persist();q('[data-title]').textContent=`Prestation terminée · ${score}/100`;q('[data-explain]').textContent=`Ambiance : ${energy}/100. Fondu près d’un repère : ${hits?'réussi':'à pratiquer'}. ${attempts} fondu(s) lancé(s). Le nombre de clics ne donne aucun point supplémentaire.`;q('[data-task]').textContent=energy<80?'Prochain essai : prépare l’intensité annoncée pour chaque passage.':!hits?'Prochain essai : prépare ton clip, puis envoie-le au temps 1 d’un nouveau repère.':'Objectifs atteints. Rejoue avec une autre composition : plusieurs choix sont valables.';q('[data-feedback]').textContent=`Meilleur résultat : ${saved.best}/100 · ${saved.completed} prestation(s) terminée(s).`;q('[data-play]').textContent='Recommencer le défi';q('[data-take]').disabled=true;if(quick){panel.dataset.quickStep='5';q('[data-title]').textContent='Prestation terminée';q('[data-task]').textContent=energy>=80?'Tu as bien accompagné l’énergie.':'Tu as livré ton premier show.';q('[data-feedback]').textContent=hits?'✓ Compétence pratiquée : transition sur un repère. Fondu placé près du repère musical. Prochain essai : garde la même attention pendant le break.':'Prochain essai : prépare ton image avant le temps 1, puis lance le fondu sur ce repère.';if(!q('[data-next-place]')){const next=document.createElement('button');next.dataset.nextPlace='';next.textContent='Prochain lieu : le garage →';next.onclick=()=>{q('[data-close]').click();document.querySelector('#field-launch').click();document.querySelector('[data-mission="wall"]').click();};q('aside').append(next);}}}
 function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(open){if(playing){const previousElapsed=elapsed;elapsed+=dt;if(ac&&ac.state==='running'){// Use the same audio clock for audible beat and visual/scoring timeline.
 elapsed=ac.currentTime-origin;
 const beat=Math.floor(elapsed*2);if(beat!==lastBeat){lastBeat=beat;const musicalRange=currentRanges()[phaseIndex()],musicalEnergy=mode==='challenge'?(musicalRange[0]+musicalRange[1])/200:.55;const oscillator=ac.createOscillator(),gain=ac.createGain();oscillator.frequency.value=beat%8===0?110:beat%2===0?75:220;gain.gain.setValueAtTime(.035+musicalEnergy*.085,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.09);oscillator.connect(gain);gain.connect(master);oscillator.start();oscillator.stop(ac.currentTime+.1);if(musicalEnergy>.5){const accent=ac.createOscillator(),ag=ac.createGain();accent.type='triangle';accent.frequency.value=beat%2?784:587.33;ag.gain.setValueAtTime(.012*musicalEnergy,ac.currentTime+.25);ag.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.4);accent.connect(ag);ag.connect(master);accent.start(ac.currentTime+.25);accent.stop(ac.currentTime+.42);}if(beat%8===0){const chords=[[130.81,164.81,196],[110,130.81,164.81],[87.31,110,130.81],[98,123.47,146.83]],notes=chords[Math.floor(beat/8)%4];for(const hz of notes){const tone=ac.createOscillator(),envelope=ac.createGain();tone.type=musicalEnergy>.6?'triangle':'sine';tone.frequency.value=hz;envelope.gain.setValueAtTime(0,ac.currentTime);envelope.gain.linearRampToValueAtTime(.012+musicalEnergy*.024,ac.currentTime+.12);envelope.gain.linearRampToValueAtTime(0,ac.currentTime+3.8);tone.connect(envelope);envelope.connect(master);tone.start();tone.stop(ac.currentTime+3.85);}}}}
 const r=currentRanges()[phaseIndex()];if(mode==='challenge')integral+=(mission===null?Math.max(0,100-Math.max(r[0]-level*100,0,level*100-r[1])*2):(level*100>=r[0]&&level*100<=r[1]?100:0))*Math.max(0,Math.min(duration(),elapsed)-previousElapsed);
 q('[data-cue]').textContent=mode==='free'?'Pratique libre : explore sans limite de temps.':`${r[2]} · intensité ${r[0]}–${r[1]} %`;
 q('[data-time]').textContent=`${Math.floor(elapsed)} ${mode==='challenge'?'/ '+duration()+' ':''}s · 120 BPM`;q('[data-beat]').textContent=Array.from({length:8},(_,i)=>i===Math.floor(elapsed*2)%8?`${i+1} ●`:`${i+1} ○`).join(' ');if(mode==='challenge'&&elapsed>=duration())finish();else if(Math.floor(elapsed)!==lastSaved){lastSaved=Math.floor(elapsed);checkpoint();}}
 panel.dataset.mode=mode;panel.dataset.playing=playing;panel.classList.toggle('room-run',mission!==null);
 clips.querySelectorAll('button').forEach(button=>{const id=Number(button.dataset.visual);button.setAttribute('aria-pressed',String(id===preview));button.disabled=Boolean(fade);button.dataset.program=String(id===program&&!(quick&&mode==='lesson'&&quickStep===0));button.querySelector('small').textContent=id===preview?'PRÊT EN PREVIEW':button.dataset.program==='true'?'EN SALLE':'Préparer';});
 if(mode==='challenge'){
 const phase=phaseIndex(),range=currentRanges()[phase],value=Math.round(level*100),good=value>=range[0]&&value<=range[1];
 timeline.querySelectorAll('[data-phase]').forEach((el,i)=>{el.dataset.active=String(i===phase);el.querySelector('progress').value=Math.max(0,Math.min(phaseLength(),elapsed-i*phaseLength()));});
 coaching.dataset.good=String(good);coaching.textContent=!playing?(elapsed>=duration()?'Show terminé — rejoue ou découvre le garage.':'En pause — reprends quand tu veux.'):good?'✓ Bonne intensité. Prépare ton prochain visuel.':value<range[0]?'↑ Monte doucement l’intensité.':'↓ Baisse l’intensité pour laisser respirer ce passage.';
 if(mission===0&&playing){q('[data-cue]').textContent='Prépare une autre image, puis envoie-la en fondu.';coaching.dataset.good=String(completedFades>0);coaching.textContent=completedFades>0?'✓ Fondu terminé. Profite du show ou essaie un autre visuel.':'La preview reste invisible au public tant que tu ne l’envoies pas.';}
 if(quick&&playing){q('[data-title]').textContent=currentRanges()[phase][2].toUpperCase();}
 }else coaching.textContent='';
 const t=q('[data-still]').checked?0:now/1000;art(out,program,t,level);if(quick&&mode==='lesson'&&quickStep===0){const c=out.getContext('2d');c.fillStyle='#091322';c.fillRect(0,0,out.width,out.height);c.fillStyle='#c0e7ef';c.font='26px Arial';c.textAlign='center';c.fillText('L’écran attend ton premier visuel',out.width/2,out.height/2);c.textAlign='start';}art(pre,preview,t);
 if(fade){if(playing||mode==='lesson')fade.time+=dt;art(buffer,preview,t,level);const c=out.getContext('2d');c.globalAlpha=Math.min(1,fade.time/fade.duration);c.drawImage(buffer,0,0);c.globalAlpha=1;if(fade.time>=fade.duration){const demo=fade.demo;if(!demo&&mode==='challenge'){completedFades++;q('[data-feedback]').textContent='✓ Fondu terminé : la nouvelle image est en salle.';}[program,preview]=[preview,program];fade=null;q('[data-clip]').value=preview;q('[data-clip]').disabled=false;q('[data-take]').disabled=false;if(quick&&mode==='lesson'&&!demo&&quickStep<2){quickStep++;if(quickStep===2)window.VJLearning?.complete('mix');quickPrompt();}if(!quick&&mode==='lesson'&&saved.lesson===1&&!demo){success('Ton nouveau visuel est en salle.');window.VJLearning?.complete('mix');}}}
 directMonitor.getContext('2d').drawImage(out,0,0,320,180);if(quick)window.VJRoom?.draw(out,{time:elapsed,level:quickStep===0&&mode==='lesson'?0:level,still:q('[data-still]').checked,playing});}requestAnimationFrame(frame);}
 launch.onclick=()=>{quick=false;panel.classList.remove('quick-show');open=true;panel.hidden=false;launch.hidden=true;musicWasPlaying=!musicAudio.paused;musicAudio.pause();mode='lesson';playing=false;mission=null;q('[data-demo]').disabled=false;lesson();if(saved.run){const r=saved.run;mission=Number.isInteger(r.mission)&&r.mission>=0&&r.mission<3?r.mission:null;completedFades=Number(r.completedFades)||0;elapsed=Math.max(0,Math.min(duration()-.01,Number(r.elapsed)||0));integral=Number(r.integral)||0;hits=Number(r.hits)||0;attempts=Number(r.attempts)||0;program=Math.max(0,Math.min(names.length-1,Number(r.program)||0));preview=Math.max(0,Math.min(names.length-1,Number(r.preview)||0));level=Math.max(0,Math.min(1,(Number.isFinite(Number(r.level))?Number(r.level):.35)));fade=r.fade||null;q('[data-clip]').disabled=Boolean(fade);q('[data-take]').disabled=Boolean(fade);mode='challenge';q('[data-title]').textContent='Ton défi est en pause';q('[data-play]').textContent='Reprendre le défi';q('[data-feedback]').textContent=`Reprise à ${Math.floor(elapsed)} / ${duration()} secondes. Clique sur Reprendre pour continuer.`;q('[data-clip]').value=preview;q('[data-intensity]').value=level*100;q('[data-level]').textContent=`${Math.round(level*100)} %`;q('[data-next]').hidden=true;}setTimeline();renderMissions();q('[data-close]').focus();};
 q('[data-close]').onclick=()=>{stop();open=false;panel.hidden=true;launch.hidden=false;if(musicWasPlaying)musicAudio.play().catch(()=>{});launch.focus();};
 q('[data-clip]').value=preview;q('[data-clip]').onchange=e=>{preview=Number(e.target.value);if(mode==='lesson'&&saved.lesson===0&&preview!==program)success('Tu as changé le brouillon. Le programme reste intact.');};
 q('[data-take]').onclick=()=>take();q('[data-intensity]').oninput=e=>{level=Number(e.target.value)/100;q('[data-level]').textContent=`${e.target.value} %`;if(quick&&quickStep===2&&level>=.5&&level<=.7){quickStep=3;saved.introComplete=true;rewardVisual();persist();quickPrompt();}if(!quick&&mode==='lesson'&&saved.lesson===2&&level>=.25&&level<=.45)success('Cette intensité laisse respirer la scène.');};
 q('[data-next]').onclick=()=>{if(!learned)return;saved.lesson=Math.min(3,saved.lesson+1);persist();lesson();};
 q('[data-demo]').onclick=()=>{if(saved.lesson===0){preview=(program+1)%3;q('[data-clip]').value=preview;q('[data-feedback]').textContent='Démonstration : seul le petit écran change. Choisis maintenant un autre visuel toi-même.';}else if(saved.lesson===2){level=.35;q('[data-intensity]').value=35;q('[data-level]').textContent='35 %';q('[data-feedback]').textContent='Démonstration : à 35 %, la projection laisse respirer la scène. Essaie le curseur toi-même.';}else if(saved.lesson===3){q('[data-feedback]').textContent='Lance le défi : les temps sont numérotés sous la projection. Le son grave et le temps 1 annoncent le même repère.';}else{preview=(program+1)%3;q('[data-clip]').value=preview;take(true);}};
 q('[data-play]').onclick=()=>{if(quick&&mode!=='challenge'){beginMission(Math.min(2,(saved.roomWins||[]).length));return;}if(quick){quickStep=3;panel.dataset.quickStep='4';}start('challenge');};q('[data-free]').onclick=()=>{checkpoint();mission=null;setTimeline();if(quick)panel.dataset.quickStep='free';start('free');q('[data-task]').textContent='Choisis une image, prépare la suivante, puis fais un fondu.';q('[data-feedback]').textContent='À toi de créer. Tu peux jouer le mini-show quand tu veux.';};q('[data-review]').onclick=()=>{stop();mission=null;quick=false;panel.classList.remove('quick-show');setTimeline();mode='lesson';delete saved.run;saved.lesson=0;persist();q('[data-demo]').disabled=false;lesson();};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape')q('[data-close]').click();if(e.key==='Tab'){const controls=[...panel.querySelectorAll('button,input,select')].filter(el=>!el.disabled&&!el.hidden&&el.offsetParent);const first=controls[0],end=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}}});
 window.addEventListener('pagehide',checkpoint);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&open)stop();});requestAnimationFrame(frame);
})();
