const {chromium}=require('../qa-browser.cjs'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Repetition QA');await p.locator('#create-vj-button').click();await p.evaluate(()=>StudioWorld.showComputer());await p.locator('[data-rehearsal-launch]').click();await p.locator('#studio-rehearsal').waitFor({state:'visible'});assert(await p.evaluate(()=>StudioRehearsal.show instanceof VJLiveShow));const baseline=await p.evaluate(()=>({money:profile.money,sessions:profile.showSessions||0,day:profile.day,clock:StudioWorld.getClock(),statuses:profile.gigs.map(g=>g.status)}));await p.screenshot({path:'documentation/shared-rehearsal-20260915/studio-start.png'});
for(let phase=0;phase<4;phase++){assert.equal(await p.evaluate(()=>StudioRehearsal.show.paused),true);assert.equal(await p.evaluate(()=>StudioRehearsal.show.cueIndex),phase);await p.locator('[data-rehearsal-go]').click();const range=await p.evaluate(()=>{const s=StudioRehearsal.show,c=s.cues[s.cueIndex];return Math.round((c.low+c.high)/2)});await p.locator('#studio-rehearsal [data-live-intensity]').fill(String(range));await p.locator('#studio-rehearsal [data-live-intensity]').dispatchEvent('input');
if(phase===1||phase===2){const target=await p.evaluate(()=>String((StudioRehearsal.show.currentIndex+1)%StudioRehearsal.show.clips.length));await p.locator('#studio-rehearsal [data-live-select]').selectOption(target);await p.waitForFunction(()=>StudioRehearsal.show.preview.readyState>=2);await p.locator(phase===1?'#studio-rehearsal [data-live-take]':'#studio-rehearsal [data-live-sync]').click();}
await p.waitForFunction(phase=>StudioRehearsal.show.stageTasks[phase],phase,{timeout:14000});console.log('Action complete',phase);await p.screenshot({path:`documentation/shared-rehearsal-20260915/action-${phase}.png`});
if(phase===1){await p.locator('#studio-rehearsal [data-live-pause]').click();const elapsed=await p.evaluate(()=>StudioRehearsal.show.elapsed);await p.locator('[data-rehearsal-close]').click();await p.reload();await p.locator('#studio-entry-button').click();await p.evaluate(()=>StudioWorld.showComputer());await p.locator('[data-rehearsal-launch]').click();assert.equal(await p.evaluate(()=>StudioRehearsal.show.elapsed),elapsed);assert.equal(await p.evaluate(()=>StudioRehearsal.show.stageTasks[1]),true);await p.locator('[data-rehearsal-go]').click();}
await p.waitForFunction(phase=>StudioRehearsal.show.completed||(StudioRehearsal.show.paused&&StudioRehearsal.show.cueIndex===phase+1),phase,{timeout:20000});}
const result=await p.evaluate(()=>StudioRehearsal.show.result());assert.deepEqual(result.stageTasks,[true,true,true,true]);await p.locator('[data-rehearsal-result]').waitFor({state:'visible'});await p.screenshot({path:'documentation/shared-rehearsal-20260915/result.png'});const after=await p.evaluate(()=>({money:profile.money,sessions:profile.showSessions||0,day:profile.day,statuses:profile.gigs.map(g=>g.status)}));assert.equal(after.money,baseline.money);assert.equal(after.sessions,baseline.sessions);assert.equal(after.day,baseline.day);assert.deepEqual(after.statuses,baseline.statuses);
await p.locator('[data-rehearsal-restart]').click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:'documentation/shared-rehearsal-20260915/mobile.png'});for(const sel of ['[data-rehearsal-go]','[data-rehearsal-close]']){await p.locator(sel).scrollIntoViewIfNeeded();assert(await p.locator(sel).evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el}));}await p.locator('[data-rehearsal-close]').click();assert.equal(await p.evaluate(()=>StudioRehearsal.isOpen),false);assert.deepEqual(errors,[]);fs.writeFileSync('documentation/shared-rehearsal-20260915/tests.json',JSON.stringify({result,baseline,after,errors},null,2));console.log('PASS: same live engine, four real actions, guided pauses, restore, no payout or contract mutation, mobile and exit');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
