const {chromium}=require('../qa-browser.cjs'),{measure}=require('../desktop-layout-20260915/audit.cjs'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),dir='documentation/design-items-20260915',errors=[],rows=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Catalogue QA');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);await p.evaluate(()=>{StudioWorld.showComputer();profile.settings.reducedMotion=true;profile.money=500;profile.stats.level=10;openApp('shop');shopView='gear';shopGearFilter='projector';renderDesktop();});
 await p.locator('[data-catalog-search]').focus();await p.keyboard.type('laser',{delay:50});assert.equal(await p.locator('.shop-card[data-detail]').count(),2);assert.equal(await p.locator('[data-catalog-search]').inputValue(),'laser');await p.locator('[data-catalog-clear]').click();
 await p.locator('[data-catalog-budget]').check();assert.equal(await p.locator('.shop-card[data-detail]').count(),2);assert(await p.locator('[data-detail="projector-standard"]').isVisible());await p.locator('[data-catalog-budget]').uncheck();
 await p.locator('[data-catalog-sort]').selectOption('price-down');const sorted=await p.locator('.shop-card[data-detail]').evaluateAll(es=>es.map(e=>shopItems.find(i=>i.id===e.dataset.detail).cost));assert.deepEqual(sorted,[...sorted].sort((a,b)=>b-a));await p.locator('[data-catalog-sort]').selectOption('level');
 await p.locator('[data-open-detail="projector-pro-6500"]').click();await p.locator('[data-item-3d]').click();await p.waitForFunction(()=>ItemInspector.model?.userData.designVersion===2);
 for(const angle of ['front','back','three-quarter']){await p.locator('[data-model-angle="'+angle+'"]').click();assert(await p.locator('[data-model-angle="'+angle+'"]').getAttribute('aria-pressed')==='true');}
 const before=await p.evaluate(()=>ItemInspector.stage.pivot.rotation.y);await p.locator('.product-inspector [data-model-view]').press('ArrowRight');assert.notEqual(await p.evaluate(()=>ItemInspector.stage.pivot.rotation.y),before);
 await p.locator('[data-model-compare]').click();assert.equal(await p.evaluate(()=>ItemInspector.model.userData.itemId),'projector-cheap');await p.locator('[data-model-compare]').click();assert.equal(await p.evaluate(()=>ItemInspector.model.userData.itemId),'projector-pro-6500');await p.locator('[data-model-zoom]').fill('75');await p.locator('[data-model-zoom]').dispatchEvent('input');await p.locator('[data-model-reset]').click();assert.equal(await p.locator('[data-model-zoom]').inputValue(),'100');
 for(const size of [{width:1440,height:1000},{width:1116,height:717},{width:390,height:844}]){await p.setViewportSize(size);await p.waitForTimeout(120);const m=await p.evaluate(measure,'.item-inspector[open]');rows.push({name:'inspector',size,...m});assert(!m.overflow&&!m.offscreen&&!m.issues.length,JSON.stringify(rows.at(-1)));await p.screenshot({path:dir+'/inspector-'+size.width+'.png'});}
 await p.locator('[data-model-close]').click();
 for(const size of [{width:1440,height:1000},{width:1116,height:717},{width:390,height:844}]){await p.setViewportSize(size);for(const category of ['gear','clothing','vjloop']){await p.evaluate(c=>{shopDetailItemId=null;shopView=c;renderDesktop();},category);await p.waitForTimeout(350);const m=await p.evaluate(measure);rows.push({name:category,size,...m});assert(!m.overflow&&!m.offscreen&&!m.issues.length,JSON.stringify(rows.at(-1)));await p.screenshot({path:dir+'/'+category+'-'+size.width+'.png'});}}
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{shopView='gear';shopDetailItemId='projector-standard';renderDesktop();});await p.locator('[data-buy="projector-standard"]').click();assert.equal(await p.evaluate(()=>profile.money),220);assert.equal(await p.evaluate(()=>profile.gear.projector),'standard');
 await p.locator('#leave-studio-computer').click();await p.waitForFunction(()=>scene.getObjectByName('Studio equipped projector')?.userData.itemId==='projector-standard');assert.equal(await p.evaluate(()=>scene.getObjectByName('Studio equipped projector').userData.designVersion),2);
 await p.evaluate(()=>saveSlots());await p.reload();await p.locator('#studio-entry-button').click();assert.equal(await p.evaluate(()=>profile.money),220);assert.equal(await p.evaluate(()=>profile.gear.projector),'standard');await p.waitForFunction(()=>scene.getObjectByName('Studio equipped projector')?.userData.itemId==='projector-standard');
 assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/integration.json',JSON.stringify({rows,errors},null,2));console.log('PASS: search typing, price sorting, budget filter, 3D views/keyboard/zoom/reset/equipment comparison, 12 layouts, purchase, physical model and save reload');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
