const {chromium}=require('../qa-browser.cjs'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],dir='documentation/design-items-20260915';p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5181/');await p.locator('#studio-entry-button').click();await p.locator('#vj-name').fill('Catalogue design');await p.locator('#create-vj-button').click();await p.waitForFunction(()=>player.userData.loaded);
 const items=await p.evaluate(()=>shopItems.filter(i=>['gear','clothing'].includes(i.category)).map(i=>({id:i.id,label:i.label,type:i.type,category:i.category}))),rows=[];
 for(const item of items){const start=Date.now();const data=await p.evaluate(async id=>{const item=shopItems.find(i=>i.id===id),g=ItemModels.create(item),box=new THREE.Box3().setFromObject(g);let vertices=0,meshes=0,finite=true;g.traverse(o=>{if(!o.isMesh)return;meshes++;vertices+=o.geometry.attributes.position.count;finite&&=[...o.geometry.attributes.position.array].every(Number.isFinite);});const size=box.getSize(new THREE.Vector3()).toArray();ProductStage.dispose(g);return {png:await ItemPreviews.get(id),vertices,meshes,finite,size};},item.id);assert(data.finite&&data.size.every(v=>v>0&&v<4),item.id);assert(data.png.length>5000,item.id);fs.writeFileSync(dir+'/'+item.id+'.png',Buffer.from(data.png.split(',')[1],'base64'));delete data.png;rows.push({...item,...data,ms:Date.now()-start});}
 fs.writeFileSync(dir+'/models.json',JSON.stringify({rows,errors},null,2));assert.deepEqual(errors,[]);
 for(const category of ['gear','clothing']){const html='<!doctype html><meta charset="utf-8"><style>body{background:#101923;color:#d9e1e7;font:15px Arial;margin:18px}main{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}article{background:#17212d;border:1px solid #384659;border-radius:12px;overflow:hidden}img{width:100%;display:block}p{margin:0;padding:14px}</style><h1>'+category+'</h1><main>'+items.filter(i=>i.category===category).map(i=>'<article><img src="'+i.id+'.png"><p>'+i.label+'</p></article>').join('')+'</main>';fs.writeFileSync(dir+'/'+category+'.html',html);await p.goto('http://127.0.0.1:5181/'+dir+'/'+category+'.html');await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:dir+'/'+category+'-sheet.png',fullPage:true});}
 console.log(JSON.stringify({models:items.length,errors,maxMeshes:Math.max(...rows.filter(r=>r.category==='gear').map(r=>r.meshes)),maxVertices:Math.max(...rows.filter(r=>r.category==='gear').map(r=>r.vertices))}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
