/* Terrain exercises and skill progression share the active career save. */
window.VJProgression ||= (()=>{
 const thresholds=[0,100,260,500,800,1200];
 const rewards={mix:['timePressure',12],wall:['mapping',22],energy:['timePressure',18],cable:['cabling',22],client:['timePressure',12],contract:['cabling',10]};
 function root(){
  if(!profile)return null;profile.settings ||= {};profile.settings.progression ||= {version:1,skillXp:{},learning:{},practiceLog:{},history:[]};
  const p=profile.settings.progression;p.skillXp ||= {};p.learning ||= {};p.practiceLog ||= {};p.history ||= [];
  if(!p.legacyLearningMigrated){try{const old=JSON.parse(localStorage.getItem('vj-field-learning-v1')||'{}')||{};Object.entries(old).forEach(([id,v])=>{if(v)p.learning[id]=true;});}catch{}p.legacyLearningMigrated=true;}
  profile.skills ||= {};Object.entries(profile.skills).forEach(([id,l])=>{if(!Number.isFinite(Number(p.skillXp[id])))p.skillXp[id]=thresholds[Math.max(0,Math.min(5,Number(l)||0))]||0;});return p;
 }
 function levelForXp(xp){let l=0;for(let i=1;i<thresholds.length;i++)if(xp>=thresholds[i])l=i;return l;}
 function get(id){const p=root(),xp=Math.max(0,Number(p?.skillXp?.[id])||0),level=levelForXp(xp),floor=thresholds[level],next=thresholds[Math.min(level+1,5)];return{id,xp,level,intoLevel:xp-floor,needed:level>=5?0:next-floor,maxLevel:5};}
 function addXp(id,base,source='practice',evidence=null){const p=root();if(!p)return{gained:0,...get(id)};const before=get(id),day=Number(profile.day)||1,key=`${day}:${id}:${source}`,n=Number(p.practiceLog[key])||0,m=source==='gig'||source==='course'?1:[1,.65,.4,.25][Math.min(n,3)];p.practiceLog[key]=n+1;const gained=Math.max(1,Math.round((Number(base)||0)*m));p.skillXp[id]=(Number(p.skillXp[id])||0)+gained;const after=get(id);profile.skills[id]=Math.max(Number(profile.skills[id])||0,after.level);profile.skillEvidence ||= {};profile.skillEvidence[id] ||= [];if(evidence&&!profile.skillEvidence[id].includes(evidence))profile.skillEvidence[id].push(evidence);p.history.push({day,skill:id,xp:gained,source,evidence:evidence||null});if(p.history.length>80)p.history.splice(0,p.history.length-80);if(after.level>before.level)notify(`${skillCatalog.find(s=>s.id===id)?.label||id} passe niveau ${after.level}.`);unlockGigs();saveSlots();window.dispatchEvent(new CustomEvent('vj-progression',{detail:{id,gained,source,before,after}}));return{gained,multiplier:m,...after,leveled:after.level>before.level};}
 function completeLearning(id){const p=root();if(!p)return false;const first=!p.learning[id];p.learning[id]=true;if(first&&rewards[id])addXp(rewards[id][0],rewards[id][1],'lesson',`lesson-${id}`);else saveSlots();window.dispatchEvent(new Event('vj-learning'));return true;}
 function readLearning(){return{...(root()?.learning||{})};}
 function progressText(id){const s=get(id);return s.level>=5?`Niveau ${s.level} · maîtrise`:`Niveau ${s.level} · ${s.intoLevel}/${s.needed} XP vers niveau ${s.level+1}`;}
 return{thresholds,get,addXp,completeLearning,readLearning,progressText,courseXp:(id,t=1)=>addXp(id,45+Math.max(0,t-1)*18,'course',`course-${id}-${t}-day-${Number(profile?.day)||1}`),gigXp:(id,q=1,g='gig')=>addXp(id,Math.round(22+Math.max(0,q)*18),'gig',`${g}:${id}`)};
})();

window.VJLearning={read(){return VJProgression.readLearning();},complete(id){return VJProgression.completeLearning(id);}};

(()=>{
 const missions=[['mix','Premier mix','Préparer en preview puis diffuser un fondu.'],['wall','Le mur du garage','Trouver la sortie et cadrer la projection.'],['energy','Le DJ demande une montée','Accompagner warm-up, montée, peak et break.'],['cable','Le câble trop court','Résoudre une contrainte de distance et de budget.'],['client','Le client veut plus intense','Clarifier sa demande et conserver une image lisible.'],['contract','Premier vrai contrat','Préparer, jouer et recevoir un bilan.']];
 const button=document.createElement('button');button.id='field-launch';button.textContent='Mon parcours VJ';document.querySelector('#desktop-screen').append(button);
 const root=document.createElement('section');root.id='field-school';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Parcours VJ');document.body.append(root);
 let active='',connected=false,x=70,size=70,skew=25,clarified=false;
 const q=s=>root.querySelector(s);
 function close(){root.hidden=true;button.focus();}
 function shell(title){root.innerHTML=`<header><div><small>APPRENDRE → PRATIQUER → JOUER → COMPRENDRE</small><h1>${title}</h1></div><button data-exit>Retour au jeu</button></header><div data-content></div><p data-feedback role="status"></p>`;q('[data-exit]').onclick=close;}
 function hub(){shell('Construis tes compétences de VJ');const progress=VJLearning.read();q('[data-content]').innerHTML=`<p>Des situations courtes liées à ta vraie carrière. Une première réussite donne de l’XP ; rejouer sert à pratiquer, mais rapporte moins pour éviter le farming.</p><div class="field-cards">${missions.map(([id,title,desc],i)=>`<article><small>${progress[id]?'✓ RÉUSSI':i===0||progress[missions[i-1][0]]?'À JOUER':'À DÉBLOQUER'}</small><h2>${i+1}. ${title}</h2><p>${desc}</p><button data-mission="${id}" ${i>0&&!progress[missions[i-1][0]]?'disabled':''}>${progress[id]?'Rejouer':'Commencer'}</button>${i>0&&!progress[missions[i-1][0]]?`<small>Réussis « ${missions[i-1][1]} » pour continuer.</small>`:''}</article>`).join('')}</div>`;root.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>mission(b.dataset.mission));}
 function success(id,message){const first=!VJLearning.read()[id];const ok=VJLearning.complete(id);q('[data-feedback]').textContent=`✓ ${message} ${ok?(first?'Progression ajoutée à ta carrière.':'Exercice validé à nouveau.'): 'La progression n’a pas pu être sauvegardée.'}`;if(!q('[data-hub]')){const b=document.createElement('button');b.dataset.hub='';b.textContent='Voir la suite du parcours';b.onclick=hub;root.append(b);}}
 function draw(){const c=q('canvas').getContext('2d');c.fillStyle='#111d2d';c.fillRect(0,0,800,450);c.strokeStyle='#f8bd73';c.lineWidth=4;c.setLineDash([8,6]);c.strokeRect(200,100,400,250);c.setLineDash([]);if(connected){const w=400*size/100,cx=400+x;c.fillStyle='#6ee5d1';c.beginPath();c.moveTo(cx-w/2+skew,225-125*size/100);c.lineTo(cx+w/2-skew,225-125*size/100);c.lineTo(cx+w/2,225+125*size/100);c.lineTo(cx-w/2,225+125*size/100);c.closePath();c.fill();c.fillStyle='#15263c';c.font='24px Arial';c.fillText('PROGRAMME',cx-78,232);}c.fillStyle='white';c.font='18px Arial';c.fillText(connected?'Signal reçu · cadre pointillé = cible':'Aucun signal : vérifie la sortie et le câble',24,410);}
 function mission(id){active=id;if(id==='mix'||id==='energy'){close();document.querySelector('#academy-launch').click();return;}if(id==='contract'){close();if(!profile.created){showScreen('creator');notify('Crée ton VJ pour conserver ce premier contrat dans une carrière.');return;}showScreen('desktop');openApp('booking');notify('Choisis un petit contrat accessible, postule, attends la réponse puis prépare le show le jour venu.');return;}shell(missions.find(m=>m[0]===id)[1]);
  if(id==='wall'){connected=false;x=70;size=70;skew=25;q('[data-content]').innerHTML=`<p>La technicienne a branché un projecteur HDMI. Envoie le programme à cette sortie, puis remplis le cadre sans déborder.</p><canvas width="800" height="450" aria-label="Projection et cadre cible"></canvas><div class="field-controls"><label>Sortie<select data-output><option value="internal">Écran du laptop seulement</option><option value="hdmi">HDMI · programme externe</option></select></label><button data-connect>Brancher le câble HDMI</button>${[['x','Position horizontale',-100,100,70],['size','Taille',50,120,70],['skew','Trapèze',-45,45,25]].map(([k,label,min,max,v])=>`<label>${label} <output data-value="${k}">${v}</output><input data-adjust="${k}" aria-label="${label}" type="range" min="${min}" max="${max}" value="${v}"></label>`).join('')}<button data-check>Tester la projection</button></div>`;let cable=false;const signal=()=>{connected=cable&&q('[data-output]').value==='hdmi';draw();};q('[data-output]').onchange=signal;q('[data-connect]').onclick=()=>{cable=!cable;q('[data-connect]').textContent=cable?'Débrancher le câble HDMI':'Brancher le câble HDMI';signal();};root.querySelectorAll('[data-adjust]').forEach(e=>e.oninput=()=>{const v=Number(e.value);if(e.dataset.adjust==='x')x=v;if(e.dataset.adjust==='size')size=v;if(e.dataset.adjust==='skew')skew=v;q(`[data-value="${e.dataset.adjust}"]`).textContent=v;draw();});q('[data-check]').onclick=()=>{if(!connected)q('[data-feedback]').textContent='Le mur ne reçoit aucun signal. Il faut le câble ET la sortie HDMI programme.';else if(Math.abs(skew)>4)q('[data-feedback]').textContent='Le signal arrive, mais le haut de l’image est déformé. Corrige le trapèze.';else if(Math.abs(x)>8||Math.abs(size-100)>3)q('[data-feedback]').textContent='Le trapèze est corrigé. Ajuste la position et la taille.';else success(id,'Tu as rétabli le signal et cadré le mur.');};draw();}
  if(id==='cable'){q('[data-content]').innerHTML=`<p>Le chemin sécurisé jusqu’au projecteur mesure <strong>6 m</strong>. Ton câble mesure <strong>3 m</strong>. Budget dépannage : <strong>40 $</strong>.</p><div class="field-cards"><button data-choice="short">Garder le câble de 3 m · 0 $</button><button data-choice="safe">Louer le câble testé de 8 m et fixer le passage · 25 $</button><button data-choice="move">Déplacer la régie dans le passage du public · 0 $</button><button data-choice="over">Louer une liaison optique de 20 m · 90 $</button></div>`;root.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const v=b.dataset.choice;if(v==='safe')success(id,'La liaison atteint le projecteur et le passage est sécurisé.');else q('[data-feedback]').textContent=v==='short'?'Il manque 3 m.':v==='move'?'Tu bloques la circulation du public.':'Cette solution dépasse le budget.';});}
  if(id==='client'){clarified=false;q('[data-content]').innerHTML=`<p>Le client demande « plus intense ». La chanteuse doit rester visible.</p><button data-ask>Demander : plus lumineux, plus rapide ou plus contrasté ?</button><p data-answer>Clarifie la demande avant de changer la sortie.</p><canvas data-client-preview width="800" height="350"></canvas><div class="field-controls"><label>Intensité<input data-power type="range" min="0" max="100" value="45"></label><label>Couches visibles<select data-layers><option>1</option><option>2</option><option>5</option></select></label><label>Palette<select data-palette><option value="warm">Ambre et violet</option><option value="all">Toutes les couleurs</option></select></label><button data-client-test>Proposer ce réglage</button></div>`;q('[data-ask]').onclick=()=>{clarified=true;q('[data-answer]').textContent='Client : « Plus présent, mais pas de flash. Gardons ambre et violet. »';};const previewClient=()=>{const c=q('[data-client-preview]').getContext('2d'),power=Number(q('[data-power]').value)/100,n=Number(q('[data-layers]').value);c.fillStyle='#0b1425';c.fillRect(0,0,800,350);c.globalAlpha=power;for(let i=0;i<n*6;i++){c.strokeStyle=q('[data-palette]').value==='warm'?(i%2?'#ae89ef':'#ffc185'):`hsl(${i*47},80%,65%)`;c.lineWidth=8;c.beginPath();c.ellipse(400,175,90+i*12,35+i*8,i*.14,0,Math.PI*2);c.stroke();}c.globalAlpha=1;};root.querySelectorAll('[data-power],[data-layers],[data-palette]').forEach(e=>e.addEventListener('input',previewClient));previewClient();q('[data-client-test]').onclick=()=>{const power=Number(q('[data-power]').value);if(!clarified)q('[data-feedback]').textContent='Pose d’abord une question courte au client.';else if(power<55||power>75||Number(q('[data-layers]').value)>2||q('[data-palette]').value!=='warm')q('[data-feedback]').textContent='Respecte le brief : 55–75 %, maximum deux couches, ambre et violet.';else success(id,'Tu as clarifié la demande et respecté le compromis.');};}
 }
 button.onclick=()=>{root.hidden=false;hub();q('[data-exit]').focus();};root.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const a=[...root.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus();}}});
 window.addEventListener('vj-learning',()=>{if(typeof renderCareerCompass==='function')renderCareerCompass();});
})();
