window.God99SceneEditor=(()=>{
 const KEY='hyyu-god99-scenes';
 const group=new THREE.Group();group.name='GOD99 editor';scene.add(group);
 let open=false,selected=null,restored=false;
 const q=(s,p=document)=>p.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
 const vjName=()=>String(profile?.vjName||profile?.name||profile?.displayName||profile?.character?.name||q('#vj-name')?.value||'');
 const allowed=()=>/god\s*99/i.test(vjName());
 const walking=()=>document.body.classList.contains('studio-world-view');
 const base=[['god-cube','Bloc','Structure'],['god-platform','Plateforme','Structure'],['god-wall','Mur / panneau','Structure'],['god-pillar','Poteau','Structure'],['god-light','Lampe','Lumière']];
 function catalog(){
  const out=base.map(([id,label,category])=>({id,label,category,primitive:true})),seen=new Set(out.map(x=>x.id));
  if(typeof shopItems!=='undefined'&&Array.isArray(shopItems)&&window.ItemModels?.create)for(const item of shopItems){if(item?.id&&!seen.has(item.id)&&!['vjloop','housing'].includes(item.category)){seen.add(item.id);out.push({id:item.id,label:item.label||item.id,category:item.category||item.type||'Jeu',item});}}
  if(Array.isArray(window.God99EditorObjects))for(const item of window.God99EditorObjects){if(item?.id&&!seen.has(item.id)){seen.add(item.id);out.push(item);}}
  return out;
 }
 function primitive(id){const m=new THREE.MeshStandardMaterial({color:0x6d777d,roughness:.75,metalness:.1});if(id==='god-platform')return new THREE.Mesh(new THREE.BoxGeometry(2.4,.18,1.6),m);if(id==='god-wall')return new THREE.Mesh(new THREE.BoxGeometry(2.8,2.4,.16),m);if(id==='god-pillar')return new THREE.Mesh(new THREE.BoxGeometry(.35,2.5,.35),m);if(id==='god-light'){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CylinderGeometry(.15,.2,.28,16),m),l=new THREE.PointLight(0xffddb0,1.2,6);b.rotation.x=Math.PI/2;l.position.y=.2;g.add(b,l);return g;}return new THREE.Mesh(new THREE.BoxGeometry(1,1,1),m);}
 function make(id){const entry=catalog().find(x=>x.id===id);if(!entry)return null;let o=null;try{o=entry.primitive?primitive(id):entry.item?ItemModels.create(entry.item):typeof entry.create==='function'?entry.create():null;}catch(e){console.warn(e);}if(!o)return null;o.userData.god99=true;o.userData.editorId=id;o.userData.editorLabel=entry.label||id;o.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});return o;}
 function spawn(){const d=new THREE.Vector3();camera.getWorldDirection(d);const p=camera.position.clone().add(d.multiplyScalar(2.3));return new THREE.Vector3(clamp(p.x,-5.9,5.9),.2,clamp(p.z,4.8,13.1));}
 function floor(o){o.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(o);if(Number.isFinite(b.min.y))o.position.y+=.17-b.min.y;}
 function add(id,data){const o=make(id);if(!o){notify?.('Objet indisponible.');return;}group.add(o);if(data){o.position.set(Number(data.x)||0,Number(data.y)||.17,Number(data.z)||8);o.rotation.y=Number(data.r)||0;o.scale.setScalar(Math.max(.02,Number(data.s)||1));}else{o.position.copy(spawn());floor(o);}pick(o);autosave();}
 function rec(o){return{id:o.userData.editorId,x:+o.position.x.toFixed(3),y:+o.position.y.toFixed(3),z:+o.position.z.toFixed(3),r:+o.rotation.y.toFixed(4),s:+o.scale.x.toFixed(3)};}
 function sceneData(name){return{version:1,name:name||q('#god-scene-name')?.value||'Garage GOD99',objects:group.children.filter(o=>o.userData.god99).map(rec)};}
 function dispose(o){o.traverse(n=>{n.geometry?.dispose?.();if(n.material){(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>m.dispose?.());}});}
 function clear(){pick(null);for(const o of [...group.children]){group.remove(o);dispose(o);}}
 function apply(data){if(!Array.isArray(data?.objects))return false;clear();for(const r of data.objects)add(r.id,r);if(data.name&&q('#god-scene-name'))q('#god-scene-name').value=data.name;autosave();return true;}
 function store(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{return{};}}
 function refreshSaved(){const s=q('#god-scenes');if(!s)return;const names=Object.keys(store());s.innerHTML=names.length?names.map(n=>`<option>${n.replace(/[<&]/g,'')}</option>`).join(''):'<option value="">Aucune scène</option>';}
 function autosave(){try{localStorage.setItem(KEY+':auto',JSON.stringify(sceneData('Autosave GOD99')));}catch{}}
 function save(){const name=(q('#god-scene-name')?.value||'Garage GOD99').trim(),all=store();all[name]=sceneData(name);localStorage.setItem(KEY,JSON.stringify(all));refreshSaved();notify?.(`Scène ${name} sauvegardée.`);}
 function load(){const d=store()[q('#god-scenes')?.value];if(d&&apply(d))notify?.(`Scène ${d.name} chargée.`);}
 function exportJson(){const d=sceneData(),blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(d.name||'god99-scene').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async function importJson(file){try{const d=JSON.parse(await file.text());if(!apply(d))throw new Error();notify?.('Scène importée.');}catch{notify?.('Fichier JSON invalide.');}}
 const panel=document.createElement('section');panel.id='god99-editor';panel.hidden=true;panel.innerHTML=`<div class="god-shell"><header><div><small>GOD99</small><h2>Éditeur de scène</h2></div><button data-close>×</button></header><div class="god-bar"><input id="god-search" placeholder="Chercher un objet"><select id="god-cat"><option value="all">Tous</option></select><input id="god-scene-name" value="Garage GOD99"><button data-save>Sauvegarder</button><button data-load>Charger</button><select id="god-scenes"></select><button data-export>Exporter JSON</button><label>Importer<input data-import type="file" accept=".json,application/json"></label></div><main><div class="god-library" data-library></div><aside><p data-empty>Sélectionne ou ajoute un objet.</p><div data-fields hidden><h3 data-title></h3><label>X<input data-p="x" type="number" step=".1"></label><label>Y<input data-p="y" type="number" step=".1"></label><label>Z<input data-p="z" type="number" step=".1"></label><label>Rotation<input data-p="r" type="number" step="5"></label><label>Échelle<input data-p="s" type="number" step=".05"></label><button data-floor>Au sol</button><button data-copy>Dupliquer</button><button data-delete>Supprimer</button><small>Flèches : déplacer · Q/E : tourner · D : dupliquer · Suppr : supprimer</small></div></aside></main></div>`;document.body.append(panel);
 const style=document.createElement('style');style.textContent=`#god99-editor{position:fixed;inset:55px 20px 20px;z-index:1500;color:#eafbf8;font-family:Arial}#god99-editor[hidden]{display:none}.god-shell{height:100%;display:grid;grid-template-rows:auto auto 1fr;background:#07141bf4;border:1px solid #31717a;border-radius:12px;overflow:hidden;box-shadow:0 30px 90px #000c}.god-shell header{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;background:#0d222b;border-bottom:1px solid #24505a}.god-shell header h2{margin:2px 0}.god-shell header small{color:#54e7d8;font-weight:900}.god-shell button,.god-shell input,.god-shell select,.god-shell label{background:#102a33;color:white;border:1px solid #315b65;border-radius:5px;padding:7px}.god-shell button,.god-shell label{cursor:pointer}.god-bar{display:flex;gap:7px;flex-wrap:wrap;padding:9px;border-bottom:1px solid #20444c}.god-bar label input{display:none}.god-shell main{display:grid;grid-template-columns:1fr 290px;min-height:0}.god-library{padding:10px;overflow:auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));align-content:start;gap:7px}.god-library button{text-align:left;min-height:55px}.god-shell aside{padding:12px;background:#0b1b22;overflow:auto}.god-shell aside label{display:grid;grid-template-columns:75px 1fr;align-items:center;margin:6px 0}.god-shell aside input{width:100%;box-sizing:border-box}.god-shell aside button{margin:4px 2px}.god-shell aside small{display:block;margin-top:10px;color:#8da9ae;line-height:1.4}@media(max-width:800px){#god99-editor{inset:8px}.god-shell main{grid-template-columns:1fr}.god-shell aside{max-height:40vh}}`;document.head.append(style);
 function render(){const all=catalog(),search=q('#god-search').value.toLowerCase(),cat=q('#god-cat').value,cats=[...new Set(all.map(x=>x.category))],old=cat;q('#god-cat').innerHTML='<option value="all">Tous</option>'+cats.map(c=>`<option>${String(c).replace(/[<&]/g,'')}</option>`).join('');if([...q('#god-cat').options].some(o=>o.value===old))q('#god-cat').value=old;const host=q('[data-library]',panel);host.replaceChildren();for(const item of all.filter(x=>(cat==='all'||x.category===cat)&&(!search||(x.label+' '+x.id).toLowerCase().includes(search)))){const b=document.createElement('button');b.innerHTML=`<b>${item.label}</b><br><small>${item.category}</small>`;b.onclick=()=>add(item.id);host.append(b);}}
 function pick(o){selected=o&&o.parent===group?o:null;q('[data-empty]',panel).hidden=!!selected;q('[data-fields]',panel).hidden=!selected;if(!selected)return;q('[data-title]',panel).textContent=selected.userData.editorLabel||selected.userData.editorId;sync();}
 function sync(){if(!selected)return;q('[data-p=x]',panel).value=selected.position.x.toFixed(2);q('[data-p=y]',panel).value=selected.position.y.toFixed(2);q('[data-p=z]',panel).value=selected.position.z.toFixed(2);q('[data-p=r]',panel).value=THREE.MathUtils.radToDeg(selected.rotation.y).toFixed(1);q('[data-p=s]',panel).value=selected.scale.x.toFixed(2);}
 panel.querySelectorAll('[data-p]').forEach(i=>i.oninput=()=>{if(!selected)return;const v=Number(i.value);if(!Number.isFinite(v))return,p=i.dataset.p;if(p==='x')selected.position.x=clamp(v,-6.1,6.1);if(p==='y')selected.position.y=clamp(v,-1,8);if(p==='z')selected.position.z=clamp(v,4.4,13.45);if(p==='r')selected.rotation.y=THREE.MathUtils.degToRad(v);if(p==='s')selected.scale.setScalar(clamp(v,.02,20));autosave();});
 function remove(){if(!selected)return;const o=selected;pick(null);group.remove(o);dispose(o);autosave();}
 function copy(){if(!selected)return;const d=rec(selected);add(d.id,{...d,x:d.x+.4,z:d.z+.4});}
 function toggle(value=!open){if(value&&!allowed()){notify?.('Utilise le VJ GOD99 pour ouvrir cet éditeur.');return;}open=!!value;panel.hidden=!open;if(open){render();refreshSaved();}else pick(null);}
 q('[data-close]',panel).onclick=()=>toggle(false);q('[data-save]',panel).onclick=save;q('[data-load]',panel).onclick=load;q('[data-export]',panel).onclick=exportJson;q('[data-import]',panel).onchange=e=>{if(e.target.files?.[0])importJson(e.target.files[0]);e.target.value='';};q('[data-floor]',panel).onclick=()=>{if(selected){floor(selected);sync();autosave();}};q('[data-copy]',panel).onclick=copy;q('[data-delete]',panel).onclick=remove;q('#god-search').oninput=render;q('#god-cat').onchange=render;
 canvas.addEventListener('pointerup',e=>{if(!open||e.button!==0)return;const r=canvas.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hit=ray.intersectObjects(group.children,true)[0];if(!hit){pick(null);return;}let o=hit.object;while(o&&o.parent!==group)o=o.parent;pick(o?.parent===group?o:null);},true);
 window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select'))return;if(!e.repeat&&(e.key==='x'||e.key==='X')&&allowed()&&walking()){e.preventDefault();e.stopImmediatePropagation();toggle();return;}if(!open||!selected)return;const key=e.key.toLowerCase(),step=e.shiftKey?0.5:0.1;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();return;}if(key==='d'){e.preventDefault();copy();return;}if(key==='q')selected.rotation.y+=THREE.MathUtils.degToRad(5);else if(key==='e')selected.rotation.y-=THREE.MathUtils.degToRad(5);else if(e.key==='ArrowLeft')selected.position.x-=step;else if(e.key==='ArrowRight')selected.position.x+=step;else if(e.key==='ArrowUp')selected.position.z-=step;else if(e.key==='ArrowDown')selected.position.z+=step;else return;e.preventDefault();sync();autosave();},true);
 function tick(){if(open&&(!allowed()||!walking()))toggle(false);group.visible=allowed()&&walking();if(!restored&&allowed()&&profile?.created){restored=true;try{const d=JSON.parse(localStorage.getItem(KEY+':auto')||'null');if(d?.objects?.length)apply(d);}catch{}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 return{group,toggle,add,sceneData,apply,allowed,get open(){return open;}};
})();
