/* Master v4 rules: cumulative contracts, small clothing bonuses and an affordable library. */
window.PhysicalCareer=(()=>{
 const C=PhysicalCore;
 const venues=['Garage de quartier','Petit café','Bar local','Salle communautaire','Petit club','Loft','Club principal','Warehouse','Galerie','Atelier mapping','Salle spectacle','Corporate hall','Festival secondaire','Extérieur / scène temporaire','Festival principal'];
 const rows=[
 ['Projection legacy',0,'VGA',1,0,70,'Connexion, alimentation, input VGA et keystone'],['Placement legacy',1,'VGA',1,0,85,'Déplacer et orienter le projecteur'],['Test legacy',0,'VGA',1,480,105,'Installer la même chaîne sous un chrono doux'],
 ['Passage HDMI',2,'HDMI',1,0,110,'Choisir les connecteurs et input HDMI'],['Même image, deux écrans',3,'HDMI',2,0,135,'Distribuer le même signal avec un splitter'],['Rush HDMI',2,'HDMI',2,600,160,'Diagnostiquer un mauvais input sous chrono'],
 ['Premier micro',4,'HDMI',1,0,150,'Micro → XLR → console et test du vumètre'],['Micro capricieux',4,'HDMI',1,0,180,'Diagnostiquer longueur et input XLR'],['Installation événement',3,'HDMI',2,720,210,'Installer vidéo et micro sous chrono'],
 ['Deux sorties indépendantes',5,'HDMI',2,0,190,'Utiliser deux sorties réelles, sans duplication'],['Projecteur en hauteur',6,'HDMI',2,0,230,'Poser sur support et sécuriser la fixation'],['Multi-projection rush',6,'HDMI',2,660,280,'Configurer les sorties et la hauteur sous chrono'],
 ['Première longue distance',7,'SDI',1,0,250,'HDMI → SDI → HDMI et boîtes alimentées'],['Sens de conversion',7,'SDI',2,0,300,'Choisir le bon sens de conversion'],['Diagnostic SDI',10,'SDI',2,780,360,'Vérifier alimentation, input et micro'],
 ['Mapping carré',8,'SDI',1,0,300,'Créer et fermer quatre points'],['Mapping triangle',8,'SDI',1,0,360,'Créer trois sommets dans le bon ordre'],['Mapping rond',5,'SDI',1,840,430,'Tracer le contour courbe'],
 ['Deux formes',9,'SDI',1,0,420,'Mapper séparément deux surfaces'],['Deux projecteurs mappés',10,'SDI',2,0,500,'Régler deux sorties et deux mappings'],['Étoile sous pression',6,'SDI',2,720,580,'Tracer sommets et creux de l’étoile'],
 ['Première tour',11,'SDI',3,0,550,'Tour, GPU, moniteur, clavier et souris'],['Régie pro',12,'SDI',4,900,700,'Distribution SDI, sécurité et diagnostic'],['Grande finale chapitre 1',14,'SDI',4,1080,900,'Installer et tester la chaîne complète']];
 function contracts(){return rows.map((r,i)=>{const n=i+1,t=Math.floor(i/3),mapping=n>=16;return{id:'physical-gig-'+String(n).padStart(2,'0'),physical:true,number:n,title:r[0],venue:venues[r[1]],venueFamily:['garage','bar','bar','hall','club','loft','club','warehouse','gallery','lab','hall','hall','festival','street','festival'][r[1]],standard:r[2],projectorCount:r[3],timeLimitSeconds:r[4],budget:r[5],baseBudget:r[5],contractBudget:r[5],requirement:r[6],type:['VGA','HDMI','Micro XLR','Sorties indépendantes','SDI','Mapping manuel','Multi-mapping','Régie complète'][t],style:n>=22?'techno':['techno','chill','hiphop','psytrance','rock'][t%5],minRep:0,minScore:70,minGear:'starter',requiredSkills:{},requiredAccessories:[],requiredLoopPacks:n<3?0:n===3?1:n<9?2:n<15?3:n<20?4:n<23?5:6,zoneShape:n===17?'triangle':n===18?'rond':n===21?'etoile':n===19||n===24?'mixte':'rectangle',zoneCount:n===19?2:n===24?6:r[3],zoneLabel:mapping?'Contours à tracer':r[3]+' écran(s)',maskRequired:mapping?70:0,status:n===1?'open':'locked',lockedDepth:false,lockedHorizontal:false,eventDay:0,scheduledDay:null,responseIn:null,cooldownDays:0,rentalRule:'location',allowRent:true,loanerGear:false,skillText:'Apprentissage en gig',gearText:r[6],timerLabel:r[4]?r[4]/60+' min':'non',micro:[7,8,9,15,22,23,24].includes(n),independent:[10,11,12,20,21,22,24].includes(n),height:[11,12,23,24].includes(n),dress:n===22?'pro':n>=23?'safety':'',styleClipMinimum:n>=23?6:n===22?5:n>=4&&n<=6?2:0,clipMinimum:n<3?0:n===3?1:n<9?2:n<15?3:n<20?4:n<23?5:6};});}
 const clothing={ 'pin-vj':[15,1,0,1],'beanie-black':[25,1,0,0],'cap-low':[30,2,0,0],'gloves-stage':[35,1,1,0],'hoodie-vj':[55,3,0,0],'pants-cargo':[60,2,1,0],'shoes-cyan':[55,3,0,0],'shoes-magenta':[60,3,0,0],'mask-club':[70,4,0,1],'jacket-blackout':[80,3,2,0],'jacket-reflective':[95,1,3,0],'pants-tech':[95,4,1,0],'headphones-basic':[50,1,1,0],'headphones-pro':[140,2,2,0],'coat-tour':[130,4,3,1],'vest-led':[180,6,0,1],'full-fit-pro':[250,6,4,2]};
 const clipPrices=[20,21,24,28,30,25,23,34,31,27,35,35,26,24,25,29,33];
 function catalog(){
  for(const [id,d] of Object.entries(C.definitions)){if(id==='venue-outlet')continue;let item=shopItems.find(i=>i.id===id);if(!item){const type=id.split('-')[0];item={id,type,category:'gear',label:d.label||id,description:'',stackable:true,stats:{},tags:[],advantages:[],disadvantages:[],apply:()=>{}};shopItems.push(item);}item.cost=d.price??item.cost;item.label=d.label||item.label;item.physical=d;item.stackable=true;item.stats={};item.scoreBonus=0;item.description=`${d.quality} · ${d.weightKg} kg · ${d.volumeUnits} unités. ${d.length?d.length+' m · ':''}${d.ports.map(p=>p.standard+' '+p.direction.toUpperCase()).join(' / ')}${d.capacityVolume?'Contenant : '+d.capacityVolume+' unités / '+d.capacityKg+' kg.':''}`;if(['laptop','tower','projector'].includes(d.kind))item.description+=' Inclus : multiprise, câble secteur et rallonge pour le mur.';item.advantages=[d.kind==='laptop'?'Clavier et trackpad intégrés':d.kind==='tower'?'GPU remplaçable':d.length?d.length+' m de portée':d.capacityVolume?d.capacityVolume+' unités de transport':d.quality];item.disadvantages=[d.kind==='tower'?'Moniteur, clavier, souris et câbles requis':d.unlock?'Après gig '+d.unlock:'Capacité physique limitée'];item.effectScope=d.kind==='gaffer'?'En main, clique un câble branché pour le fixer. Prends le câble pour retirer le gaffer.':d.kind==='lens'?'En main, clique un projecteur éteint. Agrandit physiquement l’image de 25 %.':d.kind==='marker-kit'?'En main, clique un écran. Les repères aident à placer tes points près du contour, sans les tracer automatiquement.':'Les ports, la longueur, le poids et l’alimentation déterminent son utilisation.';}

  for(const i of shopItems){if(i.category==='clothing'){const v=clothing[i.id.replace('clothing-','')];if(v){i.cost=v[0];i.stats={style:v[1],reputation:v[2],network:v[3]};i.physicalWear={style:v[1],pro:v[2],network:v[3],safety:i.id==='clothing-jacket-reflective'};i.effectScope='Tenue portée plafonnée à 12 Style, 5 Pro, 3 Réseau. Aucun effet sur le signal.';}}
   if(i.category==='vjloop'){const ix=shopItems.filter(x=>x.category==='vjloop').indexOf(i),n=Number(i.id.match(/-(\d+)-/)?.[1]||1),tier=1+Math.floor(((n-1)%15)/3);i.cost=ix<17?clipPrices[ix]:20+Math.round(((n-1)%15)*15/14);i.visualPoints=ix<17?Math.max(1,Math.min(5,Math.ceil((i.cost-19)/3.2))):tier;i.visualPoints=i.cost<=22?1:i.cost<=25?2:i.cost<=28?3:i.cost<=32?4:5;i.stats={};i.tags=[getStyleMeta(i.styleTarget).label,i.visualPoints<3?'warm-up / groove':i.visualPoints<5?'montée / géométrique':'peak / abstrait'];i.effectScope='Contenu sélectionné avant le départ et projeté automatiquement. Score bibliothèque plafonné à 20.';i.disadvantages=['Aucun effet sur la connectique'];}
   i.physicalDisabled=i.type==='console'||['accessory-mini-controller','router-mapper-triple','cable-loom-3pack-75','cable-loom-3pack-150','adapter-dp-hdmi-pro-3pack'].includes(i.id);
  }
  for(const [id,price] of [['accessory-gaff-pocket',18],['accessory-mapping-kit',85]]){const i=shopItems.find(x=>x.id===id);if(i)i.cost=price;}
 }
 function completed(){return profile.physical?.completed||[];}
 function blocked(g){if(profile.godMode||g.number===1||completed().includes(g.number-1))return '';return 'Réussir la gig '+(g.number-1)+' à 70/100.';}
 function wear(){const all=Object.values(profile.equippedWear||{}).map(id=>shopItems.find(i=>i.id===id)?.physicalWear).filter(Boolean);return{style:Math.min(12,all.reduce((n,x)=>n+x.style,0)),pro:Math.min(5,all.reduce((n,x)=>n+x.pro,0)),network:Math.min(3,all.reduce((n,x)=>n+x.network,0)),safety:all.some(x=>x.safety)};}
 function clipScore(g){const selected=profile.physical?.selectedClips||[];const items=selected.map(id=>shopItems.find(i=>i.id===id)).filter(i=>i&&profile.ownedItems.includes(i.id));const matching=items.filter(i=>i.styleTarget===g.style);return{count:items.length,matching:matching.length,score:Math.min(20,matching.reduce((n,i)=>n+i.visualPoints,0))};}
 function migrate(){if(!profile?.created)return null;if(!profile.physical){profile.physicalLegacy={gigs:structuredClone(profile.gigs),activeRun:profile.activeRun?structuredClone(profile.activeRun):null,preparedDeparture:profile.preparedDeparture||null};profile.physical=C.create();profile.gigs=contracts();profile.activeRun=null;delete profile.preparedDeparture;for(const id of ['projector-cheap','computer-starter-laptop','cable-vga-3','surface-square','bag-messenger-basic','clip-starter-loop']){if(!profile.ownedItems.includes(id))profile.ownedItems.push(id);if(id!=='clip-starter-loop')profile.inventory[id]=Math.max(1,profile.inventory[id]||0);}profile.physical.selectedClips=['clip-starter-loop'];}
  if(!profile.physical.studioCart){const id='support-studio-cart',old=profile.physical.starterStand&&profile.physical.objects.find(o=>o.modelId==='support-stand'&&o.owner==='player');if(old&&!profile.physical.active){old.modelId=id;profile.inventory['support-stand']=Math.max(0,(profile.inventory['support-stand']||1)-1);if(!profile.inventory['support-stand'])profile.ownedItems=profile.ownedItems.filter(x=>x!=='support-stand');old.location='shelf';}if(!profile.ownedItems.includes(id))profile.ownedItems.push(id);profile.inventory[id]=Math.max(1,profile.inventory[id]||0);profile.physical.studioCart=true;}
  if(!profile.physical.starterAudio){for(const id of ['audio-speakers-basic','cable-audio-3']){if(!profile.ownedItems.includes(id))profile.ownedItems.push(id);profile.inventory[id]=Math.max(1,profile.inventory[id]||0);}profile.physical.starterAudio=true;for(const o of profile.physical.objects){if(C.spec(o.modelId).kind==='powerbar')o.powerOn=true;if(['laptop','tower'].includes(C.spec(o.modelId).kind)&&!o.ports.some(p=>p.id==='audio'))o.ports.push(C.port('audio','AUX','out'));if(o.modelId==='projector-cheap'&&!profile.physical.links.some(l=>[l.a,l.b].some(e=>e.device===o.uid&&e.port==='hdmi')))o.ports=o.ports.filter(p=>p.id!=='hdmi');}}
  for(const g of profile.gigs){if(!g.physical)continue;g.budget=rows[g.number-1][5];g.contractBudget=g.budget;g.baseBudget=g.budget;const required=contracts().find(x=>x.number===g.number);g.clipMinimum=required.clipMinimum;g.requiredLoopPacks=required.requiredLoopPacks;g.styleClipMinimum=required.styleClipMinimum;if(['open','locked'].includes(g.status))g.status=blocked(g)?'locked':'open';}
  return profile.physical;
 }
 function unlockItem(item){if(!item.physical)return '';const n=item.physical.unlock||0;return n&&!completed().includes(n)&&!profile.godMode?'Débloqué après la gig '+n+'.':'';}
 let guidePage=1;
 function guide(){appWindow.innerHTML=`<div class="app-heading"><div><h1>Guide officiel · Refonte physique v4</h1><p>Document fourni par Cindy · 17 pages · référence du gameplay.</p></div></div><details style="margin:12px 0"><summary>Bien démarrer : ranger, poser et brancher</summary><ol><li>Le bureau commence vide. Prends le laptop sur l’étagère et les câbles au mur.</li><li>Clique un objet, puis E pour le prendre. Molette ou les boutons : hauteur. R / Maj+R : tourner. Glisse la souris pour regarder à 360°.</li><li>Descends jusqu’au support : le contour devient vert. E ou Poser le dépose. Échap annule.</li><li>Le rack existant porte le projecteur. Prendre le rack déplace les deux ; prendre le projecteur les sépare. Débranche avant de déplacer.</li><li>Prends une rallonge : clique la prise murale puis l’entrée de la multiprise. Le câble secteur relie la multiprise au laptop ou au projecteur.</li><li>Relie VGA OUT du laptop à VGA IN du projecteur, puis allume avec P. Place l’écran devant l’objectif.</li><li>Les petits haut-parleurs utilisent la sortie audio jack du laptop. Clique un sac fermé pour l’ouvrir, puis reclique pour ranger l’objet en main.</li></ol></details><div class="row-actions"><a href="./documentation/references/VJ_Simulator_Game_Design_Master_Refonte_Physique_v4.pdf" target="_blank" rel="noopener">Ouvrir le PDF original</a><button data-guide-prev ${guidePage===1?'disabled':''}>←</button><label>Page <select data-guide-page>${Array.from({length:17},(_,i)=>`<option ${i+1===guidePage?'selected':''}>${i+1}</option>`).join('')}</select> / 17</label><button data-guide-next ${guidePage===17?'disabled':''}>→</button></div><img style="display:block;width:100%;height:auto;margin:16px auto;max-width:1000px" src="./documentation/physical-v4/pages/page-${String(guidePage).padStart(2,'0')}.png" alt="Page ${guidePage} du Game Design Master v4"><p><a href="./documentation/physical-v4/apercu.html" target="_blank" rel="noopener">Captures et vérifications de la refonte</a> · <a href="./documentation/physical-v4/IMPLEMENTATION.md" target="_blank" rel="noopener">Suivi d’implémentation</a></p>`;appWindow.querySelector('[data-guide-prev]').onclick=()=>{guidePage--;guide();};appWindow.querySelector('[data-guide-next]').onclick=()=>{guidePage++;guide();};appWindow.querySelector('[data-guide-page]').onchange=e=>{guidePage=Number(e.target.value);guide();};addWindowControls();}
 function skills(){const lessons=[['VGA et alimentation',1,3,'Prends le câble, clique la sortie VGA puis l’entrée VGA. Branche le secteur, allume les appareils et choisis le bon input.'],['HDMI et splitter',4,6,'Une sortie vers deux écrans donne la même image. Un splitter ne crée pas de sortie indépendante.'],['Micro et XLR',7,9,'Relie le micro à la console alimentée. Choisis XLR puis utilise le test du micro pour contrôler le vumètre.'],['Sorties indépendantes',10,12,'Chaque image indépendante exige une sortie vidéo distincte. Pose les projecteurs en hauteur sur leurs supports.'],['SDI et conversion',13,15,'Respecte le sens HDMI vers SDI puis SDI vers HDMI. Les boîtiers actifs ont besoin de courant.'],['Mapping manuel',16,21,'Après le câblage et le cadrage, active la plume. Place et ferme toi-même les points sur chaque contour.'],['Tour complète',22,24,'Installe le GPU dans la tour éteinte. Apporte aussi le moniteur, le clavier, la souris et tous leurs câbles.']];appWindow.innerHTML=`<div class="app-heading"><div><h1>VJ School & Skills</h1><p>Apprends dans le garage, puis valide tes installations en gig. Les appareils et les branchements sont les mêmes.</p></div></div><div class="shop-grid skills-grid">${lessons.map(([name,start,end,description])=>{const count=completed().filter(n=>n>=start&&n<=end).length,total=end-start+1;return `<article class="shop-card"><div class="shop-card-body"><h2>${name}</h2><p>${description}</p><p>Gigs ${start}–${end} · ${count}/${total} réussies</p><div class="progress"><span style="width:${count/total*100}%"></span></div><button data-physical-practice>Pratiquer dans le garage</button></div></article>`;}).join('')}</div>`;appWindow.querySelectorAll('[data-physical-practice]').forEach(b=>b.onclick=()=>{if(profile.physical.active){notify('Reprends ou termine ton installation en pause.');return;}StudioWorld.enter();notify('Clique un objet, E pour le porter, puis clique la table pour le poser.');});}
 function stats(){const scores=profile.physical.scores||{},names={TEC:['Technique','Cadrage et keystone'],SIG:['Signal','Chaînes vidéo fonctionnelles'],MAP:['Mapping','Précision des contours tracés'],AUD:['Audio','Test micro · maximum 50'],PRO:['Professionnalisme','Tenue, sécurité et respect du temps'],STYLE:['Style','Tenue et clips compatibles'],NET:['Réseau','Installations réussies et tenue']},w=wear();appWindow.innerHTML=`<div class="app-heading"><div><h1>Progression des installations</h1><p>${completed().length}/24 gigs réussies · ${Math.round(profile.money)} $ · les scores proviennent de tes installations.</p></div></div><div class="stats-grid">${Object.entries(names).map(([key,[name,help]])=>statCard(name,scores[key]||0,help)).join('')}</div><p>Tenue portée : ${w.style}/12 Style · ${w.pro}/5 Pro · ${w.network}/3 Réseau. Les points ne remplacent pas le matériel requis.</p>`;}
 catalog();return{contracts,venues,migrate,blocked,wear,clipScore,unlockItem,guide,skills,stats};
})();
