/* Physical simulation without rendering dependencies. Distinct instances own every connection. */
(function(root){
 'use strict';
 const distance=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0),(a.z||0)-(b.z||0));
 const port=(id,standard,direction,extra={})=>({id,standard,direction,...extra});
 const power=()=>port('power','IEC','in');
 const videoOut=(standard,id=standard.toLowerCase())=>port(id,standard,'out');
 const videoIn=(standard,id=standard.toLowerCase())=>port(id,standard,'in');
 const usb=()=>[port('usb1','USB','out'),port('usb2','USB','out'),port('usb3','USB','out')];
 const definitions={};
 function define(id,data){definitions[id]={weightKg:1,volumeUnits:1,quality:'Standard',durability:({Starter:65,Standard:85,Pro:95,Touring:99}[data.quality||'Standard']),ports:[],...data};return definitions[id];}
 const computerIds=['starter-laptop','vj-laptop-gtx','creator-laptop-rtx','desktop-rtx4060','desktop-rtx4080'];
 computerIds.forEach((id,i)=>define('computer-'+id,{kind:i<3?'laptop':'tower',weightKg:i<3?2.1:8,volumeUnits:i<3?4:14,price:[0,500,1050,1350,1700][i],label:['LegacyBook VGA','FieldPad HDMI','Creator Laptop','Tour Stage Mid','Tour Stage Pro'][i],unlock:[0,3,9,21,21][i],quality:['Starter','Standard','Pro','Pro','Touring'][i],supportsSDI:i===4,maxOutputs:i===2?2:1,ports:[power(),...(i===0?[videoOut('VGA'),videoOut('HDMI')]:i===1?[videoOut('HDMI')]:i===2?[videoOut('HDMI'),videoOut('USB-C','usbc-video')]:[]),...usb(),videoOut('AUX','audio')]}));
 ['cheap','standard','short-throw','laser-entry','pro-6500','ultra-4k'].forEach((id,i)=>define('projector-'+id,{kind:'projector',weightKg:[3,3.5,4,4.5,8,12][i],volumeUnits:[8,9,9,10,14,18][i],price:[220,380,650,950,1550,2600][i],unlock:[0,3,6,9,15,21][i],lumens:[2200,4200,4000,5000,6500,8200][i],quality:['Starter','Standard','Standard','Pro','Pro','Touring'][i],ports:[power(),...(i===0?[videoIn('VGA')]:[videoIn('HDMI')]),...(i>=4?[videoIn('SDI')]:[])],defaultInput:i===0?'VGA':'HDMI'}));
 ['gpu-mobile','gpu-desktop-mid','gpu-desktop-pro'].forEach((id,i)=>define('gpu-'+id,{kind:'gpu',price:[380,750,1300][i],unlock:21,weightKg:.8,volumeUnits:2,outputs:i+2,quality:i===2?'Touring':'Pro',ports:[videoOut('HDMI','gpu-hdmi'),...Array.from({length:i+1},(_,n)=>videoOut('DP','gpu-dp'+(n+1)))]}));
 define('gpu-sdi-pcie',{kind:'sdi-card',label:'Carte SDI PCIe',price:900,unlock:21,weightKg:.4,volumeUnits:1,ports:Array.from({length:4},(_,i)=>videoOut('SDI','sdi'+(i+1)))});
 function cable(id,label,standard,length,price,unlock=0,ends=[standard,standard]){define(id,{kind:'cable',label,standard,ends,length,price,unlock,weightKg:Math.max(.15,length*.035),volumeUnits:length>=20?3:length>=10?2:1,quality:length>=15?'Pro':'Standard',ports:[]});}
 cable('cable-vga-3','VGA 3 m','VGA',3,12);cable('cable-vga-10','VGA 10 m','VGA',10,25);
 cable('cable-25ft-basic','HDMI 2 m','HDMI',2,15,3);cable('cable-hdmi-5','HDMI 5 m','HDMI',5,25,3);cable('cable-75ft-active','HDMI actif 15 m','HDMI',15,55,3);cable('cable-150ft-fiber','HDMI fibre 30 m','HDMI',30,95,12);
 [10,30,50].forEach((l,i)=>cable('cable-sdi-'+l,'SDI BNC '+l+' m','SDI',l,[30,65,95][i],12));
 [3,10,20].forEach((l,i)=>cable('cable-xlr-'+l,'XLR '+l+' m','XLR',l,[14,25,40][i],6));
 cable('cable-iec','IEC alimentation 3 m','POWER',3,12,0,['MAINS','IEC']);cable('cable-extension','Extension secteur 10 m','POWER',10,18,0,['MAINS','IEC']);
 cable('cable-dp','DisplayPort 3 m','DP',3,25,9);cable('cable-usbc-video','USB-C vidéo 3 m','USB-C',3,25,9);cable('cable-usb','USB 2 m','USB',2,8,21);
 function converter(id,label,from,to,price,unlock,active=true){define(id,{kind:'converter',label,price,unlock,weightKg:.3,volumeUnits:1,from,to,active,ports:[videoIn(from,'in'),videoOut(to,'out'),...(active?[power()]:[])]});}
 converter('adapter-dp-hdmi-basic','DP → HDMI','DP','HDMI',30,9,false);converter('adapter-usb-c-hdmi','USB-C vidéo → HDMI','USB-C','HDMI',45,9,false);converter('adapter-vga-hdmi','VGA → HDMI actif','VGA','HDMI',45,3);
 converter('converter-hdmi-sdi','MicroBridge HDMI → SDI 3G','HDMI','SDI',95,12);converter('converter-sdi-hdmi','MicroBridge SDI → HDMI 3G','SDI','HDMI',95,12);converter('converter-bidirectional','MicroBridge BiDirectional 3G','HDMI','SDI',140,12);converter('converter-12g','MicroBridge HDMI → SDI 12G','HDMI','SDI',250,21);
 define('router-splitter-duo',{kind:'splitter',price:70,unlock:3,ports:[videoIn('HDMI','in'),videoOut('HDMI','out1'),videoOut('HDMI','out2'),power()]});
 define('router-sdi-distribution',{kind:'splitter',label:'Distribution SDI 1×4',price:220,unlock:18,ports:[videoIn('SDI','in'),...Array.from({length:4},(_,i)=>videoOut('SDI','out'+(i+1))),power()]});
 define('router-matrix-4x4',{kind:'matrix',price:520,unlock:21,ports:[...Array.from({length:4},(_,i)=>videoIn('HDMI','in'+(i+1))),...Array.from({length:4},(_,i)=>videoOut('HDMI','out'+(i+1))),power()]});
 define('power-bar',{kind:'powerbar',label:'Power bar 6 prises',price:25,ports:[power(),...Array.from({length:6},(_,i)=>port('out'+(i+1),'MAINS','out'))],weightKg:.7,volumeUnits:1});
 define('venue-outlet',{kind:'outlet',label:'Prises du lieu',ports:Array.from({length:12},(_,i)=>port('out'+(i+1),'MAINS','out')),weightKg:0,volumeUnits:0});
 cable('cable-audio-3','Jack stéréo 3,5 mm · 3 m','AUX',3,8);
 define('audio-speakers-basic',{kind:'speaker',label:'Deux mini haut-parleurs de laptop',price:25,quality:'Starter',ports:[videoIn('AUX','audio')],defaultInput:'AUX',weightKg:.4,volumeUnits:2});
 define('audio-speakers-active',{kind:'speaker',label:'Paire de moniteurs actifs',price:160,unlock:3,quality:'Pro',ports:[videoIn('AUX','audio'),power()],defaultInput:'AUX',weightKg:4,volumeUnits:6});
 define('audio-mic',{kind:'microphone',label:'Micro filaire StageMic',price:55,unlock:6,ports:[videoOut('XLR')],weightKg:.35,volumeUnits:2});
 define('audio-console',{kind:'audio-console',label:'Console audio 4 voies',price:140,unlock:6,ports:[videoIn('XLR','mic'),power()],weightKg:1,volumeUnits:3});
 define('audio-wireless',{kind:'wireless',label:'Micro RF StageMic',price:180,unlock:12,ports:[],weightKg:.4,volumeUnits:2});
 define('audio-receiver',{kind:'receiver',label:'Récepteur RF StageMic',price:140,unlock:12,ports:[videoOut('XLR'),power()],weightKg:.5,volumeUnits:2});
 ['basic','compact-pro','touring'].forEach((v,i)=>define('keyboard-'+v,{kind:'keyboard',label:['Clavier USB Basic','Clavier Compact Pro','Clavier Touring'][i],price:[25,65,110][i],unlock:21,quality:['Starter','Pro','Touring'][i],weightKg:[.7,.35,.6][i],volumeUnits:i===1?1:2,ports:[port('usb','USB','in')]}));
 ['basic','wireless','touring'].forEach((v,i)=>define('mouse-'+v,{kind:'mouse',label:['Souris USB Basic','Souris Wireless Compact','Souris Touring'][i],price:[18,45,80][i],unlock:21,quality:['Starter','Standard','Touring'][i],weightKg:.12,volumeUnits:.5,ports:[port('usb','USB','in')],wireless:i===1}));
 ['monitor-24','monitor-27','portable-touch'].forEach((v,i)=>define('screen-'+v,{kind:'monitor',price:[220,420,340][i],unlock:21,weightKg:[3,4.5,1][i],volumeUnits:[6,8,4][i],ports:[videoIn('HDMI'),videoIn('DP'),power()],defaultInput:'HDMI'}));
 define('surface-square',{kind:'surface',label:'Écran 16:9 pliant',price:90,weightKg:3,volumeUnits:4,unlock:0});
 define('support-studio-cart',{kind:'stand',label:'Rack du garage',price:80,weightKg:7,volumeUnits:10,unlock:0});
 define('support-stand',{kind:'stand',label:'Support projecteur + élingue',price:103,weightKg:3,volumeUnits:4,unlock:9});
 ['bag-messenger-basic','bag-vj-backpack','bag-road-backpack','accessory-roadcase-pro'].forEach((id,i)=>define(id,{kind:'container',label:['RoadVault Messenger 12','RoadVault VJ Pack 32','RoadVault Flight Backpack','RoadVault Flight XL'][i],price:[55,180,360,620][i],unlock:[0,3,6,12][i],capacityVolume:[8,16,24,36][i],capacityKg:[7,13,18,28][i],weightKg:[.7,1,1.5,5][i],volumeUnits:[3,5,7,12][i],quality:['Starter','Standard','Pro','Touring'][i],rolling:i===3}));
 define('accessory-gaff-pocket',{kind:'gaffer',label:'StageTack — gaffer',price:18,weightKg:.2,volumeUnits:1,unlock:0});
 define('accessory-wide-lens',{kind:'lens',label:'Optomix WideKit 0.8',price:380,unlock:9,weightKg:.45,volumeUnits:1,quality:'Pro'});
 define('accessory-mapping-kit',{kind:'marker-kit',label:'MapLab Marker Kit',price:85,unlock:15,weightKg:.4,volumeUnits:1,quality:'Pro'});
 const spec=id=>definitions[id]||{kind:'accessory',weightKg:.2,volumeUnits:1,ports:[],quality:'Standard',durability:90};
 function instance(modelId,uid,location='shelf',position={x:0,y:0,z:0}){const d=spec(modelId);return{uid,modelId,owner:'player',condition:100,location,position:{...position},rotation:0,powerOn:d.kind==='powerbar',input:d.defaultInput||'',battery:100,open:false,ports:structuredClone(d.ports),installed:[],route:1};}
 function create(){return{version:4,nextId:1,objects:[],links:[],prepared:null,active:null,completed:[],selectedClips:[],results:[]};}
 const get=(s,id)=>s.objects.find(o=>o.uid===id);
 const endpoint=(s,e)=>{const object=e&&get(s,e.device);return object&&{object,port:object.ports.find(p=>p.id===e.port)};};
 function add(s,modelId,location='shelf',position){const o=instance(modelId,'av-'+s.nextId++,location,position);s.objects.push(o);return o;}
 function fail(reason){return{ok:false,reason};}
 function disconnect(s,cableId){const c=get(s,cableId);if(c){delete c.looseEnd;delete c.secured;}s.links=s.links.filter(l=>l.cable!==cableId);}
 function connect(s,cableId,a,b){const c=get(s,cableId),d=c&&spec(c.modelId),aa=endpoint(s,a),bb=endpoint(s,b);if(!c||d.kind!=='cable')return fail('Prends un câble.');if(!aa?.port||!bb?.port)return fail('Port introuvable.');if(a.device===b.device)return fail('Relie deux appareils différents.');if(['shelf','bag','vehicle','installed'].includes(aa.object.location)||['shelf','bag','vehicle','installed'].includes(bb.object.location))return fail('Pose les appareils sur une surface avant de les brancher.');if(aa.port.direction===bb.port.direction)return fail('Relie une sortie OUT à une entrée IN.');const out=aa.port.direction==='out'?aa:bb,inp=aa.port.direction==='in'?aa:bb;const ends=d.ends;if(!((ends[0]===out.port.standard&&ends[1]===inp.port.standard)||(ends[1]===out.port.standard&&ends[0]===inp.port.standard)))return fail('Connecteurs incompatibles : '+out.port.standard+' → '+inp.port.standard+'.');if(s.links.some(l=>l.cable!==cableId&&[l.a,l.b].some(e=>(e.device===a.device&&e.port===a.port)||(e.device===b.device&&e.port===b.port))))return fail('Ce port est déjà occupé.');const reach=root.PhysicalCore?.cableDistance?.(s,c,a,b)??distance(aa.object.position,bb.object.position);if(reach>d.length+.001)return fail('Câble trop court : '+d.length+' m pour un trajet de '+reach.toFixed(1)+' m.');disconnect(s,cableId);s.links.push({cable:cableId,a:{...a},b:{...b}});c.location='connected';delete c.container;delete c.looseEnd;return{ok:true};}
 function upstream(s,id,portId){const l=s.links.find(l=>[l.a,l.b].some(e=>e.device===id&&e.port===portId));if(!l)return null;return l.a.device===id&&l.a.port===portId?l.b:l.a;}
 function powered(s,id,seen=new Set()){if(seen.has(id))return false;seen.add(id);const o=get(s,id);if(!o)return false;const d=spec(o.modelId);if(d.kind==='outlet')return true;if(d.kind==='powerbar'&&!o.powerOn)return false;if(!o.ports.some(p=>p.standard==='IEC'))return true;const from=upstream(s,id,'power');return Boolean(from&&powered(s,from.device,seen));}
 function operational(s,o){return powered(s,o.uid)&&(spec(o.modelId).kind==='powerbar'||!o.ports.some(p=>p.standard==='IEC')||o.powerOn)&&o.condition>0;}
 function trace(s,id,portId,seen=new Set()){const key=id+':'+portId;if(seen.has(key))return{valid:false,reason:'Boucle de signal.'};seen.add(key);const o=get(s,id),d=o&&spec(o.modelId),p=o?.ports.find(p=>p.id===portId);if(!o||!p)return{valid:false,reason:'Port absent.'};if(!operational(s,o))return{valid:false,device:id,reason:powered(s,id)?'Appareil éteint.':'Alimentation absente.'};if(p.direction==='in'){const e=upstream(s,id,portId);return e?trace(s,e.device,e.port,seen):{valid:false,device:id,reason:'Câble absent.'};}
  if(['laptop','tower'].includes(d.kind)){const outs=o.ports.filter(p=>['HDMI','DP','SDI','VGA','USB-C'].includes(p.standard)&&p.direction==='out'&&p.id!=='control');if(d.kind==='laptop'&&outs.filter(p=>upstream(s,id,p.id)).indexOf(p)>=d.maxOutputs)return{valid:false,reason:'Sortie inactive sur ce laptop.'};return{valid:true,channel:id+':'+portId,standard:p.standard,standards:[p.standard]};}
  if(d.kind==='microphone')return{valid:true,channel:id,standard:'XLR'};
  if(d.kind==='receiver'){const rf=s.objects.find(x=>spec(x.modelId).kind==='wireless'&&x.location===o.location&&x.powerOn&&x.battery>5);return rf?{valid:true,channel:rf.uid,standard:'XLR'}:{valid:false,reason:'Micro RF éteint ou batterie faible.'};}
  if(d.kind==='converter'){const r=trace(s,id,'in',seen);return{...r,standard:p.standard,standards:[...new Set([...(r.standards||[]),p.standard])]};}
  if(d.kind==='splitter')return trace(s,id,'in',seen);
  if(d.kind==='matrix')return trace(s,id,'in'+(o.routes?.[portId]||o.route||1),seen);
  return{valid:false,reason:'Pas de source.'};
 }
 function signal(s,id){const o=get(s,id),d=o&&spec(o.modelId);if(!o)return{valid:false,reason:'Appareil absent.'};const p=o.ports.find(p=>p.direction==='in'&&p.standard===o.input);if(!p)return{valid:false,device:id,reason:'Mauvais input.'};return trace(s,id,p.id);}
 function workstation(s,id){const o=get(s,id);if(!o||!operational(s,o))return fail('Ordinateur éteint ou sans alimentation.');if(spec(o.modelId).kind==='laptop')return{ok:true};const peers=s.links.flatMap(l=>l.a.device===id?[get(s,l.b.device)]:l.b.device===id?[get(s,l.a.device)]:[]).filter(Boolean);for(const kind of ['keyboard','mouse'])if(!peers.some(x=>spec(x.modelId).kind===kind&&(!spec(x.modelId).wireless||x.battery>5)))return fail(kind==='keyboard'?'Clavier USB manquant.':'Souris USB manquante ou batterie vide.');if(!peers.some(x=>spec(x.modelId).kind==='monitor'&&signal(s,x.uid).valid))return fail('Moniteur de contrôle non connecté ou sans signal.');return{ok:true};}
 function content(s,bag){return s.objects.filter(x=>x.location==='bag'&&x.container===bag);}
 function load(s,bag){return content(s,bag).reduce((r,x)=>{const d=spec(x.modelId);r.volume+=d.volumeUnits;r.kg+=d.weightKg;return r;},{volume:0,kg:0});}
 function pack(s,id,bagId){const o=get(s,id),b=get(s,bagId),d=b&&spec(b.modelId);if(!o||!b||d.kind!=='container')return fail('Choisis un sac.');if(o.location==='installed')return fail('Retire la carte de la tour avant de la ranger.');if(!b.open)return fail('Ouvre le sac avec O.');if(s.objects.some(x=>x.mountedTo===id))return fail('Retire les objets posés sur le rack avant de le ranger.');if(spec(o.modelId).kind==='container'||o.uid===b.uid)return fail('Les sacs ne se rangent pas les uns dans les autres.');if(s.links.some(l=>l.cable===id||l.a.device===id||l.b.device===id))return fail('Débranche cet objet avant de le ranger.');const used=load(s,bagId),item=spec(o.modelId);if(used.volume+item.volumeUnits>d.capacityVolume||used.kg+item.weightKg>d.capacityKg)return fail('Sac plein : limite de volume ou de poids dépassée.');o.location='bag';o.container=bagId;return{ok:true};}
 function move(s,id,position,location){const o=get(s,id);if(!o)return fail('Objet absent.');for(const l of s.links.filter(l=>l.a.device===id||l.b.device===id)){const fixed=get(s,l.cable);if(fixed?.secured&&distance(position,o.position)>.15)return fail('Retire le gaffer avant de déplacer cet appareil.');const other=get(s,l.a.device===id?l.b.device:l.a.device),c=get(s,l.cable);if(other&&(root.PhysicalCore?.cableDistance?.(s,c,l.a,l.b,{uid:id,position})??distance(position,other.position))>spec(c.modelId).length)return fail('Déplacement bloqué : câble tendu.');}o.position={...position};if(location)o.location=location;delete o.container;delete o.mountedTo;delete o.mountedOffset;return{ok:true};}
 function install(s,cardId,towerId){const card=get(s,cardId),tower=get(s,towerId);if(!card||!tower||spec(tower.modelId).kind!=='tower'||!['gpu','sdi-card'].includes(spec(card.modelId).kind))return fail('Cette carte demande une tour.');if(tower.powerOn)return fail('Éteins la tour avant de changer une carte.');const kind=spec(card.modelId).kind;if(kind==='sdi-card'&&!spec(tower.modelId).supportsSDI)return fail('Cette carte SDI demande une Tour Stage Pro avec port PCIe.');const old=tower.installed.map(id=>get(s,id)).find(o=>o&&spec(o.modelId).kind===kind);if(old){if(s.links.some(l=>[l.a,l.b].some(e=>e.device===towerId&&old.ports.some(p=>p.id===e.port))))return fail('Débranche les sorties de la carte.');tower.ports=tower.ports.filter(p=>!old.ports.some(q=>p.id===q.id));old.location='desk';old.position={...tower.position,x:tower.position.x+.6};tower.installed=tower.installed.filter(id=>id!==old.uid);}tower.installed.push(cardId);tower.ports.push(...structuredClone(card.ports));card.location='installed';card.container=towerId;return{ok:true};}
 function setRoute(s,id,output,input){const o=get(s,id);if(!o||spec(o.modelId).kind!=='matrix'||!o.ports.some(p=>p.id===output&&p.direction==='out')||![1,2,3,4].includes(input))return fail('Routage invalide.');if(!operational(s,o))return fail('Alimente et allume la matrice.');o.routes||={};o.routes[output]=input;return{ok:true};}
 function uninstall(s,cardId){const card=get(s,cardId),tower=card&&get(s,card.container);if(!card||card.location!=='installed'||!tower)return fail('Carte non installée.');if(tower.powerOn)return fail('Éteins la tour avant de retirer une carte.');if(s.links.some(l=>[l.a,l.b].some(e=>e.device===tower.uid&&card.ports.some(p=>p.id===e.port))))return fail('Débranche les sorties de cette carte.');tower.ports=tower.ports.filter(p=>!card.ports.some(q=>q.id===p.id));tower.installed=tower.installed.filter(id=>id!==cardId);card.location=tower.location==='venue'?'venue':'desk';card.position={...tower.position,x:tower.position.x+.65};delete card.container;return{ok:true};}
 function secure(s,cableId,tapeId){const cable=get(s,cableId),tape=get(s,tapeId);if(!cable||!tape||spec(tape.modelId).kind!=='gaffer'||tape.location!=='hand')return fail('Prends le rouleau de gaffer.');if(!s.links.some(l=>l.cable===cableId))return fail('Branche le câble avant de le fixer.');cable.secured=true;return{ok:true};}
 function attach(s,id,targetId){const o=get(s,id),target=get(s,targetId);if(!o||!target||o.location!=='hand')return fail('Prends cet accessoire.');const kind=spec(o.modelId).kind;if(kind==='marker-kit'&&spec(target.modelId).kind==='surface'){target.referenceMarkers=true;return{ok:true};}if(kind!=='lens'||spec(target.modelId).kind!=='projector')return fail('La lentille se monte sur un projecteur.');if(target.powerOn)return fail('Éteins le projecteur avant de monter la lentille.');if(target.installed.some(id=>spec(get(s,id)?.modelId).kind==='lens'))return fail('Retire la lentille actuelle.');target.installed.push(id);o.location='installed';o.container=targetId;return{ok:true};}
 function opticalScale(s,id){const o=get(s,id);if(!o)return 1;const lens=o.installed.some(id=>spec(get(s,id)?.modelId).kind==='lens');return(o.modelId==='projector-short-throw'?1.35:1)*(lens?1.25:1);}
 root.PhysicalCore={definitions,define,spec,port,create,instance,add,get,endpoint,distance,connect,disconnect,powered,operational,signal,trace,workstation,pack,content,load,move,install,uninstall,setRoute,secure,attach,opticalScale};
 if(typeof module!=='undefined')module.exports=root.PhysicalCore;
})(typeof window!=='undefined'?window:globalThis);
