/* Direct studio entry; profile creation is used only for an empty save slot. */
(() => {
 let entering=false;
 document.querySelector('#studio-entry-button').onclick=()=>{
  const index=slots[activeSlot]?.created?activeSlot:Math.max(0,slots.findIndex(s=>s.created));
  entering=true;chooseSlot(index);
  if(profile.created){entering=false;StudioWorld.enter();}
 };
 document.querySelector('#create-vj-button').addEventListener('click',()=>{if(entering&&profile.created){entering=false;StudioWorld.enter();}});

 const style=document.createElement('style');
 style.textContent=`
 .relax-game-icon{display:flex!important}
 .relax-game-window{position:absolute;inset:76px 8% 70px;z-index:85;display:grid;grid-template-rows:auto 1fr auto;gap:14px;padding:18px;border:1px solid #426d78;border-radius:14px;background:linear-gradient(180deg,#0d1c25f5,#08131bf7);box-shadow:0 28px 80px #0009;color:#e9f7f7}
 .relax-game-window[hidden]{display:none}.relax-game-head{display:flex;justify-content:space-between;align-items:start;gap:18px}.relax-game-head h2{margin:2px 0 6px;font-size:24px}.relax-game-head p{margin:0;color:#9cb6be;max-width:650px;line-height:1.45}.relax-game-head button,.relax-game-actions button{border:1px solid #527c84;border-radius:7px;padding:10px 14px;background:#17313d;color:#ecf8f8;cursor:pointer}.relax-game-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.relax-game-actions .primary{background:#b8e7df;color:#12272d;border-color:#d7fff8;font-weight:800}.relax-game-status{margin-left:auto;color:#cfdcba;font-size:13px}.relax-game-board{position:relative;min-height:280px;border:1px solid #315463;border-radius:12px;overflow:hidden;background:radial-gradient(circle at 50% 45%,#173344,#071019 68%)}.relax-game-board canvas{display:block;width:100%;height:100%;min-height:280px;cursor:crosshair}.relax-game-hud{position:absolute;left:14px;top:12px;display:flex;gap:10px;pointer-events:none}.relax-game-hud span{padding:6px 9px;border-radius:999px;background:#07131ccd;border:1px solid #30545e;font:12px monospace;color:#bfeee7}
 #academy.resolut-reference{padding:10px!important;background:#080b0e!important}.resolut-reference>header{display:none!important}.resolut-reference .resolut-original-hidden{display:none!important}.resolut-reference .resolute-console{margin:0!important;border-radius:4px!important;background:#07151e!important;border-color:#0e6f82!important;box-shadow:0 22px 70px #000b}.resolut-reference .resolute-titlebar{min-height:48px!important;background:#07131c!important;border-bottom:1px solid #155b70!important;padding:0 14px!important;gap:18px!important;color:#a9cbd4!important}.resolut-reference .resolute-titlebar strong{display:flex;align-items:center;gap:9px;color:white!important;font-size:20px!important;text-transform:none!important}.resolut-reference .resolute-titlebar strong i{display:grid;place-items:center;width:32px;height:32px;background:linear-gradient(145deg,#d9fbff,#56e3ff 55%,#18b8d5);color:#073344;font-style:normal;font-weight:1000;clip-path:polygon(50% 0,100% 100%,72% 100%,62% 76%,38% 76%,28% 100%,0 100%)}.resolut-reference .resolute-titlebar .res-menu{display:flex;gap:18px;font-size:11px;color:#b7c8d0}.resolut-reference .resolute-titlebar .res-comp{margin-left:auto;padding:8px 13px;border:1px solid #20506a;border-radius:5px;background:#0a2231;color:#dbeff6}.resolut-reference .resolute-titlebar .res-live{display:flex;align-items:center;gap:7px;color:#48ffae;font-weight:800}.resolut-reference .resolute-titlebar .res-live:before{content:'';width:8px;height:8px;border-radius:50%;background:#48ffae;box-shadow:0 0 12px #48ffae}
 .resolut-pro-workspace{display:grid;grid-template-columns:145px minmax(310px,1.05fr) minmax(360px,1.35fr) 265px;min-height:560px;background:#071018}.resolut-layers,.resolut-browser,.resolut-program,.resolut-params{min-width:0;border-right:1px solid #174556}.resolut-layers{padding:10px 8px;background:#08141c}.resolut-section-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px;color:#27e7ff;font-size:11px;font-weight:900}.resolut-add{padding:6px 9px;border:1px solid #17687b;border-radius:4px;background:#0d2b36;color:#c9f8ff;font-size:10px}.resolut-reference .resolute-layer,.resolut-layer-card{display:grid!important;gap:7px!important;justify-content:stretch!important;min-height:86px;margin-bottom:7px;padding:10px!important;border:1px solid #174654!important;border-left:4px solid #19def4!important;border-radius:4px;background:#0c202a!important;color:#dbe9ee!important}.resolut-layer-card strong,.resolut-reference .resolute-layer strong{font-size:12px}.resolut-layer-card span,.resolut-reference .resolute-layer span{font-size:9px;color:#91aab2}.resolut-layer-card b{display:grid;place-items:center;height:34px;border:1px dashed #2c5662;background:#0a1820;color:#607a83;font-weight:400}
 .resolut-browser{display:grid;grid-template-rows:auto 1fr auto;padding:9px;background:#06131b}.resolut-tabs{display:flex;gap:6px;margin-bottom:8px}.resolut-tabs span{padding:7px 10px;border-radius:4px;background:#0d2531;color:#9fb9c2;font-size:10px}.resolut-tabs .active{background:#31e5f6;color:#06242a;font-weight:900}.resolut-reference .academy-clips{align-content:start!important;margin:0!important;padding:0!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important}.resolut-reference .academy-clips button{background:#07141c!important;border:1px solid #1c5363!important;border-radius:4px!important;overflow:hidden!important}.resolut-reference .academy-clips canvas{max-height:none!important;width:100%!important;aspect-ratio:16/9!important}.resolut-reference .academy-clips button[aria-pressed=true]{border-color:#27f4ff!important;box-shadow:0 0 0 1px #27f4ff,0 0 15px #09dff43d!important}.resolut-preview-slot{margin-top:9px;padding-top:8px;border-top:1px solid #164453}.resolut-preview-slot label{display:grid;gap:6px;color:#21e7fb;font-size:10px;font-weight:800}.resolut-preview-slot canvas{display:block;width:100%!important;height:auto!important;aspect-ratio:16/9;border:1px solid #166374!important;background:#000!important}
 .resolut-program{display:grid;grid-template-rows:auto 1fr;padding:9px;background:#051018}.resolut-program-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px;color:#22e8ff;font-size:11px;font-weight:900}.resolut-reference .resolut-program label{display:grid;gap:6px;height:100%;color:#22e8ff;font-size:10px}.resolut-reference .resolut-program canvas{display:block;width:100%!important;height:100%!important;max-height:none!important;object-fit:cover;background:#000;border:1px solid #176b7c!important;border-radius:2px!important}.resolut-program-stage{min-height:0;display:grid}.resolut-program-stage label{min-height:0}.resolut-program-stage canvas{min-height:430px}
 .resolut-params{padding:10px;background:#071720;border-right:0}.resolut-param-card{padding:10px;border:1px solid #15536a;border-radius:4px;background:#0a202a;margin-bottom:9px}.resolut-param-card h3{margin:0 0 10px;color:#27e7ff;font-size:11px}.resolut-param-row{display:grid;grid-template-columns:58px 1fr 38px;align-items:center;gap:7px;margin:9px 0;color:#dce8ec;font-size:10px}.resolut-param-row span:nth-child(2){height:4px;border-radius:9px;background:linear-gradient(90deg,#24dcf0 55%,#183845 55%)}.resolut-effects{display:grid;gap:6px}.resolut-effect{display:flex;align-items:center;gap:8px;padding:8px;border:1px solid #164c5e;background:#081922;color:#dbe7eb;font-size:10px}.resolut-effect b{margin-left:auto;color:#25e9ff}.resolut-effect.locked{opacity:.46}.resolut-reference .academy-controls{display:grid!important;grid-template-columns:1fr!important;gap:9px!important;margin:0!important;padding:0!important;background:transparent!important;border:0!important}.resolut-reference .academy-controls>div{display:grid;gap:8px;padding:10px;border:1px solid #15536a;border-radius:4px;background:#0a202a}.resolut-reference .academy-controls label{font-size:10px!important}.resolut-reference .academy-controls button{min-height:36px!important}.resolut-coach{border-top:1px solid #164555;background:#08141d;padding:8px}.resolut-coach aside{display:grid!important;grid-template-columns:minmax(200px,.8fr) minmax(260px,1fr) auto;align-items:center;gap:10px!important;padding:10px!important;border:1px solid #1a5261!important;border-radius:4px!important;background:#0b202a!important}.resolut-coach aside h2{font-size:16px!important;margin:0!important}.resolut-coach aside p{font-size:11px!important;line-height:1.35!important}.resolut-coach .room-missions{display:flex!important;gap:5px!important;flex-wrap:wrap}.resolut-coach .room-missions button{min-height:34px!important;padding:6px 8px!important;font-size:9px!important}.resolut-reference footer{padding:7px 10px!important;background:#061018!important;border-top:1px solid #154858!important}
 @media(max-width:1150px){.resolut-pro-workspace{grid-template-columns:110px minmax(260px,1fr) minmax(300px,1.15fr)}.resolut-params{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;border-top:1px solid #174556}.resolut-param-card{margin:0}.resolut-reference .academy-controls{grid-template-columns:repeat(2,minmax(0,1fr))!important}.resolut-coach aside{grid-template-columns:1fr}}
 @media(max-width:760px){.relax-game-window{inset:62px 12px 58px}.resolut-pro-workspace{grid-template-columns:1fr}.resolut-layers{display:none}.resolut-browser,.resolut-program,.resolut-params{border-right:0;border-bottom:1px solid #174556}.resolut-program-stage canvas{min-height:240px}.resolut-params{grid-column:auto;display:block}.resolut-reference .academy-clips{grid-template-columns:repeat(2,minmax(0,1fr))!important}.resolut-reference .resolute-titlebar .res-menu,.resolut-reference .resolute-titlebar .res-comp{display:none}}
 `;
 document.head.append(style);

 function installRelaxGame(){
  const desktop=document.querySelector('#desktop-screen'),icons=desktop?.querySelector('.desktop-icons');
  if(!desktop||!icons||desktop.querySelector('.relax-game-icon'))return;
  const icon=document.createElement('button');icon.type='button';icon.className='desktop-icon relax-game-icon';icon.dataset.icon='◌';icon.textContent='Pause';icons.append(icon);
  const root=document.createElement('section');root.className='relax-game-window';root.hidden=true;root.innerHTML=`<div class="relax-game-head"><div><small>VJOS / PAUSE</small><h2>Neon Drift</h2><p>Une pause de 30 secondes entre deux contrats. Attrape doucement les orbes qui dérivent pour relâcher la pression.</p></div><button type="button" data-relax-close>Fermer</button></div><div class="relax-game-board"><canvas width="900" height="430" aria-label="Mini-jeu Neon Drift"></canvas><div class="relax-game-hud"><span data-relax-score>Score 0</span><span data-relax-time>30 s</span></div></div><div class="relax-game-actions"><button class="primary" type="button" data-relax-start>Jouer 30 s</button><span>Récompense quotidienne : fatigue ↓ et inspiration ↑.</span><strong class="relax-game-status" data-relax-status>Une récompense par jour de carrière.</strong></div>`;desktop.append(root);
  const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),scoreNode=root.querySelector('[data-relax-score]'),timeNode=root.querySelector('[data-relax-time]'),status=root.querySelector('[data-relax-status]'),startButton=root.querySelector('[data-relax-start]');
  let running=false,raf=0,endAt=0,score=0,orbs=[];
  const resetOrbs=()=>{orbs=Array.from({length:9},(_,i)=>({x:90+Math.random()*720,y:70+Math.random()*290,r:16+Math.random()*15,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.18,h:175+i*13}));};
  function draw(now){
   ctx.clearRect(0,0,canvas.width,canvas.height);const bg=ctx.createRadialGradient(450,205,20,450,205,480);bg.addColorStop(0,'#16394a');bg.addColorStop(1,'#050b11');ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);
   ctx.strokeStyle='rgba(126,225,230,.08)';for(let x=0;x<canvas.width;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();}for(let y=0;y<canvas.height;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke();}
   orbs.forEach((o,i)=>{if(running){o.x+=o.vx*16;o.y+=o.vy*16;if(o.x<o.r||o.x>canvas.width-o.r)o.vx*=-1;if(o.y<o.r||o.y>canvas.height-o.r)o.vy*=-1;}const pulse=1+Math.sin(now*.002+i)*.08,g=ctx.createRadialGradient(o.x,o.y,2,o.x,o.y,o.r*2.2);g.addColorStop(0,`hsla(${o.h},90%,78%,.95)`);g.addColorStop(.35,`hsla(${o.h},88%,58%,.62)`);g.addColorStop(1,`hsla(${o.h},90%,55%,0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r*2.2*pulse,0,Math.PI*2);ctx.fill();ctx.fillStyle=`hsl(${o.h} 86% 70%)`;ctx.beginPath();ctx.arc(o.x,o.y,o.r*pulse,0,Math.PI*2);ctx.fill();});
   if(running){const left=Math.max(0,endAt-now);timeNode.textContent=`${Math.ceil(left/1000)} s`;if(left<=0){finish();return;}}raf=requestAnimationFrame(draw);
  }
  function finish(){running=false;cancelAnimationFrame(raf);startButton.disabled=false;timeNode.textContent='0 s';const day=Number(profile?.day)||1;profile.relaxGame||={};profile.relaxGame.best=Math.max(Number(profile.relaxGame.best)||0,score);if(profile.relaxGame.rewardDay!==day){const fatigueBefore=Number(profile.stats?.fatigue)||0,creativityBefore=Number(profile.stats?.creativity)||0;profile.stats.fatigue=Math.max(0,fatigueBefore-6);profile.stats.creativity=Math.min(100,creativityBefore+(score>=12?2:1));profile.relaxGame.rewardDay=day;saveSlots();if(typeof updateProfileChrome==='function')updateProfileChrome();status.textContent=`Pause réussie : fatigue -${fatigueBefore-profile.stats.fatigue}, inspiration +${profile.stats.creativity-creativityBefore}.`;}else status.textContent=`Meilleur score : ${profile.relaxGame.best}. Récompense déjà reçue aujourd’hui.`;draw(performance.now());}
  function start(){if(running)return;running=true;score=0;scoreNode.textContent='Score 0';status.textContent='Respire. Clique les orbes à ton rythme.';startButton.disabled=true;resetOrbs();endAt=performance.now()+30000;cancelAnimationFrame(raf);raf=requestAnimationFrame(draw);}
  canvas.addEventListener('pointerdown',event=>{if(!running)return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*canvas.width/rect.width,y=(event.clientY-rect.top)*canvas.height/rect.height;let best=-1,bestD=Infinity;orbs.forEach((o,i)=>{const d=Math.hypot(o.x-x,o.y-y);if(d<o.r*1.35&&d<bestD){best=i;bestD=d;}});if(best>=0){score++;scoreNode.textContent=`Score ${score}`;orbs[best]={x:70+Math.random()*760,y:60+Math.random()*310,r:16+Math.random()*15,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.18,h:170+Math.random()*160};}});
  icon.onclick=()=>{root.hidden=false;resetOrbs();scoreNode.textContent=`Meilleur ${Number(profile?.relaxGame?.best)||0}`;timeNode.textContent='30 s';status.textContent=profile?.relaxGame?.rewardDay===(Number(profile?.day)||1)?'Récompense déjà reçue aujourd’hui, mais tu peux rejouer.':'Récompense quotidienne disponible.';cancelAnimationFrame(raf);raf=requestAnimationFrame(draw);};
  root.querySelector('[data-relax-close]').onclick=()=>{running=false;cancelAnimationFrame(raf);root.hidden=true;};startButton.onclick=start;resetOrbs();root.hidden=true;
 }

 function upgradeResolut(){
  const academy=document.querySelector('#academy'),consolePanel=academy?.querySelector('.resolute-console');
  if(!academy||!consolePanel||consolePanel.dataset.referenceLayout==='1')return;
  const deck=consolePanel.querySelector('.resolute-deck'),layer=consolePanel.querySelector('.resolute-layer'),clips=consolePanel.querySelector('.academy-clips'),controls=consolePanel.querySelector('.academy-controls'),monitors=controls?.querySelector('.resolute-monitors'),aside=academy.querySelector('.academy-layout aside');
  if(!deck||!layer||!clips||!controls||!monitors||!aside)return;
  const monitorLabels=[...monitors.querySelectorAll('label')];if(monitorLabels.length<2)return;
  const previewLabel=monitorLabels[0],programLabel=monitorLabels[1];
  consolePanel.dataset.referenceLayout='1';academy.classList.add('resolut-reference');academy.querySelector('.academy-layout')?.classList.add('resolut-original-hidden');
  const titlebar=consolePanel.querySelector('.resolute-titlebar');titlebar.innerHTML='<strong><i>A</i> Resolut 8</strong><span class="res-menu">Fichier &nbsp; Édition &nbsp; Affichage &nbsp; Aide</span><span class="res-comp">Ma création · Le Sous-sol</span><span class="res-live">EN DIRECT</span>';
  const workspace=document.createElement('div');workspace.className='resolut-pro-workspace';
  const layers=document.createElement('section');layers.className='resolut-layers';layers.innerHTML='<div class="resolut-section-title"><span>COUCHES</span><button class="resolut-add" type="button">+ Ajouter</button></div>';layers.append(layer);[['2','Effets','Add'],['3','Fond','Normal']].forEach(([n,name,mode])=>{const card=document.createElement('div');card.className='resolut-layer-card';card.innerHTML=`<small>${n}</small><strong>${name}</strong><b>▦</b><span>${mode}</span>`;layers.append(card);});
  const browser=document.createElement('section');browser.className='resolut-browser';browser.innerHTML='<div class="resolut-tabs"><span class="active">Mes clips</span><span>Tous les clips</span><span>Favoris</span><span>⌕</span></div>';browser.append(clips);const preview=document.createElement('div');preview.className='resolut-preview-slot';preview.append(previewLabel);browser.append(preview);
  const program=document.createElement('section');program.className='resolut-program';program.innerHTML='<div class="resolut-program-head"><span>SORTIE / PROGRAMME</span><span>● EN DIRECT</span></div>';const programStage=document.createElement('div');programStage.className='resolut-program-stage';programStage.append(programLabel);program.append(programStage);
  const params=document.createElement('aside');params.className='resolut-params';params.innerHTML='<div class="resolut-param-card"><h3>PARAMÈTRES DU CLIP</h3><div class="resolut-param-row"><span>Vitesse</span><span></span><b>1.00x</b></div><div class="resolut-param-row"><span>Couleur</span><span></span><b>100%</b></div><div class="resolut-param-row"><span>Opacité</span><span></span><b>80%</b></div><div class="resolut-param-row"><span>Échelle</span><span></span><b>100%</b></div><div class="resolut-param-row"><span>Rotation</span><span></span><b>0°</b></div></div><div class="resolut-param-card"><h3>EFFETS</h3><div class="resolut-effects"><div class="resolut-effect">◉ Glow <b>≡</b></div><div class="resolut-effect">◉ Colorize <b>≡</b></div><div class="resolut-effect locked">🔒 Distorsion <b>PRO</b></div><div class="resolut-effect locked">🔒 Kaléidoscope <b>PRO</b></div></div></div>';
  params.append(controls);workspace.append(layers,browser,program,params);titlebar.after(workspace);deck.remove();monitors.remove();
  const coach=document.createElement('div');coach.className='resolut-coach';coach.append(aside);consolePanel.after(coach);
 }

 installRelaxGame();upgradeResolut();
})();
