/* Phase 9 · Core VJ 3.0
   Progressive real layers, blend modes, master macros and a lightweight set recorder. */
window.VJCore3=(()=>{
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
  function careerLevel(){return Math.max(1,Number(profile?.level)||Math.floor((Number(profile?.xp)||0)/500)+1);}
  function unlockedLayerCount(){const level=careerLevel();return level>=9?4:level>=6?3:level>=3?2:1;}
  function injectStyles(){if(document.querySelector('#vj-core3-style'))return;const s=document.createElement('style');s.id='vj-core3-style';s.textContent=`.core3-panel{margin:10px 0;border:1px solid #344f5d;border-radius:7px;background:#0f202a;color:#eaf3f4}.core3-panel>summary{cursor:pointer;padding:9px 11px;font-size:11px;font-weight:700;letter-spacing:.08em}.core3-inner{padding:0 10px 10px}.core3-layer{display:grid;grid-template-columns:70px minmax(120px,1fr) 110px 110px;gap:7px;align-items:center;padding:7px 0;border-top:1px solid #263f4a}.core3-layer strong{font-size:10px}.core3-layer label{display:flex;gap:5px;align-items:center;font-size:9px;color:#9fb4bd}.core3-layer select,.core3-layer input{min-width:0}.core3-lock{opacity:.55}.core3-master{display:flex;gap:7px;flex-wrap:wrap;border-top:1px solid #263f4a;padding-top:8px}.core3-master button{min-height:32px}.core3-rec{margin-left:auto}.core3-rec[aria-pressed="true"]{outline:2px solid #e46c6c;color:#ffd2d2}@media(max-width:760px){.core3-layer{grid-template-columns:1fr 1fr}.core3-rec{margin-left:0}}`;document.head.append(s);}
  function createLayer(show,index){return {index,clipIndex:(show.currentIndex+index)%show.clips.length,opacity:index===1?.35:.25,blend:'screen',video:null,changes:0};}
  function releaseLayer(show,layer){if(layer?.video){show.release(layer.video);layer.video=null;}}
  function loadLayer(show,layer,index){if(!show.clips[index])return;releaseLayer(show,layer);layer.clipIndex=index;layer.video=show.media(index);layer.video.play().catch(()=>{});layer.changes++;}
  function mount(show,saved=null){
    if(show.__core3)return restore(show,saved),show.__core3;
    injectStyles();const count=unlockedLayerCount(),state={layers:[],recording:false,record:[],saved:false};for(let i=1;i<count;i++){const layer=createLayer(show,i);state.layers.push(layer);loadLayer(show,layer,layer.clipIndex);}
    const panel=document.createElement('details');panel.className='core3-panel';panel.innerHTML=`<summary>Régie avancée · ${count}/4 couches disponibles</summary><div class="core3-inner"><div data-core3-layers></div><div class="core3-master"><button type="button" data-core3-macro="break">Macro BREAK</button><button type="button" data-core3-macro="clean">Macro CLEAN</button><button type="button" data-core3-macro="peak">Macro PEAK</button><button type="button" data-core3-bypass>Bypass FX</button><button class="core3-rec" type="button" data-core3-rec aria-pressed="false">● REC réglages</button></div></div>`;
    const host=show.root.querySelector('.resolute-console-main')||show.root;host.append(panel);const layersRoot=panel.querySelector('[data-core3-layers]');
    for(let i=1;i<4;i++){
      const unlocked=i<count,layer=state.layers.find(l=>l.index===i);const row=document.createElement('div');row.className=`core3-layer ${unlocked?'':'core3-lock'}`;row.innerHTML=unlocked?`<strong>COUCHE ${i+1}</strong><select data-layer-clip></select><label>Opacité <input data-layer-opacity type="range" min="0" max="100" value="${Math.round(layer.opacity*100)}"></label><label>Fusion <select data-layer-blend><option value="screen">Screen</option><option value="lighter">Add</option><option value="source-over">Normal</option><option value="multiply">Multiply</option></select></label>`:`<strong>COUCHE ${i+1}</strong><span>Débloquée au niveau ${i===1?3:i===2?6:9}</span>`;layersRoot.append(row);
      if(!unlocked)continue;const clip=row.querySelector('[data-layer-clip]');show.clips.forEach((c,clipIndex)=>{const o=document.createElement('option');o.value=clipIndex;o.textContent=c.label;clip.append(o);});clip.value=layer.clipIndex;clip.onchange=()=>loadLayer(show,layer,Number(clip.value));row.querySelector('[data-layer-opacity]').oninput=e=>{layer.opacity=clamp(e.target.value,0,100)/100;layer.changes++;};row.querySelector('[data-layer-blend]').onchange=e=>{layer.blend=e.target.value;layer.changes++;};
    }
    panel.querySelectorAll('[data-core3-macro]').forEach(button=>button.onclick=()=>applyMacro(show,button.dataset.core3Macro));panel.querySelector('[data-core3-bypass]').onclick=()=>toggleBypass(show,panel.querySelector('[data-core3-bypass]'));panel.querySelector('[data-core3-rec]').onclick=e=>{state.recording=!state.recording;e.currentTarget.setAttribute('aria-pressed',String(state.recording));e.currentTarget.textContent=state.recording?'■ STOP REC':'● REC réglages';if(state.recording)state.record=[];else saveRecording(show);};
    show.__core3=state;if(saved)restore(show,saved);return state;
  }
  function applyMacro(show,id){
    const intensity=show.root.querySelector('[data-live-intensity]'),sat=show.root.querySelector('[data-live-saturation]'),zoom=show.root.querySelector('[data-live-zoom]');const presets={break:[28,82,100],clean:[50,100,100],peak:[88,130,112]},p=presets[id];if(!p)return;show.intensity=p[0]/100;show.effects.saturation=p[1];show.effects.zoom=p[2];intensity.value=p[0];sat.value=p[1];zoom.value=p[2];show.root.querySelector('[data-live-level]').textContent=`${p[0]} %`;show.root.querySelector('[data-live-saturation-value]').textContent=`${p[1]} %`;show.root.querySelector('[data-live-zoom-value]').textContent=`${p[2]} %`;show.effectChanges++;
  }
  function toggleBypass(show,button){show.__core3.bypass=!show.__core3.bypass;button.textContent=show.__core3.bypass?'Réactiver FX':'Bypass FX';button.setAttribute('aria-pressed',String(Boolean(show.__core3.bypass)));}
  function drawLayers(show){const state=show.__core3;if(!state)return;for(const layer of state.layers){const video=layer.video;if(!video||video.readyState<2||layer.opacity<=0)continue;show.ctx.save();show.ctx.globalAlpha=layer.opacity;show.ctx.globalCompositeOperation=layer.blend;show.ctx.filter=state.bypass?'none':`saturate(${show.effects.saturation}%) hue-rotate(${show.effects.hue}deg)`;show.ctx.drawImage(video,0,0,show.canvas.width,show.canvas.height);show.ctx.restore();}}
  function recordTick(show){const state=show.__core3;if(!state?.recording)return;const second=Math.floor(show.elapsed);if(state.record.at(-1)?.second===second)return;state.record.push({second,program:show.currentIndex,intensity:Math.round(show.intensity*100),effects:{...show.effects},layers:state.layers.map(l=>({clip:l.clipIndex,opacity:l.opacity,blend:l.blend}))});}
  function saveRecording(show){const state=show.__core3;if(!state||!state.record.length||state.saved)return;profile.sessionRecordings ||= [];profile.sessionRecordings.unshift({day:profile.day,gig:show.options?.gig?.id||currentGig?.id||'practice',duration:Math.round(show.elapsed),frames:state.record.slice(0,120)});profile.sessionRecordings=profile.sessionRecordings.slice(0,10);state.saved=true;saveSlots();notify('Réglages du set enregistrés dans la sauvegarde.');}
  function snapshot(show){const s=show.__core3;return s?{layers:s.layers.map(l=>({index:l.index,clipIndex:l.clipIndex,opacity:l.opacity,blend:l.blend,changes:l.changes})),recording:s.recording,record:s.record,bypass:Boolean(s.bypass)}:null;}
  function restore(show,saved){if(!saved)return;const s=show.__core3||mount(show);s.bypass=Boolean(saved.bypass);for(const data of saved.layers||[]){const layer=s.layers.find(l=>l.index===data.index);if(!layer)continue;layer.opacity=clamp(data.opacity,0,1);layer.blend=data.blend||'screen';layer.changes=Number(data.changes)||0;loadLayer(show,layer,Math.max(0,Math.min(show.clips.length-1,Number(data.clipIndex)||0)));}s.recording=Boolean(saved.recording);s.record=Array.isArray(saved.record)?saved.record:[];}
  function patch(){if(typeof VJLiveShow==='undefined'||VJLiveShow.prototype.__core3Patched)return;const p=VJLiveShow.prototype;p.__core3Patched=true;const start=p.start,draw=p.drawProgram,tick=p.tick,snap=p.snapshot,restoreBase=p.restore,dispose=p.dispose,result=p.result;p.start=function(...args){const out=start.apply(this,args);mount(this);return out;};p.drawProgram=function(...args){const out=draw.apply(this,args);drawLayers(this);return out;};p.tick=function(delta){const out=tick.call(this,delta);recordTick(this);if(this.completed&&this.__core3?.recording){this.__core3.recording=false;saveRecording(this);}return out;};p.snapshot=function(){return {...snap.call(this),core3:snapshot(this)};};p.restore=function(saved){const out=restoreBase.call(this,saved);mount(this,saved?.core3);return out;};p.result=function(){const out=result.call(this),s=this.__core3;return {...out,layerCount:1+(s?.layers.length||0),layerChanges:s?.layers.reduce((n,l)=>n+l.changes,0)||0};};p.dispose=function(){if(this.__core3){if(this.__core3.recording)saveRecording(this);this.__core3.layers.forEach(l=>releaseLayer(this,l));}return dispose.call(this);};}
  patch();return {mount,unlockedLayerCount};
})();
